import { createHash,randomUUID } from 'node:crypto';
import { and,desc,eq,sql } from 'drizzle-orm';
import { z } from 'zod';
import { amendmentInput,createVisitInput,draftInput,emptyClinicalBody,finalizationInput } from '../../lib/visits/contracts.ts';
import { authorize,resolveContext,type Database } from '../auth/context.ts';
import { appointments } from '../db/schema/appointments.ts';
import { visits,visitRevisions } from '../db/schema/visits.ts';
import { patients } from '../db/schema/patients.ts';
import { memberships,appUsers } from '../db/schema/organization.ts';
import { auditEvents } from '../db/schema/security.ts';
import { AppError } from '../http/errors.ts';
import type { PatientScope } from '../patients/service.ts';
const parse=<T>(schema:z.ZodType<T>,value:unknown):T=>{const r=schema.safeParse(value);if(!r.success)throw new AppError(400,'INVALID_INPUT','Check the visit details.');return r.data;};
const scoped=(s:PatientScope)=>and(eq(visits.clinicId,s.clinicId),eq(visits.branchId,s.branchId));
async function context(db:Database,s:PatientScope,permission?:'visit.draft.write'|'visit.finalize'){parse(z.object({authUserId:z.uuid(),clinicId:z.uuid(),branchId:z.uuid()}),s);const c=await resolveContext(db,s.authUserId,s.clinicId,s.branchId);authorize(c,'patient.demographics.read');authorize(c,'patient.clinical.read');if(permission)authorize(c,permission);return c;}
async function audit(db:Database,s:PatientScope,actor:string,id:string,action:string){await db.insert(auditEvents).values({clinicId:s.clinicId,branchId:s.branchId,actorMembershipId:actor,entityId:id,entityType:'visit',action,requestId:randomUUID()});}
export async function createVisit(db:Database,s:PatientScope,raw:unknown){const input=parse(createVisitInput,raw);const hash=createHash('sha256').update(JSON.stringify(input)).digest('hex');return db.transaction(async tx=>{const c=await context(tx,s,'visit.draft.write');await tx.execute(sql`select pg_advisory_xact_lock(hashtextextended(${s.clinicId+':'+s.branchId+':visit-operation:'+input.operationId},0))`);await tx.execute(sql`select pg_advisory_xact_lock(hashtextextended(${s.clinicId+':'+s.branchId+':visit:'+ (input.appointmentId??input.operationId)},0))`);const [old]=await tx.select().from(visits).where(and(scoped(s),eq(visits.operationId,input.operationId)));if(old){if(old.payloadHash!==hash)throw new AppError(409,'OPERATION_CONFLICT','This visit key has different details.');return {id:old.id,status:old.status,version:old.version};}const [p]=await tx.select({id:patients.id}).from(patients).where(and(eq(patients.id,input.patientId),eq(patients.clinicId,s.clinicId)));if(!p)throw new AppError(404,'PATIENT_NOT_FOUND','Patient is not available in this clinic.');if(input.appointmentId){authorize(c,'appointment.read');const [a]=await tx.select().from(appointments).where(and(eq(appointments.id,input.appointmentId),eq(appointments.clinicId,s.clinicId),eq(appointments.branchId,s.branchId),eq(appointments.patientId,input.patientId)));if(!a||a.status!=='arrived')throw new AppError(409,'APPOINTMENT_NOT_ARRIVED','Check in the appointment before starting its visit.');const [existing]=await tx.select({id:visits.id}).from(visits).where(and(scoped(s),eq(visits.appointmentId,input.appointmentId)));if(existing)throw new AppError(409,'VISIT_EXISTS','This appointment already has a visit.');}const [row]=await tx.insert(visits).values({clinicId:s.clinicId,branchId:s.branchId,patientId:input.patientId,authorMembershipId:c.membershipId,appointmentId:input.appointmentId,operationId:input.operationId,payloadHash:hash,body:emptyClinicalBody}).returning({id:visits.id,status:visits.status,version:visits.version});await audit(tx,s,c.membershipId,row.id,'visit.started');return row;});}
export async function listVisits(db:Database,s:PatientScope,raw:unknown){const q=parse(z.object({patientId:z.uuid().optional(),offset:z.coerce.number().int().min(0).max(100000).default(0)}),raw);await context(db,s);return db.select({id:visits.id,patientId:visits.patientId,patientName:patients.name,status:visits.status,version:visits.version,createdAt:visits.createdAt,authorName:appUsers.displayName}).from(visits).innerJoin(patients,and(eq(patients.id,visits.patientId),eq(patients.clinicId,visits.clinicId))).innerJoin(memberships,and(eq(memberships.id,visits.authorMembershipId),eq(memberships.clinicId,visits.clinicId))).innerJoin(appUsers,eq(appUsers.id,memberships.userId)).where(and(scoped(s),q.patientId?eq(visits.patientId,q.patientId):undefined)).orderBy(desc(visits.createdAt),desc(visits.id)).limit(50).offset(q.offset);}
export async function readVisit(db:Database,s:PatientScope,id:string){parse(z.uuid(),id);return db.transaction(async tx=>{const c=await context(tx,s);const [row]=await tx.select({visit:visits,patientName:patients.name,patientDisplayId:patients.displayId,authorName:appUsers.displayName}).from(visits).innerJoin(patients,and(eq(patients.id,visits.patientId),eq(patients.clinicId,visits.clinicId))).innerJoin(memberships,and(eq(memberships.id,visits.authorMembershipId),eq(memberships.clinicId,visits.clinicId))).innerJoin(appUsers,eq(appUsers.id,memberships.userId)).where(and(scoped(s),eq(visits.id,id)));if(!row)throw new AppError(404,'VISIT_NOT_FOUND','Visit is not available in this branch.');const revisions=await tx.select({id:visitRevisions.id,revision:visitRevisions.revision,kind:visitRevisions.kind,reason:visitRevisions.reason,body:visitRevisions.body,signedAt:visitRevisions.signedAt,authorName:appUsers.displayName}).from(visitRevisions).innerJoin(memberships,and(eq(memberships.id,visitRevisions.authorMembershipId),eq(memberships.clinicId,visitRevisions.clinicId))).innerJoin(appUsers,eq(appUsers.id,memberships.userId)).where(and(eq(visitRevisions.visitId,id),eq(visitRevisions.clinicId,s.clinicId),eq(visitRevisions.branchId,s.branchId))).orderBy(desc(visitRevisions.revision));return {...row,revisions,canEdit:row.visit.authorMembershipId===c.membershipId&&c.permissions.has('visit.draft.write'),canFinalize:row.visit.authorMembershipId===c.membershipId&&c.permissions.has('visit.finalize')};},{isolationLevel:'repeatable read'});}
export async function saveVisitDraft(db:Database,s:PatientScope,id:string,raw:unknown){parse(z.uuid(),id);const input=parse(draftInput,raw);return db.transaction(async tx=>{const c=await context(tx,s,'visit.draft.write');const [row]=await tx.update(visits).set({body:input.body,version:sql`${visits.version}+1`,updatedAt:new Date()}).where(and(scoped(s),eq(visits.id,id),eq(visits.authorMembershipId,c.membershipId),eq(visits.status,'draft'),eq(visits.version,input.expectedVersion))).returning({id:visits.id,version:visits.version});if(!row)throw new AppError(409,'VISIT_CONFLICT','Draft changed, is signed, or belongs to another clinician. Reload before editing.');await audit(tx,s,c.membershipId,id,'visit.draft_saved');return row;});}
export async function signVisit(db:Database,s:PatientScope,id:string,raw:unknown,amend=false){parse(z.uuid(),id);const amendment=amend?parse(amendmentInput,raw):null;const input=amendment??parse(finalizationInput,raw);const hash=createHash('sha256').update(JSON.stringify({id,amend,...input})).digest('hex');return db.transaction(async tx=>{const c=await context(tx,s,'visit.finalize');await tx.execute(sql`select pg_advisory_xact_lock(hashtextextended(${s.clinicId+':'+s.branchId+':visit-sign:'+input.operationId},0))`);const [old]=await tx.select().from(visitRevisions).where(and(eq(visitRevisions.clinicId,s.clinicId),eq(visitRevisions.branchId,s.branchId),eq(visitRevisions.operationId,input.operationId)));if(old){if(old.payloadHash!==hash)throw new AppError(409,'OPERATION_CONFLICT','This signing key has different details.');return {id:old.id,revision:old.revision};}const [row]=await tx.select().from(visits).where(and(scoped(s),eq(visits.id,id))).for('update');if(!row)throw new AppError(404,'VISIT_NOT_FOUND','Visit is not available in this branch.');if(row.authorMembershipId!==c.membershipId)throw new AppError(403,'VISIT_AUTHOR_REQUIRED','Only the authoring clinician can sign or amend this visit.');if(row.version!==input.expectedVersion||row.status!==(amend?'finalized':'draft'))throw new AppError(409,'VISIT_CONFLICT','Visit changed. Reload before signing.');const body=amendment?.body??row.body;if(!body.complaint||!body.assessment||!body.treatment)throw new AppError(400,'NOTE_INCOMPLETE','Complete complaint, assessment and treatment before signing.');const [latest]=await tx.select({revision:visitRevisions.revision}).from(visitRevisions).where(eq(visitRevisions.visitId,id)).orderBy(desc(visitRevisions.revision)).limit(1);const [revision]=await tx.insert(visitRevisions).values({clinicId:s.clinicId,branchId:s.branchId,patientId:row.patientId,visitId:id,authorMembershipId:c.membershipId,revision:(latest?.revision??0)+1,kind:amend?'amendment':'final',reason:amendment?.reason??'',body,operationId:input.operationId,payloadHash:hash}).returning({id:visitRevisions.id,revision:visitRevisions.revision});await tx.update(visits).set({status:'finalized',body,version:row.version+1,updatedAt:new Date()}).where(eq(visits.id,id));await audit(tx,s,c.membershipId,revision.id,amend?'visit.amended':'visit.finalized');return revision;});}
