import { randomUUID } from 'node:crypto';
import { and,eq,sql } from 'drizzle-orm';
import { z } from 'zod';
import { businessDate } from '../../lib/finance/contracts.ts';
import { authorize,resolveContext,type Database } from '../auth/context.ts';
import { clinics } from '../db/schema/organization.ts';
import { closingApprovals,closingDrafts } from '../db/schema/closing.ts';
import { payments,paymentRefunds } from '../db/schema/finance.ts';
import { expenses } from '../db/schema/expenses.ts';
import { auditEvents } from '../db/schema/security.ts';
import { AppError } from '../http/errors.ts';
import type { PatientScope } from '../patients/service.ts';
import { lockFinancialDay,requireOpenFinancialDay } from './guard.ts';
const count=z.string().regex(/^(?:0|[1-9]\d{0,5})(?:\.\d{1,2})?$/).transform(v=>{const [whole,fraction='']=v.split('.');return Number(whole)*100+Number(fraction.padEnd(2,'0'));}).refine(v=>v<=99999999);
function parse<T>(schema:z.ZodType<T>,raw:unknown):T{const r=schema.safeParse(raw);if(!r.success)throw new AppError(400,'INVALID_INPUT','Check the business date, cash counts and note.');return r.data;}
async function context(db:Database,s:PatientScope,p:'closing.read'|'closing.write'|'closing.approve'){parse(z.object({authUserId:z.uuid(),clinicId:z.uuid(),branchId:z.uuid()}),s);const c=await resolveContext(db,s.authUserId,s.clinicId,s.branchId);authorize(c,p);return c;}
const draftScope=(s:PatientScope,day:string)=>and(eq(closingDrafts.clinicId,s.clinicId),eq(closingDrafts.branchId,s.branchId),eq(closingDrafts.businessDate,day));
const approvedScope=(s:PatientScope,day:string)=>and(eq(closingApprovals.clinicId,s.clinicId),eq(closingApprovals.branchId,s.branchId),eq(closingApprovals.businessDate,day));
async function cashTotals(db:Database,s:PatientScope,day:string){const [receipts]=await db.select({sum:sql<string>`coalesce(sum(${payments.amountMinor}),0)::text`}).from(payments).where(and(eq(payments.clinicId,s.clinicId),eq(payments.branchId,s.branchId),eq(payments.paidOn,day),eq(payments.method,'Cash')));const [paidExpenses]=await db.select({sum:sql<string>`coalesce(sum(${expenses.amountMinor}),0)::text`}).from(expenses).where(and(eq(expenses.clinicId,s.clinicId),eq(expenses.branchId,s.branchId),eq(expenses.paidOn,day),eq(expenses.method,'Cash')));const [refunds]=await db.select({sum:sql<string>`coalesce(sum(${paymentRefunds.amountMinor}),0)::text`}).from(paymentRefunds).where(and(eq(paymentRefunds.clinicId,s.clinicId),eq(paymentRefunds.branchId,s.branchId),eq(paymentRefunds.paidOn,day),eq(paymentRefunds.method,'Cash')));return {cashReceiptsMinor:receipts.sum,cashRefundsMinor:refunds.sum,cashExpensesMinor:paidExpenses.sum};}
async function audit(db:Database,s:PatientScope,actor:string,id:string,action:string){await db.insert(auditEvents).values({clinicId:s.clinicId,branchId:s.branchId,actorMembershipId:actor,entityId:id,entityType:'closing',action,requestId:randomUUID()});}
async function validDay(db:Database,s:PatientScope,day:string){const [clinic]=await db.select().from(clinics).where(eq(clinics.id,s.clinicId));if(clinic?.currency!=='PKR')throw new AppError(409,'CURRENCY_UNSUPPORTED','Closing currently supports PKR clinics.');if(day>businessDate(clinic.timezone))throw new AppError(400,'DATE_FUTURE','Future days cannot be closed.');}
export async function closingSummary(db:Database,s:PatientScope,raw:unknown){const day=parse(z.iso.date(),raw);return db.transaction(async tx=>{await context(tx,s,'closing.read');const [approval]=await tx.select().from(closingApprovals).where(approvedScope(s,day));const [draft]=await tx.select().from(closingDrafts).where(draftScope(s,day));const totals=await cashTotals(tx,s,day);const expectedMinor=(BigInt(draft?.openingMinor??0)+BigInt(totals.cashReceiptsMinor)-BigInt(totals.cashRefundsMinor)-BigInt(totals.cashExpensesMinor)).toString();return {businessDate:day,draft:draft??null,approval:approval??null,...totals,expectedMinor,varianceMinor:(BigInt(draft?.countedMinor??0)-BigInt(expectedMinor)).toString()};},{isolationLevel:'repeatable read'});}
export async function saveClosingDraft(db:Database,s:PatientScope,raw:unknown){const input=parse(z.object({businessDate:z.iso.date(),expectedVersion:z.number().int().min(0),opening:count,counted:count,note:z.string().trim().max(500)}).strict(),raw);return db.transaction(async tx=>{const c=await context(tx,s,'closing.write');await validDay(tx,s,input.businessDate);await requireOpenFinancialDay(tx,s,input.businessDate);const [old]=await tx.select().from(closingDrafts).where(draftScope(s,input.businessDate));if((old?.version??0)!==input.expectedVersion)throw new AppError(409,'CLOSING_CONFLICT','Draft changed. Reload before saving.');const values={clinicId:s.clinicId,branchId:s.branchId,actorMembershipId:c.membershipId,businessDate:input.businessDate,openingMinor:input.opening,countedMinor:input.counted,note:input.note,version:input.expectedVersion+1,updatedAt:new Date()};const [row]=old?await tx.update(closingDrafts).set(values).where(draftScope(s,input.businessDate)).returning():await tx.insert(closingDrafts).values(values).returning();await audit(tx,s,c.membershipId,row.id,'closing.draft_saved');return row;});}
export async function approveClosing(db:Database,s:PatientScope,raw:unknown){const input=parse(z.object({businessDate:z.iso.date(),expectedVersion:z.number().int().positive(),expectedCashMinor:z.string().regex(/^-?\d{1,30}$/)}).strict(),raw);return db.transaction(async tx=>{const c=await context(tx,s,'closing.approve');await validDay(tx,s,input.businessDate);await lockFinancialDay(tx,s,input.businessDate);const [existing]=await tx.select().from(closingApprovals).where(approvedScope(s,input.businessDate));if(existing){if(existing.draftVersion!==input.expectedVersion||existing.snapshot.expectedMinor!==input.expectedCashMinor)throw new AppError(409,'CLOSING_CONFLICT','This day was approved with another snapshot.');return existing;}const [draft]=await tx.select().from(closingDrafts).where(draftScope(s,input.businessDate));if(!draft||draft.version!==input.expectedVersion)throw new AppError(409,'CLOSING_CONFLICT','Draft changed. Reload before approving.');if(draft.actorMembershipId===c.membershipId)throw new AppError(403,'SECOND_APPROVER_REQUIRED','A different authorized staff member must approve the closing.');const totals=await cashTotals(tx,s,input.businessDate);const expected=BigInt(draft.openingMinor)+BigInt(totals.cashReceiptsMinor)-BigInt(totals.cashRefundsMinor)-BigInt(totals.cashExpensesMinor);if(expected<0)throw new AppError(409,'NEGATIVE_CASH','Expected cash is negative. Reconcile the day before closing.');if(expected.toString()!==input.expectedCashMinor)throw new AppError(409,'CASH_CHANGED','Cash transactions changed. Review the new totals before approving.');const variance=BigInt(draft.countedMinor)-expected;if(variance!==BigInt(0)&&draft.note.length<3)throw new AppError(400,'VARIANCE_NOTE_REQUIRED','Explain the cash difference before approving.');const [row]=await tx.insert(closingApprovals).values({clinicId:s.clinicId,branchId:s.branchId,actorMembershipId:c.membershipId,businessDate:input.businessDate,draftId:draft.id,draftVersion:draft.version,snapshot:{currency:'PKR',openingMinor:String(draft.openingMinor),countedMinor:String(draft.countedMinor),...totals,expectedMinor:expected.toString(),varianceMinor:variance.toString(),note:draft.note}}).returning();await audit(tx,s,c.membershipId,row.id,'closing.approved');return row;});}
