import { createHash,randomUUID } from 'node:crypto';
import { and,asc,desc,eq,sql } from 'drizzle-orm';
import { z } from 'zod';
import { businessDate,chargeInput,paymentInput,refundInput } from '../../lib/finance/contracts.ts';
import { authorize,resolveContext,type Database } from '../auth/context.ts';
import { branches,clinics } from '../db/schema/organization.ts';
import { patients } from '../db/schema/patients.ts';
import { charges,paymentAllocations,payments,receipts,paymentRefunds,allocationReversals } from '../db/schema/finance.ts';
import { auditEvents } from '../db/schema/security.ts';
import { requireOpenFinancialDay } from '../closing/guard.ts';
import { AppError } from '../http/errors.ts';
import type { PatientScope } from '../patients/service.ts';
const parse=<T>(schema:z.ZodType<T>,raw:unknown):T=>{const r=schema.safeParse(raw);if(!r.success)throw new AppError(400,'INVALID_INPUT','Check the financial details and amount.');return r.data;};
async function context(db:Database,scope:PatientScope,permission:'billing.read'|'charge.post'|'payment.post'|'refund.post'){
 parse(z.object({authUserId:z.uuid(),clinicId:z.uuid(),branchId:z.uuid()}),scope);const c=await resolveContext(db,scope.authUserId,scope.clinicId,scope.branchId);authorize(c,permission);authorize(c,'patient.demographics.read');return c;
}
async function operationLock(db:Database,s:PatientScope,kind:string,key:string){await db.execute(sql`select pg_advisory_xact_lock(hashtextextended(${s.clinicId+':'+s.branchId+':'+kind+':'+key},0))`);}
async function accountLock(db:Database,scope:PatientScope,id:string){await db.execute(sql`select pg_advisory_xact_lock(hashtextextended(${scope.clinicId+':'+scope.branchId+':account:'+id},0))`);}
async function patient(db:Database,s:PatientScope,id:string){const [row]=await db.select().from(patients).where(and(eq(patients.clinicId,s.clinicId),eq(patients.id,id)));if(!row)throw new AppError(404,'PATIENT_NOT_FOUND','Patient is not available in this clinic.');return row;}
async function clinic(db:Database,s:PatientScope){const [row]=await db.select({name:clinics.name,currency:clinics.currency,timezone:clinics.timezone,branchName:branches.name}).from(clinics).innerJoin(branches,eq(branches.clinicId,clinics.id)).where(and(eq(clinics.id,s.clinicId),eq(branches.id,s.branchId)));if(row?.currency!=='PKR')throw new AppError(409,'CURRENCY_UNSUPPORTED','Billing currently supports PKR clinics.');return row;}
async function audit(db:Database,s:PatientScope,actor:string,id:string,action:string){await db.insert(auditEvents).values({clinicId:s.clinicId,branchId:s.branchId,actorMembershipId:actor,entityId:id,entityType:'finance',action,requestId:randomUUID()});}
const chargeScope=(s:PatientScope,id:string)=>and(eq(charges.clinicId,s.clinicId),eq(charges.branchId,s.branchId),eq(charges.patientId,id));
const paymentScope=(s:PatientScope,id:string)=>and(eq(payments.clinicId,s.clinicId),eq(payments.branchId,s.branchId),eq(payments.patientId,id));
async function totals(db:Database,s:PatientScope,id:string){const [c]=await db.select({sum:sql<string>`coalesce(sum(${charges.amountMinor}),0)::text`}).from(charges).where(chargeScope(s,id));const [p]=await db.select({sum:sql<string>`coalesce(sum(${payments.amountMinor}),0)::text`}).from(payments).where(paymentScope(s,id));const [r]=await db.select({sum:sql<string>`coalesce(sum(${paymentRefunds.amountMinor}),0)::text`}).from(paymentRefunds).where(and(eq(paymentRefunds.clinicId,s.clinicId),eq(paymentRefunds.branchId,s.branchId),eq(paymentRefunds.patientId,id)));const paid=BigInt(p.sum)-BigInt(r.sum);return {chargedMinor:c.sum,paidMinor:paid.toString(),balanceMinor:(BigInt(c.sum)-paid).toString()};}
export async function postCharge(db:Database,s:PatientScope,raw:unknown){const input=parse(chargeInput,raw);const hash=createHash('sha256').update(JSON.stringify(input)).digest('hex');return db.transaction(async tx=>{
 const c=await context(tx,s,'charge.post');await operationLock(tx,s,'charge',input.operationId);await accountLock(tx,s,input.patientId);
 const [old]=await tx.select().from(charges).where(and(eq(charges.clinicId,s.clinicId),eq(charges.branchId,s.branchId),eq(charges.operationId,input.operationId)));if(old){if(old.payloadHash!==hash)throw new AppError(409,'OPERATION_CONFLICT','This charge key has different details.');return old;}
 await patient(tx,s,input.patientId);const organization=await clinic(tx,s);await requireOpenFinancialDay(tx,s,businessDate(organization.timezone));
 const [row]=await tx.insert(charges).values({clinicId:s.clinicId,branchId:s.branchId,patientId:input.patientId,actorMembershipId:c.membershipId,operationId:input.operationId,payloadHash:hash,amountMinor:input.amount,currency:organization.currency,description:input.description}).returning();await audit(tx,s,c.membershipId,row.id,'charge.posted');return row;
});}
export async function postPayment(db:Database,s:PatientScope,raw:unknown){const input=parse(paymentInput,raw);const hash=createHash('sha256').update(JSON.stringify(input)).digest('hex');return db.transaction(async tx=>{
 const c=await context(tx,s,'payment.post');await operationLock(tx,s,'payment',input.operationId);await accountLock(tx,s,input.patientId);
 const [old]=await tx.select().from(payments).where(and(eq(payments.clinicId,s.clinicId),eq(payments.branchId,s.branchId),eq(payments.operationId,input.operationId)));if(old){if(old.payloadHash!==hash)throw new AppError(409,'OPERATION_CONFLICT','This payment key has different details.');const [receipt]=await tx.select({id:receipts.id,number:receipts.number}).from(receipts).where(eq(receipts.paymentId,old.id));return {payment:old,receipt};}
 const p=await patient(tx,s,input.patientId);const organization=await clinic(tx,s);if(input.paidOn>businessDate(organization.timezone))throw new AppError(400,'PAYMENT_DATE_FUTURE','A recorded payment cannot be dated in the future.');await requireOpenFinancialDay(tx,s,input.paidOn);const before=await totals(tx,s,input.patientId);if(BigInt(input.amount)>BigInt(before.balanceMinor))throw new AppError(409,'OVERPAYMENT','Payment exceeds this branch account’s outstanding balance.');
 const pending=await tx.select({id:charges.id,description:charges.description,amountMinor:charges.amountMinor,allocated:sql<string>`coalesce((select sum(a.amount_minor-coalesce((select sum(r.amount_minor) from clinic_app.allocation_reversals r where r.allocation_id=a.id),0)) from clinic_app.payment_allocations a where a.charge_id=${charges.id}),0)::text`}).from(charges).where(chargeScope(s,input.patientId)).orderBy(asc(charges.createdAt),asc(charges.id));
 let remaining=input.amount;const allocations:{chargeId:string;description:string;amountMinor:number}[]=[];for(const charge of pending){const outstanding=charge.amountMinor-Number(charge.allocated);const amount=Math.min(remaining,outstanding);if(amount>0){allocations.push({chargeId:charge.id,description:charge.description,amountMinor:amount});remaining-=amount;}if(!remaining)break;}if(remaining!==0)throw new AppError(409,'ALLOCATION_CONFLICT','Account allocations could not be reconciled.');
 const [row]=await tx.insert(payments).values({clinicId:s.clinicId,branchId:s.branchId,patientId:input.patientId,actorMembershipId:c.membershipId,operationId:input.operationId,payloadHash:hash,amountMinor:input.amount,currency:organization.currency,method:input.method,paidOn:input.paidOn}).returning();
 await tx.insert(paymentAllocations).values(allocations.map(a=>({clinicId:s.clinicId,branchId:s.branchId,patientId:input.patientId,paymentId:row.id,chargeId:a.chargeId,amountMinor:a.amountMinor})));
 const receiptId=randomUUID();const number='R-'+receiptId.toUpperCase();const [receipt]=await tx.insert(receipts).values({id:receiptId,clinicId:s.clinicId,branchId:s.branchId,patientId:input.patientId,paymentId:row.id,number,snapshot:{clinicName:organization.name,branchName:organization.branchName,patientName:p.name,patientDisplayId:p.displayId,currency:organization.currency,method:input.method,paidOn:input.paidOn,amountMinor:input.amount,chargedMinor:before.chargedMinor,paidMinor:(BigInt(before.paidMinor)+BigInt(input.amount)).toString(),balanceMinor:(BigInt(before.balanceMinor)-BigInt(input.amount)).toString(),allocations}}).returning({id:receipts.id,number:receipts.number});
 await audit(tx,s,c.membershipId,row.id,'payment.posted');return {payment:row,receipt};
});}
export async function patientAccount(db:Database,s:PatientScope,id:string){parse(z.uuid(),id);return db.transaction(async tx=>{await context(tx,s,'billing.read');const p=await patient(tx,s,id);const amounts=await totals(tx,s,id);const postedCharges=await tx.select({id:charges.id,description:charges.description,amountMinor:charges.amountMinor,createdAt:charges.createdAt}).from(charges).where(chargeScope(s,id)).orderBy(desc(charges.createdAt),desc(charges.id)).limit(100);const postedPayments=await tx.select({id:payments.id,amountMinor:payments.amountMinor,method:payments.method,paidOn:payments.paidOn,receiptId:receipts.id,receiptNumber:receipts.number}).from(payments).innerJoin(receipts,eq(receipts.paymentId,payments.id)).where(paymentScope(s,id)).orderBy(desc(payments.createdAt),desc(payments.id)).limit(100);const refunds=await tx.select({id:paymentRefunds.id,paymentId:paymentRefunds.paymentId,amountMinor:paymentRefunds.amountMinor,paidOn:paymentRefunds.paidOn,method:paymentRefunds.method,reason:paymentRefunds.reason}).from(paymentRefunds).where(and(eq(paymentRefunds.clinicId,s.clinicId),eq(paymentRefunds.branchId,s.branchId),eq(paymentRefunds.patientId,id))).orderBy(desc(paymentRefunds.createdAt),desc(paymentRefunds.id)).limit(100);return {patient:{id:p.id,name:p.name,displayId:p.displayId},...amounts,charges:postedCharges,payments:postedPayments,refunds};},{isolationLevel:'repeatable read'});}
export async function getReceipt(db:Database,s:PatientScope,id:string){parse(z.uuid(),id);await context(db,s,'billing.read');const [row]=await db.select({id:receipts.id,number:receipts.number,snapshot:receipts.snapshot,createdAt:receipts.createdAt}).from(receipts).where(and(eq(receipts.id,id),eq(receipts.clinicId,s.clinicId),eq(receipts.branchId,s.branchId)));if(!row)throw new AppError(404,'RECEIPT_NOT_FOUND','Receipt is not available in this branch.');return row;}

export async function postRefund(db:Database,s:PatientScope,paymentId:string,raw:unknown){parse(z.uuid(),paymentId);const input=parse(refundInput,raw);const hash=createHash('sha256').update(JSON.stringify({paymentId,...input})).digest('hex');return db.transaction(async tx=>{
 const c=await context(tx,s,'refund.post');await operationLock(tx,s,'refund',input.operationId);const [original]=await tx.select().from(payments).where(and(eq(payments.id,paymentId),eq(payments.clinicId,s.clinicId),eq(payments.branchId,s.branchId)));if(!original)throw new AppError(404,'PAYMENT_NOT_FOUND','Payment is not available in this branch.');await accountLock(tx,s,original.patientId);
 const [old]=await tx.select().from(paymentRefunds).where(and(eq(paymentRefunds.clinicId,s.clinicId),eq(paymentRefunds.branchId,s.branchId),eq(paymentRefunds.operationId,input.operationId)));if(old){if(old.payloadHash!==hash)throw new AppError(409,'OPERATION_CONFLICT','This refund key has different details.');return old;}
 const organization=await clinic(tx,s);if(input.paidOn<original.paidOn)throw new AppError(400,'REFUND_DATE_INVALID','Refund cannot precede its original payment.');if(input.paidOn>businessDate(organization.timezone))throw new AppError(400,'DATE_FUTURE','A refund cannot be dated in the future.');await requireOpenFinancialDay(tx,s,input.paidOn);
 const [previous]=await tx.select({sum:sql<string>`coalesce(sum(${paymentRefunds.amountMinor}),0)::text`}).from(paymentRefunds).where(eq(paymentRefunds.paymentId,paymentId));if(BigInt(input.amount)>BigInt(original.amountMinor)-BigInt(previous.sum))throw new AppError(409,'REFUND_EXCEEDS_PAYMENT','Refund exceeds the original payment’s remaining refundable amount.');
 const allocated=await tx.select({id:paymentAllocations.id,chargeId:paymentAllocations.chargeId,amountMinor:paymentAllocations.amountMinor,reversed:sql<string>`coalesce((select sum(r.amount_minor) from clinic_app.allocation_reversals r where r.allocation_id=${paymentAllocations.id}),0)::text`,description:charges.description}).from(paymentAllocations).innerJoin(charges,eq(charges.id,paymentAllocations.chargeId)).where(eq(paymentAllocations.paymentId,paymentId)).orderBy(desc(charges.createdAt),desc(charges.id));
 let remaining=input.amount;const reversals:{allocationId:string;chargeId:string;description:string;amountMinor:number}[]=[];for(const a of allocated){const amount=Math.min(remaining,a.amountMinor-Number(a.reversed));if(amount>0){reversals.push({allocationId:a.id,chargeId:a.chargeId,description:a.description,amountMinor:amount});remaining-=amount;}if(!remaining)break;}if(remaining)throw new AppError(409,'ALLOCATION_CONFLICT','Refund allocations could not be reconciled.');
 const before=await totals(tx,s,original.patientId);const p=await patient(tx,s,original.patientId);const [row]=await tx.insert(paymentRefunds).values({clinicId:s.clinicId,branchId:s.branchId,patientId:original.patientId,actorMembershipId:c.membershipId,paymentId,operationId:input.operationId,payloadHash:hash,amountMinor:input.amount,currency:original.currency,method:original.method,paidOn:input.paidOn,reason:input.reason,snapshot:{clinicName:organization.name,branchName:organization.branchName,patientName:p.name,patientDisplayId:p.displayId,currency:original.currency,method:original.method,paidOn:input.paidOn,amountMinor:input.amount,chargedMinor:before.chargedMinor,paidMinor:(BigInt(before.paidMinor)-BigInt(input.amount)).toString(),balanceMinor:(BigInt(before.balanceMinor)+BigInt(input.amount)).toString(),allocations:reversals.map(({chargeId,description,amountMinor})=>({chargeId,description,amountMinor}))}}).returning();
 await tx.insert(allocationReversals).values(reversals.map(a=>({clinicId:s.clinicId,branchId:s.branchId,patientId:original.patientId,paymentId,allocationId:a.allocationId,refundId:row.id,amountMinor:a.amountMinor})));await audit(tx,s,c.membershipId,row.id,'payment.refunded');return row;
});}
export async function getRefundReceipt(db:Database,s:PatientScope,id:string){parse(z.uuid(),id);await context(db,s,'billing.read');const [row]=await db.select({id:paymentRefunds.id,snapshot:paymentRefunds.snapshot,reason:paymentRefunds.reason,createdAt:paymentRefunds.createdAt}).from(paymentRefunds).where(and(eq(paymentRefunds.id,id),eq(paymentRefunds.clinicId,s.clinicId),eq(paymentRefunds.branchId,s.branchId)));if(!row)throw new AppError(404,'REFUND_NOT_FOUND','Refund is not available in this branch.');return {...row,number:'RF-'+row.id.toUpperCase()};}
