import { createHash,randomUUID } from 'node:crypto';
import { and,asc,desc,eq,gt,lt,notInArray,sql } from 'drizzle-orm';
import { z } from 'zod';
import { canTransition,createFollowUpInput,followUpBooking,followUpMutation,followUpQuery,type FollowUpStatus } from '../../lib/follow-ups/contracts.ts';
import { businessDate } from '../../lib/finance/contracts.ts';
import { authorize,resolveContext,type Database } from '../auth/context.ts';
import { appUsers,clinics,memberships,membershipBranches } from '../db/schema/organization.ts';
import { followUps,followUpEvents,type FollowUpEventDetail } from '../db/schema/follow-ups.ts';
import { patients } from '../db/schema/patients.ts';
import { appointments } from '../db/schema/appointments.ts';
import { visits } from '../db/schema/visits.ts';
import { auditEvents } from '../db/schema/security.ts';
import { bookAppointment } from '../appointments/service.ts';
import { AppError } from '../http/errors.ts';
import type { PatientScope } from '../patients/service.ts';
const parse=<T>(schema:z.ZodType<T>,value:unknown):T=>{const r=schema.safeParse(value);if(!r.success)throw new AppError(400,'INVALID_INPUT','Check the follow-up details, date and status.');return r.data;};
const scoped=(s:PatientScope)=>and(eq(followUps.clinicId,s.clinicId),eq(followUps.branchId,s.branchId));
const hash=(value:unknown)=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
async function context(db:Database,s:PatientScope,write=false){parse(z.object({authUserId:z.uuid(),clinicId:z.uuid(),branchId:z.uuid()}),s);const c=await resolveContext(db,s.authUserId,s.clinicId,s.branchId);for(const p of ['patient.demographics.read','patient.clinical.read','followup.read'] as const)authorize(c,p);if(write)authorize(c,'followup.write');return c;}
async function lock(db:Database,s:PatientScope,id:string){await db.execute(sql`select pg_advisory_xact_lock(hashtextextended(${s.clinicId+':'+s.branchId+':followup-operation:'+id},0))`);}
async function replay(db:Database,s:PatientScope,operationId:string,digest:string){const [event]=await db.select().from(followUpEvents).where(and(eq(followUpEvents.clinicId,s.clinicId),eq(followUpEvents.branchId,s.branchId),eq(followUpEvents.operationId,operationId)));if(event&&event.payloadHash!==digest)throw new AppError(409,'OPERATION_CONFLICT','This operation key has different follow-up details.');return event?{id:event.followUpId,version:event.version,appointmentId:event.detail.appointmentId??null}:null;}
async function append(db:Database,s:PatientScope,actor:string,id:string,version:number,kind:string,detail:FollowUpEventDetail,operationId:string,digest:string){await db.insert(followUpEvents).values({clinicId:s.clinicId,branchId:s.branchId,actorMembershipId:actor,followUpId:id,version,kind,detail,operationId,payloadHash:digest});await db.insert(auditEvents).values({clinicId:s.clinicId,branchId:s.branchId,actorMembershipId:actor,entityId:id,entityType:'follow_up',action:`followup.${kind}`,requestId:randomUUID()});}
async function assignee(db:Database,s:PatientScope,id:string|null){if(!id)return;const [row]=await db.select({authUserId:appUsers.authUserId}).from(memberships).innerJoin(appUsers,eq(appUsers.id,memberships.userId)).innerJoin(membershipBranches,and(eq(membershipBranches.membershipId,memberships.id),eq(membershipBranches.clinicId,memberships.clinicId))).where(and(eq(memberships.id,id),eq(memberships.clinicId,s.clinicId),eq(memberships.active,true),eq(appUsers.active,true),eq(membershipBranches.branchId,s.branchId)));if(!row)throw new AppError(400,'ASSIGNEE_UNAVAILABLE','Choose active staff with follow-up access in this branch.');const c=await resolveContext(db,row.authUserId,s.clinicId,s.branchId);if(!['followup.read','patient.clinical.read','patient.demographics.read'].every(p=>c.permissions.has(p)))throw new AppError(400,'ASSIGNEE_UNAVAILABLE','Choose active staff with follow-up access in this branch.');}
async function locked(db:Database,s:PatientScope,id:string,version:number){const [row]=await db.select().from(followUps).where(and(scoped(s),eq(followUps.id,id))).for('update');if(!row)throw new AppError(404,'FOLLOWUP_NOT_FOUND','Follow-up is not available in this branch.');if(row.version!==version)throw new AppError(409,'FOLLOWUP_CONFLICT','Follow-up changed. Reload before saving.');if(row.status==='completed'||row.status==='closed')throw new AppError(409,'FOLLOWUP_FINISHED','This follow-up is finished. Create a new follow-up for further care.');return row;}
export async function createFollowUp(db:Database,s:PatientScope,raw:unknown){const input=parse(createFollowUpInput,raw);const digest=hash({action:'create',...input});return db.transaction(async tx=>{const c=await context(tx,s,true);await lock(tx,s,input.operationId);const old=await replay(tx,s,input.operationId,digest);if(old)return old;const [patient]=await tx.select({id:patients.id}).from(patients).where(and(eq(patients.clinicId,s.clinicId),eq(patients.id,input.patientId)));if(!patient)throw new AppError(404,'PATIENT_NOT_FOUND','Patient is not available in this clinic.');if(input.visitId){const [visit]=await tx.select({id:visits.id}).from(visits).where(and(eq(visits.id,input.visitId),eq(visits.clinicId,s.clinicId),eq(visits.branchId,s.branchId),eq(visits.patientId,input.patientId)));if(!visit)throw new AppError(404,'VISIT_NOT_FOUND','Visit is not available for this patient in this branch.');}await assignee(tx,s,input.assigneeId);const [row]=await tx.insert(followUps).values({clinicId:s.clinicId,branchId:s.branchId,patientId:input.patientId,visitId:input.visitId,type:input.type,customType:input.customType,dueOn:input.dueOn,assigneeId:input.assigneeId,actorMembershipId:c.membershipId,operationId:input.operationId,payloadHash:digest}).returning();await append(tx,s,c.membershipId,row.id,1,'created',{note:input.note,dueOn:input.dueOn,assigneeId:input.assigneeId,status:'due'},input.operationId,digest);return {id:row.id,version:1};});}
export async function listFollowUps(db:Database,s:PatientScope,raw:unknown){const q=parse(followUpQuery,raw);return db.transaction(async tx=>{await context(tx,s);const [clinic]=await tx.select({timezone:clinics.timezone}).from(clinics).where(eq(clinics.id,s.clinicId));const today=businessDate(clinic.timezone);const rows=await tx.select({id:followUps.id,patientName:patients.name,patientId:followUps.patientId,type:followUps.type,customType:followUps.customType,dueOn:followUps.dueOn,status:followUps.status,version:followUps.version,assigneeId:followUps.assigneeId}).from(followUps).innerJoin(patients,and(eq(patients.clinicId,followUps.clinicId),eq(patients.id,followUps.patientId))).where(and(scoped(s),q.status==='open'?notInArray(followUps.status,['completed','closed']):q.status==='all'?undefined:eq(followUps.status,q.status),q.bucket==='today'?eq(followUps.dueOn,today):q.bucket==='overdue'?lt(followUps.dueOn,today):q.bucket==='upcoming'?gt(followUps.dueOn,today):undefined,q.patientId?eq(followUps.patientId,q.patientId):undefined,q.assigneeId?eq(followUps.assigneeId,q.assigneeId):undefined)).orderBy(asc(followUps.dueOn),asc(followUps.id)).limit(51).offset(q.offset);return {today,items:rows.slice(0,50),hasMore:rows.length>50};},{isolationLevel:'repeatable read'});}
export async function followUpStaff(db:Database,s:PatientScope){await context(db,s);const candidates=await db.select({id:memberships.id,name:appUsers.displayName,authUserId:appUsers.authUserId}).from(memberships).innerJoin(appUsers,eq(appUsers.id,memberships.userId)).innerJoin(membershipBranches,and(eq(membershipBranches.membershipId,memberships.id),eq(membershipBranches.clinicId,memberships.clinicId))).where(and(eq(memberships.clinicId,s.clinicId),eq(membershipBranches.branchId,s.branchId),eq(memberships.active,true),eq(appUsers.active,true))).orderBy(asc(appUsers.displayName),asc(memberships.id)).limit(100);const result:{id:string;name:string}[]=[];for(const candidate of candidates){const c=await resolveContext(db,candidate.authUserId,s.clinicId,s.branchId);if(['followup.read','patient.clinical.read','patient.demographics.read'].every(p=>c.permissions.has(p)))result.push({id:candidate.id,name:candidate.name});}return result;}
export async function readFollowUp(db:Database,s:PatientScope,id:string){parse(z.uuid(),id);return db.transaction(async tx=>{const c=await context(tx,s);const [row]=await tx.select({followUp:followUps,patientName:patients.name}).from(followUps).innerJoin(patients,and(eq(patients.clinicId,followUps.clinicId),eq(patients.id,followUps.patientId))).where(and(scoped(s),eq(followUps.id,id)));if(!row)throw new AppError(404,'FOLLOWUP_NOT_FOUND','Follow-up is not available in this branch.');const events=await tx.select({id:followUpEvents.id,kind:followUpEvents.kind,version:followUpEvents.version,detail:followUpEvents.detail,createdAt:followUpEvents.createdAt,actorName:appUsers.displayName}).from(followUpEvents).innerJoin(memberships,and(eq(memberships.clinicId,followUpEvents.clinicId),eq(memberships.id,followUpEvents.actorMembershipId))).innerJoin(appUsers,eq(appUsers.id,memberships.userId)).where(and(eq(followUpEvents.clinicId,s.clinicId),eq(followUpEvents.branchId,s.branchId),eq(followUpEvents.followUpId,id))).orderBy(desc(followUpEvents.version)).limit(100);let appointment:null|{id:string;status:string;startsAt:Date}=null;if(row.followUp.appointmentId&&c.permissions.has('appointment.read')){const [linked]=await tx.select({id:appointments.id,status:appointments.status,startsAt:appointments.startsAt}).from(appointments).where(and(eq(appointments.id,row.followUp.appointmentId),eq(appointments.clinicId,s.clinicId),eq(appointments.branchId,s.branchId),eq(appointments.patientId,row.followUp.patientId)));appointment=linked??null;}return {...row,events,appointment,canWrite:c.permissions.has('followup.write'),canBook:c.permissions.has('followup.write')&&c.permissions.has('appointment.read')&&c.permissions.has('appointment.write')};},{isolationLevel:'repeatable read'});}
export async function mutateFollowUp(db:Database,s:PatientScope,id:string,raw:unknown){parse(z.uuid(),id);const input=parse(followUpMutation,raw);const digest=hash({id,...input});return db.transaction(async tx=>{const c=await context(tx,s,true);await lock(tx,s,input.operationId);const old=await replay(tx,s,input.operationId,digest);if(old)return old;const row=await locked(tx,s,id,input.expectedVersion);let values:Partial<typeof followUps.$inferInsert>={version:row.version+1};let detail:FollowUpEventDetail={note:input.note};if(input.action==='edit'){await assignee(tx,s,input.assigneeId);values={...values,dueOn:input.dueOn,assigneeId:input.assigneeId};detail={...detail,dueOn:input.dueOn,assigneeId:input.assigneeId};}else if(input.action==='transition'){if(!canTransition(row.status as FollowUpStatus,input.status))throw new AppError(409,'INVALID_TRANSITION','Choose a different valid follow-up state.');if(input.status==='booked'){authorize(c,'appointment.read');if(!input.appointmentId)throw new AppError(400,'APPOINTMENT_REQUIRED','Select a booking for this patient.');const [appointment]=await tx.select().from(appointments).where(and(eq(appointments.id,input.appointmentId),eq(appointments.clinicId,s.clinicId),eq(appointments.branchId,s.branchId),eq(appointments.patientId,row.patientId))).for('update');if(!appointment||appointment.status==='cancelled'||appointment.status==='no_show')throw new AppError(409,'BOOKING_UNAVAILABLE','Booking is cancelled, missed or unavailable for this patient.');}else if(input.appointmentId)throw new AppError(400,'INVALID_INPUT','Appointment linking is only available for Booked status.');const appointmentId=input.status==='booked'?input.appointmentId:input.status==='completed'||input.status==='closed'?row.appointmentId:null;values={...values,status:input.status,appointmentId};detail={...detail,fromStatus:row.status,status:input.status,appointmentId};}else{detail={...detail,channel:input.channel,outcome:input.outcome};}await tx.update(followUps).set(values).where(eq(followUps.id,id));await append(tx,s,c.membershipId,id,row.version+1,input.action==='edit'?'edited':input.action,detail,input.operationId,digest);return {id,version:row.version+1};});}
export async function bookFollowUp(db:Database,s:PatientScope,id:string,raw:unknown){parse(z.uuid(),id);const input=parse(followUpBooking,raw);const digest=hash({id,action:'book',...input});return db.transaction(async tx=>{const c=await context(tx,s,true);authorize(c,'appointment.read');authorize(c,'appointment.write');await lock(tx,s,input.operationId);const old=await replay(tx,s,input.operationId,digest);if(old)return old;const row=await locked(tx,s,id,input.expectedVersion);if(row.status==='booked')throw new AppError(409,'ALREADY_BOOKED','This follow-up already has a booking. Review it before booking again.');if(input.startsAt<=new Date())throw new AppError(400,'BOOKING_IN_PAST','Choose a future follow-up booking.');const appointment=await bookAppointment(tx,s,{patientId:row.patientId,operationId:input.operationId,startsAt:input.startsAt.toISOString(),endsAt:input.endsAt.toISOString(),dentistId:input.dentistId,chairId:input.chairId,procedureId:input.procedureId,source:'follow_up',reason:row.customType||row.type,override:input.override});await tx.update(followUps).set({status:'booked',appointmentId:appointment.id,version:row.version+1}).where(eq(followUps.id,id));await append(tx,s,c.membershipId,id,row.version+1,'booked',{note:input.note,fromStatus:row.status,status:'booked',appointmentId:appointment.id},input.operationId,digest);return {id,version:row.version+1,appointmentId:appointment.id};});}
