import { sql } from 'drizzle-orm';
import { boolean,check,foreignKey,index,integer,jsonb,primaryKey,text,timestamp,unique,uuid } from 'drizzle-orm/pg-core';
import { branches,clinicApp,memberships } from './organization.ts';
import { appointments } from './appointments.ts';
import { patients } from './patients.ts';
const time=(name:string)=>timestamp(name,{withTimezone:true});
export const messagingPreferences=clinicApp.table('messaging_preferences',{
 clinicId:uuid('clinic_id').notNull(),patientId:uuid('patient_id').notNull(),branchId:uuid('branch_id').notNull(),actorMembershipId:uuid('actor_membership_id').notNull(),
 enabled:boolean('enabled').notNull(),recipient:text('recipient').notNull(),evidence:text('evidence').notNull(),version:integer('version').notNull(),updatedAt:time('updated_at').defaultNow().notNull(),
},t=>[primaryKey({columns:[t.clinicId,t.patientId]}),foreignKey({name:'preferences_patient_fk',columns:[t.clinicId,t.patientId],foreignColumns:[patients.clinicId,patients.id]}),foreignKey({name:'preferences_branch_fk',columns:[t.clinicId,t.branchId],foreignColumns:[branches.clinicId,branches.id]}),foreignKey({name:'preferences_actor_fk',columns:[t.clinicId,t.actorMembershipId],foreignColumns:[memberships.clinicId,memberships.id]}),check('preferences_version',sql`${t.version}>0`),check('preferences_recipient',sql`${t.recipient} ~ '^[1-9][0-9]{7,14}$'`)]);
export const communicationJobs=clinicApp.table('communication_jobs',{
 id:uuid('id').primaryKey().defaultRandom(),clinicId:uuid('clinic_id').notNull(),branchId:uuid('branch_id').notNull(),patientId:uuid('patient_id').notNull(),actorMembershipId:uuid('actor_membership_id').notNull(),
 operationId:uuid('operation_id').notNull(),payloadHash:text('payload_hash').notNull(),recipient:text('recipient').notNull(),preferenceVersion:integer('preference_version').notNull(),template:text('template').notNull(),language:text('language').notNull(),parameters:jsonb('parameters').$type<string[]>().notNull(),
 appointmentId:uuid('appointment_id'),appointmentVersion:integer('appointment_version'),state:text('state').notNull().default('queued'),attempts:integer('attempts').notNull().default(0),availableAt:time('available_at').notNull().defaultNow(),leaseUntil:time('lease_until'),leaseToken:uuid('lease_token'),providerMessageId:text('provider_message_id'),deliveryStatus:text('delivery_status'),lastCode:text('last_code'),createdAt:time('created_at').defaultNow().notNull(),
},t=>[foreignKey({name:'communication_appointment_scope_fk',columns:[t.clinicId,t.branchId,t.patientId,t.appointmentId],foreignColumns:[appointments.clinicId,appointments.branchId,appointments.patientId,appointments.id]}),unique('communication_operation_unique').on(t.clinicId,t.branchId,t.operationId),unique('communication_scope_unique').on(t.clinicId,t.branchId,t.id),unique('communication_provider_unique').on(t.providerMessageId),foreignKey({name:'communication_patient_fk',columns:[t.clinicId,t.patientId],foreignColumns:[patients.clinicId,patients.id]}),foreignKey({name:'communication_branch_fk',columns:[t.clinicId,t.branchId],foreignColumns:[branches.clinicId,branches.id]}),foreignKey({name:'communication_actor_fk',columns:[t.clinicId,t.actorMembershipId],foreignColumns:[memberships.clinicId,memberships.id]}),check('communication_state',sql`${t.state} in ('queued','processing','sending','submitted','review','failed','cancelled')`),check('communication_attempts',sql`${t.attempts} between 0 and 5`),check('communication_recipient',sql`${t.recipient} ~ '^[1-9][0-9]{7,14}$'`),check('communication_delivery',sql`${t.deliveryStatus} is null or ${t.deliveryStatus} in ('sent','delivered','read','failed')`),check('communication_appointment_pair',sql`(${t.appointmentId} is null) = (${t.appointmentVersion} is null)`),index('communication_queue_idx').on(t.clinicId,t.state,t.availableAt),index('communication_branch_idx').on(t.clinicId,t.branchId,t.createdAt)]);
export const communicationEvents=clinicApp.table('communication_events',{
 id:uuid('id').primaryKey().defaultRandom(),clinicId:uuid('clinic_id').notNull(),branchId:uuid('branch_id').notNull(),jobId:uuid('job_id').notNull(),eventKey:text('event_key').notNull(),kind:text('kind').notNull(),code:text('code'),occurredAt:time('occurred_at').defaultNow().notNull(),
},t=>[unique('communication_event_key_unique').on(t.eventKey),foreignKey({name:'communication_event_job_fk',columns:[t.clinicId,t.branchId,t.jobId],foreignColumns:[communicationJobs.clinicId,communicationJobs.branchId,communicationJobs.id]})]);
export const messagingWebhookReceipts=clinicApp.table('messaging_webhook_receipts',{
 id:uuid('id').primaryKey().defaultRandom(),clinicId:uuid('clinic_id').notNull(),eventKey:text('event_key').notNull(),providerMessageId:text('provider_message_id').notNull(),recipient:text('recipient').notNull(),status:text('status').notNull(),providerTimestamp:time('provider_timestamp').notNull(),processed:boolean('processed').notNull().default(false),receivedAt:time('received_at').defaultNow().notNull(),
},t=>[unique('messaging_webhook_event_unique').on(t.eventKey),index('messaging_webhook_pending_idx').on(t.clinicId,t.processed),check('messaging_webhook_status',sql`${t.status} in ('sent','delivered','read','failed','opt_out')`)]);
