import { sql } from 'drizzle-orm';
import { check,date,foreignKey,index,integer,jsonb,text,timestamp,unique,uuid } from 'drizzle-orm/pg-core';
import { branches,clinicApp,memberships } from './organization.ts';
import { patients } from './patients.ts';
const base=()=>({id:uuid('id').primaryKey().defaultRandom(),clinicId:uuid('clinic_id').notNull(),branchId:uuid('branch_id').notNull(),patientId:uuid('patient_id').notNull(),actorMembershipId:uuid('actor_membership_id').notNull(),operationId:uuid('operation_id').notNull(),payloadHash:text('payload_hash').notNull(),amountMinor:integer('amount_minor').notNull(),currency:text('currency').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull()});
export const charges=clinicApp.table('charges',{...base(),description:text('description').notNull()},t=>[
 unique('charges_operation_unique').on(t.clinicId,t.branchId,t.operationId),unique('charges_scope_unique').on(t.clinicId,t.branchId,t.patientId,t.id),
 foreignKey({name:'charges_patient_fk',columns:[t.clinicId,t.patientId],foreignColumns:[patients.clinicId,patients.id]}),foreignKey({name:'charges_branch_fk',columns:[t.clinicId,t.branchId],foreignColumns:[branches.clinicId,branches.id]}),foreignKey({name:'charges_actor_fk',columns:[t.clinicId,t.actorMembershipId],foreignColumns:[memberships.clinicId,memberships.id]}),check('charges_amount',sql`${t.amountMinor} between 1 and 99999999`),check('charges_currency',sql`${t.currency}='PKR'`),check('charges_description',sql`length(trim(${t.description})) between 2 and 240`),index('charges_account_idx').on(t.clinicId,t.branchId,t.patientId,t.createdAt)]);
export const payments=clinicApp.table('payments',{...base(),method:text('method').notNull(),paidOn:date('paid_on').notNull()},t=>[
 unique('payments_operation_unique').on(t.clinicId,t.branchId,t.operationId),unique('payments_scope_unique').on(t.clinicId,t.branchId,t.patientId,t.id),foreignKey({name:'payments_patient_fk',columns:[t.clinicId,t.patientId],foreignColumns:[patients.clinicId,patients.id]}),foreignKey({name:'payments_branch_fk',columns:[t.clinicId,t.branchId],foreignColumns:[branches.clinicId,branches.id]}),foreignKey({name:'payments_actor_fk',columns:[t.clinicId,t.actorMembershipId],foreignColumns:[memberships.clinicId,memberships.id]}),check('payments_amount',sql`${t.amountMinor} between 1 and 99999999`),check('payments_currency',sql`${t.currency}='PKR'`),check('payments_method',sql`${t.method} in ('Cash','Card','Bank transfer')`),index('payments_account_idx').on(t.clinicId,t.branchId,t.patientId),index('payments_day_idx').on(t.clinicId,t.branchId,t.paidOn)]);
export const paymentAllocations=clinicApp.table('payment_allocations',{
 id:uuid('id').primaryKey().defaultRandom(),clinicId:uuid('clinic_id').notNull(),branchId:uuid('branch_id').notNull(),patientId:uuid('patient_id').notNull(),paymentId:uuid('payment_id').notNull(),chargeId:uuid('charge_id').notNull(),amountMinor:integer('amount_minor').notNull(),
},t=>[unique('allocation_scope_unique').on(t.clinicId,t.branchId,t.patientId,t.paymentId,t.id),unique('payment_charge_unique').on(t.paymentId,t.chargeId),foreignKey({name:'allocation_payment_fk',columns:[t.clinicId,t.branchId,t.patientId,t.paymentId],foreignColumns:[payments.clinicId,payments.branchId,payments.patientId,payments.id]}),foreignKey({name:'allocation_charge_fk',columns:[t.clinicId,t.branchId,t.patientId,t.chargeId],foreignColumns:[charges.clinicId,charges.branchId,charges.patientId,charges.id]}),check('allocation_amount',sql`${t.amountMinor}>0`)]);
export type ReceiptSnapshot={clinicName:string;branchName:string;patientName:string;patientDisplayId:string;currency:string;method:string;paidOn:string;amountMinor:number;chargedMinor:string;paidMinor:string;balanceMinor:string;allocations:{chargeId:string;description:string;amountMinor:number}[]};
export const receipts=clinicApp.table('receipts',{
 id:uuid('id').primaryKey().defaultRandom(),clinicId:uuid('clinic_id').notNull(),branchId:uuid('branch_id').notNull(),patientId:uuid('patient_id').notNull(),paymentId:uuid('payment_id').notNull(),number:text('number').notNull(),snapshot:jsonb('snapshot').$type<ReceiptSnapshot>().notNull(),createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull(),
},t=>[unique('receipts_payment_unique').on(t.paymentId),unique('receipts_number_unique').on(t.clinicId,t.number),foreignKey({name:'receipt_payment_fk',columns:[t.clinicId,t.branchId,t.patientId,t.paymentId],foreignColumns:[payments.clinicId,payments.branchId,payments.patientId,payments.id]})]);
export const paymentRefunds=clinicApp.table('payment_refunds',{
 ...base(),paymentId:uuid('payment_id').notNull(),method:text('method').notNull(),paidOn:date('paid_on').notNull(),reason:text('reason').notNull(),snapshot:jsonb('snapshot').$type<ReceiptSnapshot>().notNull(),
},t=>[unique('refunds_operation_unique').on(t.clinicId,t.branchId,t.operationId),unique('refunds_scope_unique').on(t.clinicId,t.branchId,t.patientId,t.paymentId,t.id),foreignKey({name:'refund_payment_fk',columns:[t.clinicId,t.branchId,t.patientId,t.paymentId],foreignColumns:[payments.clinicId,payments.branchId,payments.patientId,payments.id]}),foreignKey({name:'refund_actor_fk',columns:[t.clinicId,t.actorMembershipId],foreignColumns:[memberships.clinicId,memberships.id]}),check('refund_amount',sql`${t.amountMinor} between 1 and 99999999`),check('refund_reason',sql`length(trim(${t.reason})) between 3 and 500`),check('refund_currency',sql`${t.currency}='PKR'`)]);
export const allocationReversals=clinicApp.table('allocation_reversals',{
 id:uuid('id').primaryKey().defaultRandom(),clinicId:uuid('clinic_id').notNull(),branchId:uuid('branch_id').notNull(),patientId:uuid('patient_id').notNull(),paymentId:uuid('payment_id').notNull(),allocationId:uuid('allocation_id').notNull(),refundId:uuid('refund_id').notNull(),amountMinor:integer('amount_minor').notNull(),
},t=>[foreignKey({name:'reversal_allocation_fk',columns:[t.clinicId,t.branchId,t.patientId,t.paymentId,t.allocationId],foreignColumns:[paymentAllocations.clinicId,paymentAllocations.branchId,paymentAllocations.patientId,paymentAllocations.paymentId,paymentAllocations.id]}),foreignKey({name:'reversal_refund_fk',columns:[t.clinicId,t.branchId,t.patientId,t.paymentId,t.refundId],foreignColumns:[paymentRefunds.clinicId,paymentRefunds.branchId,paymentRefunds.patientId,paymentRefunds.paymentId,paymentRefunds.id]}),unique('refund_allocation_unique').on(t.refundId,t.allocationId),check('reversal_positive',sql`${t.amountMinor}>0`)]);
