import { sql } from 'drizzle-orm';
import { check,date,foreignKey,index,integer,jsonb,text,timestamp,unique,uuid } from 'drizzle-orm/pg-core';
import { branches,clinicApp,memberships } from './organization.ts';
import { patients } from './patients.ts';
import { visits } from './visits.ts';
import { appointments } from './appointments.ts';
export const followUps=clinicApp.table('follow_ups',{
 id:uuid('id').primaryKey().defaultRandom(),clinicId:uuid('clinic_id').notNull(),branchId:uuid('branch_id').notNull(),patientId:uuid('patient_id').notNull(),visitId:uuid('visit_id'),type:text('type').notNull(),customType:text('custom_type').notNull(),dueOn:date('due_on').notNull(),assigneeId:uuid('assignee_id'),status:text('status').notNull().default('due'),appointmentId:uuid('appointment_id'),version:integer('version').notNull().default(1),actorMembershipId:uuid('actor_membership_id').notNull(),operationId:uuid('operation_id').notNull(),payloadHash:text('payload_hash').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull(),
},t=>[unique('follow_up_scope_unique').on(t.clinicId,t.branchId,t.id),unique('follow_up_operation_unique').on(t.clinicId,t.branchId,t.operationId),foreignKey({name:'follow_up_patient_fk',columns:[t.clinicId,t.patientId],foreignColumns:[patients.clinicId,patients.id]}),foreignKey({name:'follow_up_branch_fk',columns:[t.clinicId,t.branchId],foreignColumns:[branches.clinicId,branches.id]}),foreignKey({name:'follow_up_actor_fk',columns:[t.clinicId,t.actorMembershipId],foreignColumns:[memberships.clinicId,memberships.id]}),foreignKey({name:'follow_up_assignee_fk',columns:[t.clinicId,t.assigneeId],foreignColumns:[memberships.clinicId,memberships.id]}),foreignKey({name:'follow_up_visit_fk',columns:[t.clinicId,t.branchId,t.patientId,t.visitId],foreignColumns:[visits.clinicId,visits.branchId,visits.patientId,visits.id]}),foreignKey({name:'follow_up_appointment_fk',columns:[t.clinicId,t.branchId,t.patientId,t.appointmentId],foreignColumns:[appointments.clinicId,appointments.branchId,appointments.patientId,appointments.id]}),check('follow_up_status',sql`${t.status} in ('due','contacted','booked','completed','closed','unable_to_reach')`),check('follow_up_version',sql`${t.version}>0`),check('follow_up_booked_link',sql`${t.status}<>'booked' or ${t.appointmentId} is not null`),index('follow_up_due_idx').on(t.clinicId,t.branchId,t.status,t.dueOn)]);
export type FollowUpEventDetail={note:string;dueOn?:string;assigneeId?:string|null;fromStatus?:string;status?:string;appointmentId?:string|null;channel?:string;outcome?:string};
export const followUpEvents=clinicApp.table('follow_up_events',{
 id:uuid('id').primaryKey().defaultRandom(),clinicId:uuid('clinic_id').notNull(),branchId:uuid('branch_id').notNull(),followUpId:uuid('follow_up_id').notNull(),actorMembershipId:uuid('actor_membership_id').notNull(),kind:text('kind').notNull(),version:integer('version').notNull(),detail:jsonb('detail').$type<FollowUpEventDetail>().notNull(),operationId:uuid('operation_id').notNull(),payloadHash:text('payload_hash').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull(),
},t=>[unique('follow_up_event_version_unique').on(t.followUpId,t.version),unique('follow_up_event_operation_unique').on(t.clinicId,t.branchId,t.operationId),foreignKey({name:'follow_up_event_parent_fk',columns:[t.clinicId,t.branchId,t.followUpId],foreignColumns:[followUps.clinicId,followUps.branchId,followUps.id]}),foreignKey({name:'follow_up_event_actor_fk',columns:[t.clinicId,t.actorMembershipId],foreignColumns:[memberships.clinicId,memberships.id]}),check('follow_up_event_kind',sql`${t.kind} in ('created','edited','transition','contact','booked')`),check('follow_up_event_version',sql`${t.version}>0`)]);
