import { sql } from 'drizzle-orm';
import { check,foreignKey,index,integer,jsonb,text,timestamp,unique,uuid } from 'drizzle-orm/pg-core';
import type { HistoryBody,AlertBody } from '../../../lib/patient-clinical/contracts.ts';
import { clinicApp,branches,memberships } from './organization.ts';
import { patients } from './patients.ts';
const base=()=>({id:uuid('id').primaryKey().defaultRandom(),clinicId:uuid('clinic_id').notNull(),branchId:uuid('branch_id').notNull(),patientId:uuid('patient_id').notNull(),actorMembershipId:uuid('actor_membership_id').notNull(),operationId:uuid('operation_id').notNull(),payloadHash:text('payload_hash').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull()});
export const patientHistoryVersions=clinicApp.table('patient_history_versions',{...base(),version:integer('version').notNull(),reason:text('reason').notNull(),body:jsonb('body').$type<HistoryBody>().notNull()},t=>[unique('history_patient_version_unique').on(t.clinicId,t.branchId,t.patientId,t.version),unique('history_operation_unique').on(t.clinicId,t.branchId,t.operationId),foreignKey({name:'history_patient_fk',columns:[t.clinicId,t.patientId],foreignColumns:[patients.clinicId,patients.id]}),foreignKey({name:'history_branch_fk',columns:[t.clinicId,t.branchId],foreignColumns:[branches.clinicId,branches.id]}),foreignKey({name:'history_actor_fk',columns:[t.clinicId,t.actorMembershipId],foreignColumns:[memberships.clinicId,memberships.id]}),check('history_version_positive',sql`${t.version}>0`),check('history_reason',sql`length(trim(${t.reason})) between 3 and 500`)]);
export const patientAlerts=clinicApp.table('patient_alerts',{...base(),version:integer('version').notNull().default(1),body:jsonb('body').$type<AlertBody>().notNull()},t=>[unique('patient_alert_scope_unique').on(t.clinicId,t.branchId,t.patientId,t.id),unique('patient_alert_operation_unique').on(t.clinicId,t.branchId,t.operationId),foreignKey({name:'alert_patient_fk',columns:[t.clinicId,t.patientId],foreignColumns:[patients.clinicId,patients.id]}),foreignKey({name:'alert_branch_fk',columns:[t.clinicId,t.branchId],foreignColumns:[branches.clinicId,branches.id]}),foreignKey({name:'alert_actor_fk',columns:[t.clinicId,t.actorMembershipId],foreignColumns:[memberships.clinicId,memberships.id]}),check('patient_alert_version',sql`${t.version}>0`),index('patient_alert_patient_idx').on(t.clinicId,t.branchId,t.patientId)]);
export const patientAlertVersions=clinicApp.table('patient_alert_versions',{...base(),alertId:uuid('alert_id').notNull(),version:integer('version').notNull(),reason:text('reason').notNull(),body:jsonb('body').$type<AlertBody>().notNull()},t=>[unique('alert_version_unique').on(t.alertId,t.version),unique('alert_version_operation_unique').on(t.clinicId,t.branchId,t.operationId),foreignKey({name:'alert_version_parent_fk',columns:[t.clinicId,t.branchId,t.patientId,t.alertId],foreignColumns:[patientAlerts.clinicId,patientAlerts.branchId,patientAlerts.patientId,patientAlerts.id]}),foreignKey({name:'alert_version_actor_fk',columns:[t.clinicId,t.actorMembershipId],foreignColumns:[memberships.clinicId,memberships.id]}),check('alert_revision_positive',sql`${t.version}>0`),check('alert_reason',sql`length(trim(${t.reason})) between 3 and 500`)]);
