import { sql } from 'drizzle-orm';
import { check,date,foreignKey,index,integer,jsonb,text,timestamp,unique,uuid } from 'drizzle-orm/pg-core';
import type { PlanSnapshot } from '../../../lib/plans/contracts.ts';
import { branches,clinicApp,memberships } from './organization.ts';
import { charges } from './finance.ts';
import { patients } from './patients.ts';
export const treatmentPlans=clinicApp.table('treatment_plans',{
 id:uuid('id').primaryKey().defaultRandom(),clinicId:uuid('clinic_id').notNull(),branchId:uuid('branch_id').notNull(),patientId:uuid('patient_id').notNull(),authorMembershipId:uuid('author_membership_id').notNull(),operationId:uuid('operation_id').notNull(),payloadHash:text('payload_hash').notNull(),version:integer('version').notNull().default(1),status:text('status').notNull().default('draft'),createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull(),
},t=>[unique('plans_patient_scope_unique').on(t.clinicId,t.branchId,t.patientId,t.id),unique('plans_scope_unique').on(t.clinicId,t.branchId,t.id),unique('plans_operation_unique').on(t.clinicId,t.branchId,t.operationId),foreignKey({name:'plan_patient_fk',columns:[t.clinicId,t.patientId],foreignColumns:[patients.clinicId,patients.id]}),foreignKey({name:'plan_branch_fk',columns:[t.clinicId,t.branchId],foreignColumns:[branches.clinicId,branches.id]}),foreignKey({name:'plan_author_fk',columns:[t.clinicId,t.authorMembershipId],foreignColumns:[memberships.clinicId,memberships.id]}),check('plan_version',sql`${t.version}>0`),check('plan_status',sql`${t.status} in ('draft','accepted')`),index('plan_branch_idx').on(t.clinicId,t.branchId,t.createdAt)]);
export const planVersions=clinicApp.table('plan_versions',{
 id:uuid('id').primaryKey().defaultRandom(),clinicId:uuid('clinic_id').notNull(),branchId:uuid('branch_id').notNull(),planId:uuid('plan_id').notNull(),version:integer('version').notNull(),actorMembershipId:uuid('actor_membership_id').notNull(),snapshot:jsonb('snapshot').$type<PlanSnapshot>().notNull(),operationId:uuid('operation_id').notNull(),payloadHash:text('payload_hash').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull(),
},t=>[unique('plan_versions_scope_unique').on(t.clinicId,t.branchId,t.planId,t.version),unique('plan_versions_operation_unique').on(t.clinicId,t.branchId,t.operationId),foreignKey({name:'plan_version_plan_fk',columns:[t.clinicId,t.branchId,t.planId],foreignColumns:[treatmentPlans.clinicId,treatmentPlans.branchId,treatmentPlans.id]}),foreignKey({name:'plan_version_actor_fk',columns:[t.clinicId,t.actorMembershipId],foreignColumns:[memberships.clinicId,memberships.id]}),check('plan_revision_positive',sql`${t.version}>0`)]);
export const planAcceptances=clinicApp.table('plan_acceptances',{
 id:uuid('id').primaryKey().defaultRandom(),clinicId:uuid('clinic_id').notNull(),branchId:uuid('branch_id').notNull(),planId:uuid('plan_id').notNull(),version:integer('version').notNull(),actorMembershipId:uuid('actor_membership_id').notNull(),acceptedBy:text('accepted_by').notNull(),evidence:text('evidence').notNull(),operationId:uuid('operation_id').notNull(),payloadHash:text('payload_hash').notNull(),acceptedAt:timestamp('accepted_at',{withTimezone:true}).defaultNow().notNull(),
},t=>[unique('plan_acceptance_version_scope').on(t.clinicId,t.branchId,t.planId,t.version),unique('plan_acceptance_once').on(t.planId),unique('plan_acceptance_operation_unique').on(t.clinicId,t.branchId,t.operationId),foreignKey({name:'plan_acceptance_version_fk',columns:[t.clinicId,t.branchId,t.planId,t.version],foreignColumns:[planVersions.clinicId,planVersions.branchId,planVersions.planId,planVersions.version]}),foreignKey({name:'plan_acceptance_actor_fk',columns:[t.clinicId,t.actorMembershipId],foreignColumns:[memberships.clinicId,memberships.id]}),check('plan_acceptance_evidence',sql`length(trim(${t.evidence})) between 3 and 500`),check('plan_acceptance_name',sql`length(trim(${t.acceptedBy})) between 2 and 160`)]);

export const treatmentCompletions=clinicApp.table('treatment_completions',{
 id:uuid('id').primaryKey().defaultRandom(),clinicId:uuid('clinic_id').notNull(),branchId:uuid('branch_id').notNull(),patientId:uuid('patient_id').notNull(),planId:uuid('plan_id').notNull(),version:integer('version').notNull(),itemId:uuid('item_id').notNull(),quantity:integer('quantity').notNull(),performedOn:date('performed_on').notNull(),note:text('note').notNull(),actorMembershipId:uuid('actor_membership_id').notNull(),operationId:uuid('operation_id').notNull(),payloadHash:text('payload_hash').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull(),
},t=>[unique('completion_scope_unique').on(t.clinicId,t.branchId,t.patientId,t.id),unique('completion_operation_unique').on(t.clinicId,t.branchId,t.operationId),foreignKey({name:'completion_patient_plan_fk',columns:[t.clinicId,t.branchId,t.patientId,t.planId],foreignColumns:[treatmentPlans.clinicId,treatmentPlans.branchId,treatmentPlans.patientId,treatmentPlans.id]}),foreignKey({name:'completion_accepted_fk',columns:[t.clinicId,t.branchId,t.planId,t.version],foreignColumns:[planAcceptances.clinicId,planAcceptances.branchId,planAcceptances.planId,planAcceptances.version]}),foreignKey({name:'completion_actor_fk',columns:[t.clinicId,t.actorMembershipId],foreignColumns:[memberships.clinicId,memberships.id]}),check('completion_quantity',sql`${t.quantity} between 1 and 100`),check('completion_note',sql`length(trim(${t.note})) between 3 and 1000`)]);
export const treatmentChargeLinks=clinicApp.table('treatment_charge_links',{
 id:uuid('id').primaryKey().defaultRandom(),clinicId:uuid('clinic_id').notNull(),branchId:uuid('branch_id').notNull(),patientId:uuid('patient_id').notNull(),completionId:uuid('completion_id').notNull(),chargeId:uuid('charge_id').notNull(),actorMembershipId:uuid('actor_membership_id').notNull(),operationId:uuid('operation_id').notNull(),payloadHash:text('payload_hash').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull(),
},t=>[unique('completion_charge_once').on(t.completionId),unique('charge_completion_once').on(t.chargeId),unique('treatment_charge_operation_unique').on(t.clinicId,t.branchId,t.operationId),foreignKey({name:'treatment_charge_completion_fk',columns:[t.clinicId,t.branchId,t.patientId,t.completionId],foreignColumns:[treatmentCompletions.clinicId,treatmentCompletions.branchId,treatmentCompletions.patientId,treatmentCompletions.id]}),foreignKey({name:'treatment_charge_charge_fk',columns:[t.clinicId,t.branchId,t.patientId,t.chargeId],foreignColumns:[charges.clinicId,charges.branchId,charges.patientId,charges.id]}),foreignKey({name:'treatment_charge_actor_fk',columns:[t.clinicId,t.actorMembershipId],foreignColumns:[memberships.clinicId,memberships.id]})]);
