import { sql } from 'drizzle-orm';
import { boolean,check,foreignKey,integer,jsonb,text,timestamp,unique,uniqueIndex,uuid } from 'drizzle-orm/pg-core';
import type { ProcedureSnapshot } from '../../../lib/procedures/contracts.ts';
import { branches,clinicApp,clinics,memberships } from './organization.ts';
// Clinic-wide catalog; price is an optional default in integer paisa.
export const procedures=clinicApp.table('procedures',{
 id:uuid('id').primaryKey().defaultRandom(),clinicId:uuid('clinic_id').notNull().references(()=>clinics.id,{onDelete:'restrict'}),code:text('code').notNull().default(''),name:text('name').notNull(),category:text('category').notNull(),defaultMinutes:integer('default_minutes').notNull(),priceMinor:integer('price_minor'),active:boolean('active').notNull().default(true),version:integer('version').notNull().default(1),createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull(),updatedAt:timestamp('updated_at',{withTimezone:true}).defaultNow().notNull(),
},t=>[unique('procedure_scope_unique').on(t.clinicId,t.id),uniqueIndex('procedure_name_unique').on(t.clinicId,sql`lower(${t.name})`),uniqueIndex('procedure_code_unique').on(t.clinicId,sql`lower(${t.code})`).where(sql`${t.code}<>''`),check('procedure_name',sql`length(trim(${t.name})) between 2 and 120`),check('procedure_category',sql`${t.category} in ('Consultation','Diagnostic','Preventive','Restorative','Endodontic','Periodontal','Prosthodontic','Oral surgery','Orthodontic','Implant','Cosmetic','Pediatric','Other')`),check('procedure_minutes',sql`${t.defaultMinutes} between 5 and 480 and ${t.defaultMinutes}%5=0`),check('procedure_price',sql`${t.priceMinor} is null or ${t.priceMinor} between 1 and 99999999`),check('procedure_version',sql`${t.version}>0`)]);
// Immutable price/duration history and idempotency record. Branch records where the change was made.
export const procedureVersions=clinicApp.table('procedure_versions',{
 id:uuid('id').primaryKey().defaultRandom(),clinicId:uuid('clinic_id').notNull(),branchId:uuid('branch_id').notNull(),procedureId:uuid('procedure_id').notNull(),version:integer('version').notNull(),snapshot:jsonb('snapshot').$type<ProcedureSnapshot>().notNull(),actorMembershipId:uuid('actor_membership_id').notNull(),operationId:uuid('operation_id').notNull(),payloadHash:text('payload_hash').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull(),
},t=>[unique('procedure_version_unique').on(t.procedureId,t.version),unique('procedure_version_operation_unique').on(t.clinicId,t.operationId),foreignKey({name:'procedure_version_parent_fk',columns:[t.clinicId,t.procedureId],foreignColumns:[procedures.clinicId,procedures.id]}),foreignKey({name:'procedure_version_branch_fk',columns:[t.clinicId,t.branchId],foreignColumns:[branches.clinicId,branches.id]}),foreignKey({name:'procedure_version_actor_fk',columns:[t.clinicId,t.actorMembershipId],foreignColumns:[memberships.clinicId,memberships.id]}),check('procedure_version_positive',sql`${t.version}>0`)]);
