import { sql } from 'drizzle-orm';
import { boolean,check,date,foreignKey,index,integer,jsonb,primaryKey,text,timestamp,unique,uniqueIndex,uuid } from 'drizzle-orm/pg-core';
import type { WeeklyHours } from '../../../lib/scheduling/contracts.ts';
import { branches,clinicApp,memberships } from './organization.ts';
const createdAt=()=>timestamp('created_at',{withTimezone:true}).defaultNow().notNull();
// Branch-scoped bookable resources. A dentist may optionally map to a staff membership.
export const scheduleDentists=clinicApp.table('schedule_dentists',{
 id:uuid('id').primaryKey().defaultRandom(),clinicId:uuid('clinic_id').notNull(),branchId:uuid('branch_id').notNull(),membershipId:uuid('membership_id'),name:text('name').notNull(),color:text('color').notNull(),active:boolean('active').notNull().default(true),version:integer('version').notNull().default(1),createdAt:createdAt(),
},t=>[unique('schedule_dentist_scope_unique').on(t.clinicId,t.branchId,t.id),uniqueIndex('schedule_dentist_name_unique').on(t.clinicId,t.branchId,sql`lower(${t.name})`),unique('schedule_dentist_membership_unique').on(t.clinicId,t.branchId,t.membershipId),foreignKey({name:'schedule_dentist_branch_fk',columns:[t.clinicId,t.branchId],foreignColumns:[branches.clinicId,branches.id]}),foreignKey({name:'schedule_dentist_membership_fk',columns:[t.clinicId,t.membershipId],foreignColumns:[memberships.clinicId,memberships.id]}),check('schedule_dentist_name',sql`length(trim(${t.name})) between 2 and 80`),check('schedule_dentist_color',sql`${t.color} ~ '^#[0-9a-f]{6}$'`),check('schedule_dentist_version',sql`${t.version}>0`)]);
export const scheduleChairs=clinicApp.table('schedule_chairs',{
 id:uuid('id').primaryKey().defaultRandom(),clinicId:uuid('clinic_id').notNull(),branchId:uuid('branch_id').notNull(),name:text('name').notNull(),active:boolean('active').notNull().default(true),version:integer('version').notNull().default(1),createdAt:createdAt(),
},t=>[unique('schedule_chair_scope_unique').on(t.clinicId,t.branchId,t.id),uniqueIndex('schedule_chair_name_unique').on(t.clinicId,t.branchId,sql`lower(${t.name})`),foreignKey({name:'schedule_chair_branch_fk',columns:[t.clinicId,t.branchId],foreignColumns:[branches.clinicId,branches.id]}),check('schedule_chair_name',sql`length(trim(${t.name})) between 2 and 80`),check('schedule_chair_version',sql`${t.version}>0`)]);
// Absent row means opening hours are not configured and are not enforced.
export const branchScheduleSettings=clinicApp.table('branch_schedule_settings',{
 clinicId:uuid('clinic_id').notNull(),branchId:uuid('branch_id').notNull(),slotMinutes:integer('slot_minutes').notNull(),weeklyHours:jsonb('weekly_hours').$type<WeeklyHours>().notNull(),version:integer('version').notNull().default(1),updatedAt:timestamp('updated_at',{withTimezone:true}).defaultNow().notNull(),
},t=>[primaryKey({columns:[t.clinicId,t.branchId]}),foreignKey({name:'schedule_settings_branch_fk',columns:[t.clinicId,t.branchId],foreignColumns:[branches.clinicId,branches.id]}),check('schedule_settings_slot',sql`${t.slotMinutes} in (5,10,15,20,30,60)`),check('schedule_settings_version',sql`${t.version}>0`)]);
export const branchClosures=clinicApp.table('branch_closures',{
 id:uuid('id').primaryKey().defaultRandom(),clinicId:uuid('clinic_id').notNull(),branchId:uuid('branch_id').notNull(),closedOn:date('closed_on').notNull(),reason:text('reason').notNull(),active:boolean('active').notNull().default(true),version:integer('version').notNull().default(1),createdAt:createdAt(),
},t=>[unique('branch_closure_scope_unique').on(t.clinicId,t.branchId,t.id),uniqueIndex('branch_closure_active_date_unique').on(t.clinicId,t.branchId,t.closedOn).where(sql`${t.active}`),index('branch_closure_date_idx').on(t.clinicId,t.branchId,t.closedOn),foreignKey({name:'branch_closure_branch_fk',columns:[t.clinicId,t.branchId],foreignColumns:[branches.clinicId,branches.id]}),check('branch_closure_reason',sql`length(trim(${t.reason})) between 3 and 200`),check('branch_closure_version',sql`${t.version}>0`)]);
// Immutable snapshot of every configuration version, also the idempotency record for configuration commands.
export const scheduleConfigRevisions=clinicApp.table('schedule_config_revisions',{
 id:uuid('id').primaryKey().defaultRandom(),clinicId:uuid('clinic_id').notNull(),branchId:uuid('branch_id').notNull(),entityType:text('entity_type').notNull(),entityId:uuid('entity_id').notNull(),version:integer('version').notNull(),snapshot:jsonb('snapshot').notNull(),actorMembershipId:uuid('actor_membership_id').notNull(),operationId:uuid('operation_id').notNull(),payloadHash:text('payload_hash').notNull(),createdAt:createdAt(),
},t=>[unique('schedule_revision_version_unique').on(t.entityType,t.entityId,t.version),unique('schedule_revision_operation_unique').on(t.clinicId,t.branchId,t.operationId),foreignKey({name:'schedule_revision_branch_fk',columns:[t.clinicId,t.branchId],foreignColumns:[branches.clinicId,branches.id]}),foreignKey({name:'schedule_revision_actor_fk',columns:[t.clinicId,t.actorMembershipId],foreignColumns:[memberships.clinicId,memberships.id]}),check('schedule_revision_type',sql`${t.entityType} in ('dentist','chair','hours','closure')`),check('schedule_revision_version',sql`${t.version}>0`)]);
