import { sql } from 'drizzle-orm';
import { check,foreignKey,index,integer,jsonb,text,timestamp,unique,uuid } from 'drizzle-orm/pg-core';
import type { ClinicalBody } from '../../../lib/visits/contracts.ts';
import { branches,clinicApp,memberships } from './organization.ts';
import { appointments } from './appointments.ts';
import { patients } from './patients.ts';
export const visits=clinicApp.table('visits',{
 id:uuid('id').primaryKey().defaultRandom(),clinicId:uuid('clinic_id').notNull(),branchId:uuid('branch_id').notNull(),patientId:uuid('patient_id').notNull(),authorMembershipId:uuid('author_membership_id').notNull(),appointmentId:uuid('appointment_id'),operationId:uuid('operation_id').notNull(),payloadHash:text('payload_hash').notNull(),status:text('status').notNull().default('draft'),version:integer('version').notNull().default(1),body:jsonb('body').$type<ClinicalBody>().notNull(),createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull(),updatedAt:timestamp('updated_at',{withTimezone:true}).defaultNow().notNull(),
},t=>[foreignKey({name:'visit_appointment_scope_fk',columns:[t.clinicId,t.branchId,t.patientId,t.appointmentId],foreignColumns:[appointments.clinicId,appointments.branchId,appointments.patientId,appointments.id]}),unique('visits_operation_unique').on(t.clinicId,t.branchId,t.operationId),unique('visits_appointment_unique').on(t.clinicId,t.branchId,t.appointmentId),unique('visits_scope_unique').on(t.clinicId,t.branchId,t.patientId,t.id),foreignKey({name:'visit_patient_fk',columns:[t.clinicId,t.patientId],foreignColumns:[patients.clinicId,patients.id]}),foreignKey({name:'visit_branch_fk',columns:[t.clinicId,t.branchId],foreignColumns:[branches.clinicId,branches.id]}),foreignKey({name:'visit_author_fk',columns:[t.clinicId,t.authorMembershipId],foreignColumns:[memberships.clinicId,memberships.id]}),check('visit_status',sql`${t.status} in ('draft','finalized')`),check('visit_version',sql`${t.version}>0`),index('visits_patient_idx').on(t.clinicId,t.branchId,t.patientId,t.createdAt)]);
export const visitRevisions=clinicApp.table('visit_revisions',{
 id:uuid('id').primaryKey().defaultRandom(),clinicId:uuid('clinic_id').notNull(),branchId:uuid('branch_id').notNull(),patientId:uuid('patient_id').notNull(),visitId:uuid('visit_id').notNull(),authorMembershipId:uuid('author_membership_id').notNull(),revision:integer('revision').notNull(),kind:text('kind').notNull(),reason:text('reason').notNull(),body:jsonb('body').$type<ClinicalBody>().notNull(),operationId:uuid('operation_id').notNull(),payloadHash:text('payload_hash').notNull(),signedAt:timestamp('signed_at',{withTimezone:true}).defaultNow().notNull(),
},t=>[unique('visit_revision_unique').on(t.visitId,t.revision),unique('visit_revision_operation_unique').on(t.clinicId,t.branchId,t.operationId),foreignKey({name:'revision_visit_fk',columns:[t.clinicId,t.branchId,t.patientId,t.visitId],foreignColumns:[visits.clinicId,visits.branchId,visits.patientId,visits.id]}),foreignKey({name:'revision_author_fk',columns:[t.clinicId,t.authorMembershipId],foreignColumns:[memberships.clinicId,memberships.id]}),check('revision_number',sql`${t.revision}>0`),check('revision_kind',sql`${t.kind} in ('final','amendment')`),check('revision_reason',sql`${t.kind}='final' or length(trim(${t.reason}))>=3`)]);
