import { and,eq,sql,type SQL } from 'drizzle-orm';
import { z } from 'zod';
import { timelineQuery,timelineCursor,visibleCategories,type TimelineEvent,type TimelineResult } from '../../lib/timeline/contracts.ts';
import { authorize,resolveContext,type Database } from '../auth/context.ts';
import { patients } from '../db/schema/patients.ts';
import { clinics } from '../db/schema/organization.ts';
import { AppError } from '../http/errors.ts';
import type { PatientScope } from '../patients/service.ts';
function parse<T>(schema:z.ZodType<T>,raw:unknown):T{const r=schema.safeParse(raw);if(!r.success)throw new AppError(400,'INVALID_INPUT','Check the timeline filters or refresh the timeline.');return r.data;}
function decode(value:string|undefined){if(!value)return null;try{return parse(timelineCursor,JSON.parse(Buffer.from(value,'base64url').toString('utf8')));}catch{throw new AppError(400,'INVALID_CURSOR','Refresh the timeline to start a new page.');}}
export async function patientTimeline(db:Database,s:PatientScope,patientId:string,raw:unknown={}):Promise<TimelineResult>{
 parse(z.object({authUserId:z.uuid(),clinicId:z.uuid(),branchId:z.uuid()}),s);parse(z.uuid(),patientId);const q=parse(timelineQuery,raw);const cursor=decode(q.cursor);
 return db.transaction(async tx=>{
 const c=await resolveContext(tx,s.authUserId,s.clinicId,s.branchId);authorize(c,'patient.demographics.read');const [patient]=await tx.select({id:patients.id,name:patients.name,displayId:patients.displayId}).from(patients).where(and(eq(patients.clinicId,s.clinicId),eq(patients.id,patientId)));if(!patient)throw new AppError(404,'PATIENT_NOT_FOUND','Patient is not available in this clinic.');
 const categories=visibleCategories(c.permissions);if(q.category!=='all'&&!categories.includes(q.category))throw new AppError(403,'FORBIDDEN','Your account cannot view this timeline category.');const enabled=new Set(q.category==='all'?categories:[q.category]);const parts:SQL[]=[];
 // These source queries are fixed allowlisted SQL, selected only after authorization.
 if(enabled.has('demographics'))parts.push(sql`select 'patient:'||p.id as key,p.created_at as occurred_at,'demographics' as category,'Patient registered' as summary,null::text as amount_minor,null::text as event_date,null::timestamptz as scheduled_at,null::uuid as actor_id,'Clinic record' as actor_label,'/patients' as href from clinic_app.patients p where p.clinic_id=${s.clinicId} and p.id=${patientId}`);
 if(enabled.has('appointments'))parts.push(sql`select 'appointment:'||a.id as key,a.occurred_at,'appointments',case a.action when 'appointment.booked' then 'Appointment booked' when 'appointment.arrived' then 'Patient arrived' when 'appointment.cancelled' then 'Appointment cancelled' end,null::text,null::text,p.starts_at,a.actor_membership_id,null::text,'/appointments' from clinic_app.audit_events a join clinic_app.appointments p on p.id=a.entity_id and p.clinic_id=a.clinic_id and p.branch_id=a.branch_id where a.clinic_id=${s.clinicId} and a.branch_id=${s.branchId} and p.patient_id=${patientId} and a.entity_type='appointment' and a.action in ('appointment.booked','appointment.arrived','appointment.cancelled')`);
 if(enabled.has('clinical')){
 parts.push(sql`select 'visit:'||a.id,a.occurred_at,'clinical',case a.action when 'visit.started' then 'Clinical visit started' else 'Clinical draft saved' end,null::text,null::text,null::timestamptz,a.actor_membership_id,null::text,'/visits/'||v.id from clinic_app.audit_events a join clinic_app.visits v on v.id=a.entity_id and v.clinic_id=a.clinic_id and v.branch_id=a.branch_id where a.clinic_id=${s.clinicId} and a.branch_id=${s.branchId} and v.patient_id=${patientId} and a.entity_type='visit' and a.action in ('visit.started','visit.draft_saved')`);
 parts.push(sql`select 'revision:'||v.id,v.signed_at,'clinical',case v.kind when 'final' then 'Clinical note signed' else 'Clinical note amendment signed' end,null::text,null::text,null::timestamptz,v.author_membership_id,null::text,'/visits/'||v.visit_id from clinic_app.visit_revisions v where v.clinic_id=${s.clinicId} and v.branch_id=${s.branchId} and v.patient_id=${patientId}`);
 }
 if(enabled.has('plans')){
 parts.push(sql`select 'estimate:'||v.id,v.created_at,'plans','Estimate version '||v.version||' saved: '||(v.snapshot->>'title'),v.snapshot->>'totalMinor',null::text,null::timestamptz,v.actor_membership_id,null::text,'/plans?planId='||p.id from clinic_app.plan_versions v join clinic_app.treatment_plans p on p.id=v.plan_id and p.clinic_id=v.clinic_id and p.branch_id=v.branch_id where v.clinic_id=${s.clinicId} and v.branch_id=${s.branchId} and p.patient_id=${patientId}`);
 parts.push(sql`select 'acceptance:'||a.id,a.accepted_at,'plans','Estimate version '||a.version||' accepted',null::text,null::text,null::timestamptz,a.actor_membership_id,null::text,'/plans?planId='||p.id from clinic_app.plan_acceptances a join clinic_app.treatment_plans p on p.id=a.plan_id and p.clinic_id=a.clinic_id and p.branch_id=a.branch_id where a.clinic_id=${s.clinicId} and a.branch_id=${s.branchId} and p.patient_id=${patientId}`);
 parts.push(sql`select 'completion:'||t.id,t.created_at,'plans','Treatment completion recorded: '||t.quantity||' unit(s)',null::text,t.performed_on::text,null::timestamptz,t.actor_membership_id,null::text,'/plans?planId='||t.plan_id from clinic_app.treatment_completions t where t.clinic_id=${s.clinicId} and t.branch_id=${s.branchId} and t.patient_id=${patientId}`);
 }
 if(enabled.has('billing')){
 parts.push(sql`select 'charge:'||t.id,t.created_at,'billing','Charge posted',t.amount_minor::text,null::text,null::timestamptz,t.actor_membership_id,null::text,'/accounts/'||t.patient_id from clinic_app.charges t where t.clinic_id=${s.clinicId} and t.branch_id=${s.branchId} and t.patient_id=${patientId}`);
 parts.push(sql`select 'payment:'||t.id,t.created_at,'billing','Payment recorded ('||t.method||')',t.amount_minor::text,t.paid_on::text,null::timestamptz,t.actor_membership_id,null::text,'/receipts/'||r.id from clinic_app.payments t join clinic_app.receipts r on r.payment_id=t.id and r.clinic_id=t.clinic_id and r.branch_id=t.branch_id and r.patient_id=t.patient_id where t.clinic_id=${s.clinicId} and t.branch_id=${s.branchId} and t.patient_id=${patientId}`);
 parts.push(sql`select 'refund:'||t.id,t.created_at,'billing','Refund recorded ('||t.method||')',t.amount_minor::text,t.paid_on::text,null::timestamptz,t.actor_membership_id,null::text,'/refunds/'||t.id from clinic_app.payment_refunds t where t.clinic_id=${s.clinicId} and t.branch_id=${s.branchId} and t.patient_id=${patientId}`);
 }
 if(enabled.has('followups'))parts.push(sql`select 'followup:'||e.id,e.created_at,'followups',case e.kind when 'created' then 'Follow-up created' when 'edited' then 'Follow-up due date or assignment changed' when 'contact' then 'Contact recorded ('||(e.detail->>'channel')||': '||(e.detail->>'outcome')||')' when 'booked' then 'Follow-up appointment booked' else 'Follow-up status: '||(e.detail->>'status') end,null::text,e.detail->>'dueOn',null::timestamptz,e.actor_membership_id,null::text,'/follow-ups?followUpId='||f.id from clinic_app.follow_up_events e join clinic_app.follow_ups f on f.id=e.follow_up_id and f.clinic_id=e.clinic_id and f.branch_id=e.branch_id where e.clinic_id=${s.clinicId} and e.branch_id=${s.branchId} and f.patient_id=${patientId}`);
 if(enabled.has('communications')){
 parts.push(sql`select 'message:'||j.id,j.created_at,'communications','WhatsApp message queued',null::text,null::text,null::timestamptz,j.actor_membership_id,null::text,'/communications' from clinic_app.communication_jobs j where j.clinic_id=${s.clinicId} and j.branch_id=${s.branchId} and j.patient_id=${patientId}`);
 parts.push(sql`select 'delivery:'||e.id,e.occurred_at,'communications',case e.kind when 'claimed' then 'WhatsApp send attempt started' when 'submitted' then 'WhatsApp submitted to provider' when 'sent' then 'WhatsApp sent' when 'delivered' then 'WhatsApp delivered' when 'read' then 'WhatsApp read' when 'failed' then 'WhatsApp failed' when 'review' then 'WhatsApp needs review' when 'queued' then 'WhatsApp retry scheduled' when 'cancelled' then 'WhatsApp cancelled' else 'WhatsApp processing event' end,null::text,null::text,null::timestamptz,null::uuid,'Messaging worker / provider','/communications' from clinic_app.communication_events e join clinic_app.communication_jobs j on j.id=e.job_id and j.clinic_id=e.clinic_id and j.branch_id=e.branch_id where e.clinic_id=${s.clinicId} and e.branch_id=${s.branchId} and j.patient_id=${patientId}`);
 parts.push(sql`select 'message_cancel:'||a.id,a.occurred_at,'communications','WhatsApp cancelled by staff',null::text,null::text,null::timestamptz,a.actor_membership_id,null::text,'/communications' from clinic_app.audit_events a join clinic_app.communication_jobs j on j.id=a.entity_id and j.clinic_id=a.clinic_id and j.branch_id=a.branch_id where a.clinic_id=${s.clinicId} and a.branch_id=${s.branchId} and j.patient_id=${patientId} and a.entity_type='communication' and a.action='communication.cancelled'`);
 }
 const [clinic]=await tx.select({timezone:clinics.timezone}).from(clinics).where(eq(clinics.id,s.clinicId));
 const rows=await tx.execute<TimelineEvent>(sql`with events(key,occurred_at,category,summary,amount_minor,event_date,scheduled_at,actor_id,actor_label,href) as (${sql.join(parts,sql` union all `)}) select e.key,to_char(e.occurred_at at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"') as "occurredAt",e.category,e.summary,e.amount_minor as "amountMinor",e.event_date as "eventDate",case when e.scheduled_at is null then null else to_char(e.scheduled_at at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"') end as "scheduledAt",coalesce(u.display_name,e.actor_label,'Staff record') as "actorName",e.href from events e left join clinic_app.memberships m on m.id=e.actor_id and m.clinic_id=${s.clinicId} left join clinic_app.app_users u on u.id=m.user_id where ${q.from?sql`(e.occurred_at at time zone ${clinic.timezone})::date>=${q.from}::date`:sql`true`} and ${q.to?sql`(e.occurred_at at time zone ${clinic.timezone})::date<=${q.to}::date`:sql`true`} and ${cursor?sql`(e.occurred_at,e.key)<(${cursor.at}::timestamptz,${cursor.key}::text)`:sql`true`} order by e.occurred_at desc,e.key desc limit 51`);
 const events=Array.from(rows).slice(0,50);const last=events.at(-1);return {patient,categories,events,nextCursor:rows.length>50&&last?Buffer.from(JSON.stringify({at:last.occurredAt,key:last.key})).toString('base64url'):null};
 },{isolationLevel:'repeatable read'});
}
