import { createHash,randomUUID } from 'node:crypto';
import { and,desc,eq,sql } from 'drizzle-orm';
import { z } from 'zod';
import { blankDemographicBody,demographicInput } from '../../lib/patient-profile/contracts.ts';
import { businessDate } from '../../lib/finance/contracts.ts';
import { authorize,resolveContext,type Database } from '../auth/context.ts';
import { patients } from '../db/schema/patients.ts';
import { clinics,memberships,appUsers } from '../db/schema/organization.ts';
import { patientProfiles,patientProfileVersions } from '../db/schema/patient-profile.ts';
import { auditEvents } from '../db/schema/security.ts';
import { AppError } from '../http/errors.ts';
import type { PatientScope } from '../patients/service.ts';
function parse<T>(schema:z.ZodType<T>,raw:unknown):T{const r=schema.safeParse(raw);if(!r.success)throw new AppError(400,'INVALID_INPUT','Check the date of birth/reported age, contact fields and reason.');return r.data;}
async function context(db:Database,s:PatientScope,id:string,write=false){parse(z.object({authUserId:z.uuid(),clinicId:z.uuid(),branchId:z.uuid()}),s);parse(z.uuid(),id);const c=await resolveContext(db,s.authUserId,s.clinicId,s.branchId);authorize(c,'patient.demographics.read');if(write)authorize(c,'patient.demographics.write');const [patient]=await db.select({id:patients.id,name:patients.name,displayId:patients.displayId,phone:patients.phone,email:patients.email}).from(patients).where(and(eq(patients.clinicId,s.clinicId),eq(patients.id,id)));if(!patient)throw new AppError(404,'PATIENT_NOT_FOUND','Patient is not available in this clinic.');return {c,patient};}
const scoped=(s:PatientScope,id:string)=>and(eq(patientProfiles.clinicId,s.clinicId),eq(patientProfiles.patientId,id));
export async function readPatientProfile(db:Database,s:PatientScope,id:string){return db.transaction(async tx=>{const {c,patient}=await context(tx,s,id);const [profile]=await tx.select().from(patientProfiles).where(scoped(s,id));const revisions=await tx.select({version:patientProfileVersions.version,body:patientProfileVersions.body,reason:patientProfileVersions.reason,createdAt:patientProfileVersions.createdAt,actorName:appUsers.displayName}).from(patientProfileVersions).innerJoin(memberships,and(eq(memberships.clinicId,patientProfileVersions.clinicId),eq(memberships.id,patientProfileVersions.actorMembershipId))).innerJoin(appUsers,eq(appUsers.id,memberships.userId)).where(and(eq(patientProfileVersions.clinicId,s.clinicId),eq(patientProfileVersions.patientId,id))).orderBy(desc(patientProfileVersions.version)).limit(20);return {patient,profile:{version:profile?.version??0,body:profile?.body??blankDemographicBody},revisions,canWrite:c.permissions.has('patient.demographics.write'),canArchive:c.permissions.has('patient.archive')};},{isolationLevel:'repeatable read'});}
export async function savePatientProfile(db:Database,s:PatientScope,id:string,raw:unknown){const input=parse(demographicInput,raw);const digest=createHash('sha256').update(JSON.stringify({id,...input})).digest('hex');return db.transaction(async tx=>{const {c}=await context(tx,s,id,true);await tx.execute(sql`select pg_advisory_xact_lock(hashtextextended(${s.clinicId+':patient-profile-operation:'+input.operationId},0))`);await tx.execute(sql`select pg_advisory_xact_lock(hashtextextended(${s.clinicId+':patient-profile:'+id},0))`);const [prior]=await tx.select().from(patientProfileVersions).where(and(eq(patientProfileVersions.clinicId,s.clinicId),eq(patientProfileVersions.operationId,input.operationId)));if(prior){if(prior.payloadHash!==digest)throw new AppError(409,'OPERATION_CONFLICT','This profile key has different details.');const [previous]=await tx.select({body:patientProfileVersions.body}).from(patientProfileVersions).where(and(eq(patientProfileVersions.clinicId,s.clinicId),eq(patientProfileVersions.patientId,id),eq(patientProfileVersions.version,prior.version-1)));const priorStatus=previous?.body.status??'active';if(prior.body.status!==priorStatus&&(prior.body.status==='archived'||priorStatus==='archived'))authorize(c,'patient.archive');return {version:prior.version};}const [old]=await tx.select().from(patientProfiles).where(scoped(s,id));if((old?.version??0)!==input.expectedVersion)throw new AppError(409,'PROFILE_CONFLICT','Patient profile changed. Reload before saving.');const oldStatus=old?.body.status??'active';if(input.body.status!==oldStatus&&(input.body.status==='archived'||oldStatus==='archived'))authorize(c,'patient.archive');const [clinic]=await tx.select({timezone:clinics.timezone}).from(clinics).where(eq(clinics.id,s.clinicId));const today=businessDate(clinic.timezone);if((input.body.dob&&input.body.dob>today)||(input.body.ageAsOf&&input.body.ageAsOf>today))throw new AppError(400,'DATE_FUTURE','DOB and reported-age dates cannot be in the future.');const version=input.expectedVersion+1;const [revision]=await tx.insert(patientProfileVersions).values({clinicId:s.clinicId,patientId:id,branchId:s.branchId,actorMembershipId:c.membershipId,version,body:input.body,reason:input.reason,operationId:input.operationId,payloadHash:digest}).returning({id:patientProfileVersions.id});if(old)await tx.update(patientProfiles).set({version,body:input.body}).where(scoped(s,id));else await tx.insert(patientProfiles).values({clinicId:s.clinicId,patientId:id,version,body:input.body});await tx.insert(auditEvents).values({clinicId:s.clinicId,branchId:s.branchId,actorMembershipId:c.membershipId,entityId:revision.id,entityType:'patient_profile',action:'patient.profile_reviewed',requestId:randomUUID()});return {version};});}
