import { createHash,randomUUID } from 'node:crypto';
import { and,desc,eq,sql } from 'drizzle-orm';
import { z } from 'zod';
import { historyInput,createAlertInput,updateAlertInput } from '../../lib/patient-clinical/contracts.ts';
import { businessDate } from '../../lib/finance/contracts.ts';
import { authorize,resolveContext,type Database } from '../auth/context.ts';
import { patients } from '../db/schema/patients.ts';
import { clinics,memberships,appUsers } from '../db/schema/organization.ts';
import { patientHistoryVersions,patientAlerts,patientAlertVersions } from '../db/schema/patient-clinical.ts';
import { auditEvents } from '../db/schema/security.ts';
import { AppError } from '../http/errors.ts';
import type { PatientScope } from '../patients/service.ts';
function parse<T>(schema:z.ZodType<T>,raw:unknown):T{const r=schema.safeParse(raw);if(!r.success)throw new AppError(400,'INVALID_INPUT','Check the history, alert, review date and reason.');return r.data;}
const hash=(raw:unknown)=>createHash('sha256').update(JSON.stringify(raw)).digest('hex');
async function context(db:Database,s:PatientScope,patientId:string,write=false){parse(z.object({authUserId:z.uuid(),clinicId:z.uuid(),branchId:z.uuid()}),s);parse(z.uuid(),patientId);const c=await resolveContext(db,s.authUserId,s.clinicId,s.branchId);authorize(c,'patient.demographics.read');authorize(c,'patient.clinical.read');if(write)authorize(c,'patient.clinical.write');const [patient]=await db.select({id:patients.id,name:patients.name,displayId:patients.displayId}).from(patients).where(and(eq(patients.clinicId,s.clinicId),eq(patients.id,patientId)));if(!patient)throw new AppError(404,'PATIENT_NOT_FOUND','Patient is not available in this clinic.');return {c,patient};}
const historyScope=(s:PatientScope,id:string)=>and(eq(patientHistoryVersions.clinicId,s.clinicId),eq(patientHistoryVersions.branchId,s.branchId),eq(patientHistoryVersions.patientId,id));
const alertScope=(s:PatientScope,id:string)=>and(eq(patientAlerts.clinicId,s.clinicId),eq(patientAlerts.branchId,s.branchId),eq(patientAlerts.patientId,id));
async function lock(db:Database,s:PatientScope,key:string){await db.execute(sql`select pg_advisory_xact_lock(hashtextextended(${s.clinicId+':'+s.branchId+':patient-clinical:'+key},0))`);}
async function audit(db:Database,s:PatientScope,actor:string,id:string,action:string){await db.insert(auditEvents).values({clinicId:s.clinicId,branchId:s.branchId,actorMembershipId:actor,entityId:id,entityType:'patient_clinical',action,requestId:randomUUID()});}
async function activeAlerts(db:Database,s:PatientScope,id:string){const [count]=await db.select({value:sql<number>`count(*)::integer`}).from(patientAlerts).where(and(alertScope(s,id),sql`${patientAlerts.body}->>'active'='true'`));const alerts=await db.select({id:patientAlerts.id,version:patientAlerts.version,body:patientAlerts.body}).from(patientAlerts).where(and(alertScope(s,id),sql`${patientAlerts.body}->>'active'='true'`)).orderBy(sql`case ${patientAlerts.body}->>'severity' when 'critical' then 0 when 'important' then 1 else 2 end`,desc(patientAlerts.createdAt),desc(patientAlerts.id)).limit(50);return {alerts,activeAlertCount:count.value};}
export async function readPatientClinical(db:Database,s:PatientScope,id:string){return db.transaction(async tx=>{const {c,patient}=await context(tx,s,id);const [history]=await tx.select({id:patientHistoryVersions.id,version:patientHistoryVersions.version,body:patientHistoryVersions.body,reason:patientHistoryVersions.reason,createdAt:patientHistoryVersions.createdAt,actorName:appUsers.displayName}).from(patientHistoryVersions).innerJoin(memberships,and(eq(memberships.id,patientHistoryVersions.actorMembershipId),eq(memberships.clinicId,patientHistoryVersions.clinicId))).innerJoin(appUsers,eq(appUsers.id,memberships.userId)).where(historyScope(s,id)).orderBy(desc(patientHistoryVersions.version)).limit(1);const revisions=await tx.select({version:patientHistoryVersions.version,createdAt:patientHistoryVersions.createdAt,actorName:appUsers.displayName,reason:patientHistoryVersions.reason}).from(patientHistoryVersions).innerJoin(memberships,and(eq(memberships.id,patientHistoryVersions.actorMembershipId),eq(memberships.clinicId,patientHistoryVersions.clinicId))).innerJoin(appUsers,eq(appUsers.id,memberships.userId)).where(historyScope(s,id)).orderBy(desc(patientHistoryVersions.version)).limit(50);return {patient,history:history??null,revisions,...await activeAlerts(tx,s,id),canWrite:c.permissions.has('patient.clinical.write')};},{isolationLevel:'repeatable read'});}
export async function readHistoryVersion(db:Database,s:PatientScope,id:string,raw:unknown){const version=parse(z.coerce.number().int().positive(),raw);await context(db,s,id);const [row]=await db.select().from(patientHistoryVersions).where(and(historyScope(s,id),eq(patientHistoryVersions.version,version)));if(!row)throw new AppError(404,'HISTORY_NOT_FOUND','History version is not available in this branch.');return {version:row.version,body:row.body,reason:row.reason,createdAt:row.createdAt};}
export async function savePatientHistory(db:Database,s:PatientScope,id:string,raw:unknown){const input=parse(historyInput,raw);const digest=hash({id,...input});return db.transaction(async tx=>{const {c}=await context(tx,s,id,true);await lock(tx,s,'history-operation:'+input.operationId);await lock(tx,s,'history:'+id);const [old]=await tx.select().from(patientHistoryVersions).where(and(eq(patientHistoryVersions.clinicId,s.clinicId),eq(patientHistoryVersions.branchId,s.branchId),eq(patientHistoryVersions.operationId,input.operationId)));if(old){if(old.payloadHash!==digest)throw new AppError(409,'OPERATION_CONFLICT','This history key has different details.');return {version:old.version};}const [latest]=await tx.select({version:patientHistoryVersions.version}).from(patientHistoryVersions).where(historyScope(s,id)).orderBy(desc(patientHistoryVersions.version)).limit(1);if((latest?.version??0)!==input.expectedVersion)throw new AppError(409,'HISTORY_CONFLICT','History changed. Reload before saving.');const [clinic]=await tx.select({timezone:clinics.timezone}).from(clinics).where(eq(clinics.id,s.clinicId));if(input.body.reviewedOn>businessDate(clinic.timezone))throw new AppError(400,'DATE_FUTURE','A history review cannot be dated in the future.');const [row]=await tx.insert(patientHistoryVersions).values({clinicId:s.clinicId,branchId:s.branchId,patientId:id,actorMembershipId:c.membershipId,operationId:input.operationId,payloadHash:digest,version:input.expectedVersion+1,reason:input.reason,body:input.body}).returning();await audit(tx,s,c.membershipId,row.id,'patient.history_reviewed');return {version:row.version};});}
export async function listPatientAlerts(db:Database,s:PatientScope,id:string,raw:unknown={}){const q=parse(z.object({active:z.enum(['true','false','all']).default('true'),offset:z.coerce.number().int().min(0).max(100000).default(0)}).strict(),raw);await context(db,s,id);const rows=await db.select({id:patientAlerts.id,version:patientAlerts.version,body:patientAlerts.body,createdAt:patientAlerts.createdAt}).from(patientAlerts).where(and(alertScope(s,id),q.active==='all'?undefined:sql`${patientAlerts.body}->>'active'=${q.active}`)).orderBy(sql`case ${patientAlerts.body}->>'severity' when 'critical' then 0 when 'important' then 1 else 2 end`,desc(patientAlerts.createdAt),desc(patientAlerts.id)).limit(51).offset(q.offset);return {alerts:rows.slice(0,50),hasMore:rows.length>50};}
export async function readPatientAlert(db:Database,s:PatientScope,id:string,alertId:string){parse(z.uuid(),alertId);return db.transaction(async tx=>{await context(tx,s,id);const [alert]=await tx.select().from(patientAlerts).where(and(alertScope(s,id),eq(patientAlerts.id,alertId)));if(!alert)throw new AppError(404,'ALERT_NOT_FOUND','Alert is not available for this patient in this branch.');const revisions=await tx.select({version:patientAlertVersions.version,body:patientAlertVersions.body,reason:patientAlertVersions.reason,createdAt:patientAlertVersions.createdAt,actorName:appUsers.displayName}).from(patientAlertVersions).innerJoin(memberships,and(eq(memberships.id,patientAlertVersions.actorMembershipId),eq(memberships.clinicId,patientAlertVersions.clinicId))).innerJoin(appUsers,eq(appUsers.id,memberships.userId)).where(and(eq(patientAlertVersions.clinicId,s.clinicId),eq(patientAlertVersions.branchId,s.branchId),eq(patientAlertVersions.patientId,id),eq(patientAlertVersions.alertId,alertId))).orderBy(desc(patientAlertVersions.version)).limit(50);return {alert:{id:alert.id,version:alert.version,body:alert.body},revisions};},{isolationLevel:'repeatable read'});}
export async function createPatientAlert(db:Database,s:PatientScope,id:string,raw:unknown){const input=parse(createAlertInput,raw);const digest=hash({id,action:'create',...input});return db.transaction(async tx=>{const {c}=await context(tx,s,id,true);await lock(tx,s,'alert-operation:'+input.operationId);const [old]=await tx.select().from(patientAlertVersions).where(and(eq(patientAlertVersions.clinicId,s.clinicId),eq(patientAlertVersions.branchId,s.branchId),eq(patientAlertVersions.operationId,input.operationId)));if(old){if(old.payloadHash!==digest)throw new AppError(409,'OPERATION_CONFLICT','This alert key has different details.');return {id:old.alertId,version:old.version};}const [alert]=await tx.insert(patientAlerts).values({clinicId:s.clinicId,branchId:s.branchId,patientId:id,actorMembershipId:c.membershipId,operationId:input.operationId,payloadHash:digest,body:input.body}).returning();await tx.insert(patientAlertVersions).values({clinicId:s.clinicId,branchId:s.branchId,patientId:id,actorMembershipId:c.membershipId,operationId:input.operationId,payloadHash:digest,alertId:alert.id,version:1,body:input.body,reason:input.reason});await audit(tx,s,c.membershipId,alert.id,'patient.alert_created');return {id:alert.id,version:1};});}
export async function updatePatientAlert(db:Database,s:PatientScope,id:string,alertId:string,raw:unknown){parse(z.uuid(),alertId);const input=parse(updateAlertInput,raw);const digest=hash({id,alertId,...input});return db.transaction(async tx=>{const {c}=await context(tx,s,id,true);await lock(tx,s,'alert-operation:'+input.operationId);const [old]=await tx.select().from(patientAlertVersions).where(and(eq(patientAlertVersions.clinicId,s.clinicId),eq(patientAlertVersions.branchId,s.branchId),eq(patientAlertVersions.operationId,input.operationId)));if(old){if(old.payloadHash!==digest)throw new AppError(409,'OPERATION_CONFLICT','This alert key has different details.');return {id:old.alertId,version:old.version};}const [alert]=await tx.select().from(patientAlerts).where(and(alertScope(s,id),eq(patientAlerts.id,alertId))).for('update');if(!alert)throw new AppError(404,'ALERT_NOT_FOUND','Alert is not available for this patient in this branch.');if(alert.version!==input.expectedVersion)throw new AppError(409,'ALERT_CONFLICT','Alert changed. Reload before saving.');const version=alert.version+1;await tx.insert(patientAlertVersions).values({clinicId:s.clinicId,branchId:s.branchId,patientId:id,actorMembershipId:c.membershipId,operationId:input.operationId,payloadHash:digest,alertId,version,body:input.body,reason:input.reason});await tx.update(patientAlerts).set({body:input.body,version}).where(eq(patientAlerts.id,alertId));await audit(tx,s,c.membershipId,alertId,input.body.active?'patient.alert_updated':'patient.alert_resolved');return {id:alertId,version};});}
