import './load-env.ts';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import postgres from 'postgres';
import { drizzle } from 'drizzle-orm/postgres-js';
import { sql } from 'drizzle-orm';
import { migrationEnvironment,requireLocalDatabase,connectionOptions } from '../src/lib/config/environment.ts';
import { businessDate } from '../src/lib/finance/contracts.ts';
import { clinics,branches,appUsers,memberships,membershipBranches } from '../src/server/db/schema/organization.ts';
import { membershipGrants } from '../src/server/db/schema/security.ts';
import { patients } from '../src/server/db/schema/patients.ts';
import { readPatientProfile,savePatientProfile } from '../src/server/patient-profile/service.ts';
import { blankDemographicBody } from '../src/lib/patient-profile/contracts.ts';
import { listPatients } from '../src/server/patients/service.ts';
import { patientTimeline } from '../src/server/timeline/service.ts';
import { AppError } from '../src/server/http/errors.ts';
const {MIGRATION_DATABASE_URL:url}=migrationEnvironment(process.env);requireLocalDatabase(url);const client=postgres(url,{...connectionOptions(url),max:1});const rollback=new Error('ROLLBACK_FIXTURES');const status=(n:number)=>(e:unknown)=>e instanceof AppError&&e.status===n;
try{try{await drizzle(client).transaction(async tx=>{
 await tx.execute(sql`select pg_advisory_xact_lock(73492009)`);
 const [clinic]=await tx.insert(clinics).values({name:'Synthetic follow-ups',currency:'PKR',timezone:'Asia/Karachi'}).returning();const [branch]=await tx.insert(branches).values({clinicId:clinic.id,name:'Follow-up branch'}).returning();const [second]=await tx.insert(branches).values({clinicId:clinic.id,name:'Second branch'}).returning();
 const authUserId=randomUUID();const [user]=await tx.insert(appUsers).values({authUserId,displayName:'Synthetic clinician'}).returning();const [member]=await tx.insert(memberships).values({clinicId:clinic.id,userId:user.id}).returning();await tx.insert(membershipBranches).values([branch,second].map(b=>({clinicId:clinic.id,membershipId:member.id,branchId:b.id})));await tx.insert(membershipGrants).values(['patient.demographics.read','patient.demographics.write'].map(permission=>({clinicId:clinic.id,membershipId:member.id,permission})));
 const [unavailableUser]=await tx.insert(appUsers).values({authUserId:randomUUID(),displayName:'No follow-up access'}).returning();const [unavailable]=await tx.insert(memberships).values({clinicId:clinic.id,userId:unavailableUser.id}).returning();await tx.insert(membershipBranches).values({clinicId:clinic.id,branchId:branch.id,membershipId:unavailable.id});
 const [otherClinic]=await tx.insert(clinics).values({name:'Other clinic',currency:'PKR',timezone:'Asia/Karachi'}).returning();
 const patientValues={creationHash:'synthetic',name:'Synthetic patient',phone:'+92 300 0000000',phoneNormalized:'923000000000'};
 const [patient]=await tx.insert(patients).values({...patientValues,creationKey:randomUUID(),clinicId:clinic.id,displayId:'SYNTHETIC'}).returning();const [different]=await tx.insert(patients).values({...patientValues,creationKey:randomUUID(),clinicId:clinic.id,displayId:'DIFFERENT'}).returning();const [otherPatient]=await tx.insert(patients).values({...patientValues,creationKey:randomUUID(),clinicId:otherClinic.id,displayId:'OTHER'}).returning();


 const scope={authUserId,clinicId:clinic.id,branchId:branch.id};const secondScope={...scope,branchId:second.id};const today=businessDate(clinic.timezone);await tx.execute(sql`set local role clinic_runtime`);
 assert.equal((await readPatientProfile(tx,scope,patient.id)).profile.body.dob,null);assert.equal((await readPatientProfile(tx,scope,different.id)).profile.version,0);const input={operationId:randomUUID(),expectedVersion:0,reason:'Synthetic demographic review',body:{...blankDemographicBody,reportedAge:30,ageAsOf:today,alternatePhone:'+92 333 1112233',emergencyName:'Synthetic contact',emergencyPhone:'+92 300 9990000'}};await savePatientProfile(tx,scope,patient.id,input);assert.equal((await savePatientProfile(tx,scope,patient.id,input)).version,1);assert.equal((await readPatientProfile(tx,secondScope,patient.id)).profile.body.reportedAge,30);assert.equal((await readPatientProfile(tx,scope,patient.id)).profile.body.dob,null);await assert.rejects(savePatientProfile(tx,scope,patient.id,{...input,reason:'Changed payload'}),status(409));await assert.rejects(savePatientProfile(tx,scope,patient.id,{...input,operationId:randomUUID()}),status(409));await assert.rejects(readPatientProfile(tx,scope,otherPatient.id),status(404));assert.equal((await listPatients(tx,scope,{search:'923331112233'})).length,1);assert.equal((await listPatients(tx,scope,{search:'923000000000'})).some(p=>p.id===patient.id),true);
 const archived={...input,operationId:randomUUID(),expectedVersion:1,body:{...input.body,status:'archived'}};await assert.rejects(savePatientProfile(tx,scope,patient.id,archived),status(403));await tx.execute(sql`reset role`);await tx.insert(membershipGrants).values({clinicId:clinic.id,membershipId:member.id,permission:'patient.archive'});await tx.execute(sql`set local role clinic_runtime`);await savePatientProfile(tx,scope,patient.id,archived);assert.equal((await listPatients(tx,scope)).find(p=>p.id===patient.id)?.status,'archived');assert.equal((await readPatientProfile(tx,scope,patient.id)).revisions[1].body.status,'active');assert.equal((await patientTimeline(tx,scope,patient.id)).events.some(event=>event.summary==='Patient demographics/status reviewed'),true);
 await tx.execute(sql`reset role`);await tx.execute(sql`revoke insert on clinic_app.audit_events from clinic_runtime`);await tx.execute(sql`set local role clinic_runtime`);const restore={...input,operationId:randomUUID(),expectedVersion:2};await assert.rejects(savePatientProfile(tx,scope,patient.id,restore));assert.equal((await readPatientProfile(tx,scope,patient.id)).profile.version,2);await tx.execute(sql`reset role`);await tx.execute(sql`grant insert on clinic_app.audit_events to clinic_runtime`);await tx.execute(sql`set local role clinic_runtime`);await savePatientProfile(tx,scope,patient.id,restore);assert.equal((await readPatientProfile(tx,scope,patient.id)).profile.body.status,'active');await assert.rejects(savePatientProfile(tx,scope,patient.id,{...input,operationId:randomUUID(),expectedVersion:3,body:{...blankDemographicBody,dob:'2999-01-01'}}),status(400));
 await tx.execute(sql`reset role`);for(const query of [sql`update clinic_app.patient_profile_versions set body='{}'::jsonb where patient_id=${patient.id}`,sql`update clinic_app.patient_profiles set body='{}'::jsonb,version=4 where patient_id=${patient.id}`,sql`truncate clinic_app.patient_profiles`])await assert.rejects(tx.transaction(async nested=>{await nested.execute(query);}));await tx.execute(sql`delete from clinic_app.membership_grants where membership_id=${member.id} and permission='patient.archive'`);await tx.execute(sql`set local role clinic_runtime`);await assert.rejects(savePatientProfile(tx,scope,patient.id,archived),status(403));await assert.rejects(savePatientProfile(tx,scope,patient.id,restore),status(403));await tx.execute(sql`reset role`);await tx.execute(sql`delete from clinic_app.membership_grants where membership_id=${member.id} and permission='patient.demographics.write'`);await tx.execute(sql`set local role clinic_runtime`);await assert.rejects(savePatientProfile(tx,scope,patient.id,input),status(403));throw rollback;
 });}catch(e){if(e!==rollback)throw e;}console.log('Patient profile integration passed: unknown DOB/reported-age retention, immutable demographic history, archive/restore permission, normalized/alternate phone search, clinic scope, retry/conflict protection and audit rollback. Fixtures rolled back.');}catch(e){console.error('Patient profile integration failed.',e instanceof assert.AssertionError?e.message:e instanceof AppError?e.code:'Database operation failed.');process.exitCode=1;}finally{await client.end();}
