import './load-env.ts';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import postgres from 'postgres';
import { drizzle } from 'drizzle-orm/postgres-js';
import { sql } from 'drizzle-orm';
import { migrationEnvironment, requireLocalDatabase, connectionOptions } from '../src/lib/config/environment.ts';
import { createPatient, listPatients, updatePatient } from '../src/server/patients/service.ts';
import { bookAppointment, listAppointments, changeAppointmentStatus } from '../src/server/appointments/service.ts';
import { recordExpense, listExpenses } from '../src/server/expenses/service.ts';
import { clinicOverview } from '../src/server/overview/query.ts';
import { listAuditEvents } from '../src/server/audit/query.ts';
import { AppError } from '../src/server/http/errors.ts';
import { clinics, branches, appUsers, memberships, membershipBranches } from '../src/server/db/schema/organization.ts';
import { membershipGrants, auditEvents } from '../src/server/db/schema/security.ts';

const { MIGRATION_DATABASE_URL: url } = migrationEnvironment(process.env);
requireLocalDatabase(url);
const client = postgres(url, { ...connectionOptions(url), max: 1 });
const rollback = new Error('ROLLBACK_FIXTURES');
const status = (expected: number) => (error: unknown) => error instanceof AppError && error.status === expected;
try {
  try {
    await drizzle(client).transaction(async tx => {
 await tx.execute(sql`select pg_advisory_xact_lock(73492009)`);
      const [clinic] = await tx.insert(clinics).values({ name: 'Synthetic service checks', currency: 'PKR', timezone: 'Asia/Karachi' }).returning();
      const [branch] = await tx.insert(branches).values({ clinicId: clinic.id, name: 'Test branch' }).returning();
      const [otherClinic] = await tx.insert(clinics).values({ name: 'Other synthetic clinic', currency: 'PKR', timezone: 'Asia/Karachi' }).returning();
      const [otherBranch] = await tx.insert(branches).values({ clinicId: otherClinic.id, name: 'Other test branch' }).returning();
      const authUserId = randomUUID();
      const [user] = await tx.insert(appUsers).values({ authUserId, displayName: 'Synthetic user' }).returning();
      const [member] = await tx.insert(memberships).values({ clinicId: clinic.id, userId: user.id }).returning();
      await tx.insert(membershipBranches).values({ clinicId: clinic.id, membershipId: member.id, branchId: branch.id });
      await tx.insert(membershipGrants).values(['patient.demographics.read', 'patient.demographics.write'].map(permission => ({ clinicId: clinic.id, membershipId: member.id, permission })));
      const [otherMember] = await tx.insert(memberships).values({ clinicId: otherClinic.id, userId: user.id }).returning();
      await tx.insert(membershipBranches).values({ clinicId: otherClinic.id, membershipId: otherMember.id, branchId: otherBranch.id });
      await tx.insert(membershipGrants).values(['patient.demographics.read', 'patient.demographics.write'].map(permission => ({ clinicId: otherClinic.id, membershipId: otherMember.id, permission })));
      await tx.execute(sql`set local role clinic_runtime`);
      const scope = { authUserId, clinicId: clinic.id, branchId: branch.id };
      const day = {startsAt:'2026-10-03T00:00:00+05:00',endsAt:'2026-10-04T00:00:00+05:00'};
      const demographics = { name: 'Synthetic Patient', phone: '+92 300 0000000', email: '' };
      const input = { ...demographics, operationId: randomUUID() };
      const patient = await createPatient(tx, scope, input);
      assert.equal((await createPatient(tx, scope, input)).id, patient.id);
      await assert.rejects(createPatient(tx, scope, { ...input, name: 'Changed replay' }), status(409));
      assert.equal(patient.version, 1);
      assert.deepEqual(await clinicOverview(tx,scope,day),{patients:1,appointments:null});
      assert.equal((await listPatients(tx, scope)).length, 1);
      assert.equal((await listPatients(tx, scope, { search: '%' })).length, 0);
      const updated = await updatePatient(tx, scope, patient.id, 1, { ...demographics, name: 'Updated synthetic patient' });
      assert.equal(updated.version, 2);
      assert.equal((await createPatient(tx, scope, input)).version, 2);
      const otherScope = { authUserId, clinicId: otherClinic.id, branchId: otherBranch.id };
      assert.equal((await listPatients(tx, otherScope)).length, 0);
      await assert.rejects(updatePatient(tx, otherScope, patient.id, 2, demographics), status(409));
      await assert.rejects(updatePatient(tx, scope, patient.id, 1, demographics), status(409));
      await assert.rejects(listPatients(tx, { ...scope, clinicId: randomUUID() }), status(403));
      await assert.rejects(listPatients(tx, { ...scope, branchId: randomUUID() }), status(403));
      await assert.rejects(listPatients(tx, { ...scope, authUserId: randomUUID() }), status(403));
      await assert.rejects(createPatient(tx, scope, { ...input, name: '' }), status(400));
      await tx.execute(sql`reset role`);
      await tx.execute(sql`revoke insert on clinic_app.audit_events from clinic_runtime`);
      await tx.execute(sql`set local role clinic_runtime`);
      await assert.rejects(createPatient(tx, scope, { ...input, name:'Another synthetic person',phone:'+92 300 5550000',operationId: randomUUID() }));
      assert.equal((await listPatients(tx, scope)).length, 1);
      await tx.execute(sql`reset role`);
      await tx.execute(sql`grant insert on clinic_app.audit_events to clinic_runtime`);
      await tx.execute(sql`set local role clinic_runtime`);
      await assert.rejects(listAuditEvents(tx, scope), status(403));
      await tx.execute(sql`reset role`);
      await tx.insert(membershipGrants).values({ clinicId: clinic.id, membershipId: member.id, permission: 'audit.read' });
      await tx.execute(sql`set local role clinic_runtime`);
      assert.equal((await listAuditEvents(tx, scope)).length, 2);
      const events = await tx.select().from(auditEvents);
      assert.equal(events.filter(e => e.clinicId === clinic.id).length, 2);
      await assert.rejects(tx.transaction(async nested => { await nested.execute(sql`delete from clinic_app.audit_events`); }));
      await tx.execute(sql`reset role`);
      await assert.rejects(tx.transaction(async nested => { await nested.execute(sql`update clinic_app.audit_events set action = 'tampered' where clinic_id = ${clinic.id}`); }));
      await assert.rejects(tx.transaction(async nested => { await nested.execute(sql`truncate clinic_app.audit_events`); }));
      await tx.execute(sql`delete from clinic_app.membership_grants where membership_id = ${member.id} and permission = 'patient.demographics.write'`);
      await tx.execute(sql`set local role clinic_runtime`);
      await assert.rejects(createPatient(tx, scope, input), status(403));
      assert.equal((await listPatients(tx, scope)).length, 1);
      await tx.execute(sql`reset role`);
      await tx.insert(membershipGrants).values(['appointment.read','appointment.write'].map(permission => ({clinicId:clinic.id,membershipId:member.id,permission})));
      await tx.execute(sql`set local role clinic_runtime`);
      const booking = {patientId:patient.id,operationId:randomUUID(),startsAt:'2026-10-03T09:00:00+05:00',endsAt:'2026-10-03T09:30:00+05:00'};
      const appointment = await bookAppointment(tx,scope,booking);
      assert.equal((await bookAppointment(tx,scope,booking)).id,appointment.id);
      await assert.rejects(bookAppointment(tx,scope,{...booking,endsAt:'2026-10-03T10:00:00+05:00'}),status(409));
      await assert.rejects(bookAppointment(tx,scope,{...booking,operationId:randomUUID()}),status(409));
      await assert.rejects(bookAppointment(tx,scope,{...booking,patientId:randomUUID(),operationId:randomUUID()}),status(404));
      await assert.rejects(bookAppointment(tx,scope,{...booking,endsAt:booking.startsAt,operationId:randomUUID()}),status(400));
      assert.equal((await listAppointments(tx,scope,{startsAt:'2026-10-03T00:00:00+05:00',endsAt:'2026-10-04T00:00:00+05:00'})).length,1);
      await assert.rejects(listAppointments(tx,otherScope,{startsAt:booking.startsAt,endsAt:booking.endsAt}),status(403));
      await tx.execute(sql`reset role`);
      await tx.insert(membershipGrants).values(['appointment.read','appointment.write'].map(permission => ({clinicId:otherClinic.id,membershipId:otherMember.id,permission})));
      await tx.execute(sql`set local role clinic_runtime`);
      assert.equal((await listAppointments(tx,otherScope,{startsAt:booking.startsAt,endsAt:booking.endsAt})).length,0);
      await assert.rejects(bookAppointment(tx,otherScope,{...booking,operationId:randomUUID()}),status(404));
      await assert.rejects(changeAppointmentStatus(tx,otherScope,appointment.id,{expectedVersion:1,status:'cancelled'}),status(409));
      const adjacent = await bookAppointment(tx,scope,{...booking,operationId:randomUUID(),startsAt:booking.endsAt,endsAt:'2026-10-03T10:00:00+05:00'});
      await changeAppointmentStatus(tx,scope,appointment.id,{expectedVersion:1,status:'cancelled'});
      await assert.rejects(changeAppointmentStatus(tx,scope,appointment.id,{expectedVersion:1,status:'arrived'}),status(409));
      await bookAppointment(tx,scope,{...booking,operationId:randomUUID()});
      await changeAppointmentStatus(tx,scope,adjacent.id,{expectedVersion:1,status:'arrived'});
      await assert.rejects(changeAppointmentStatus(tx,scope,adjacent.id,{expectedVersion:2,status:'cancelled'}),status(409));
      const appointmentEvents = (await listAuditEvents(tx,scope)).filter(e=>e.entityType==='appointment');
      assert.equal(appointmentEvents.length,5);
      assert.deepEqual(await clinicOverview(tx,scope,day),{patients:1,appointments:{booked:1,arrived:1,cancelled:1}});
      assert.deepEqual(await clinicOverview(tx,otherScope,day),{patients:0,appointments:{booked:0,arrived:0,cancelled:0}});
      await assert.rejects(clinicOverview(tx,scope,{...day,endsAt:day.startsAt}),status(400));
      await tx.execute(sql`reset role`);
      await tx.execute(sql`delete from clinic_app.membership_grants where membership_id=${member.id} and permission='appointment.write'`);
      await tx.execute(sql`set local role clinic_runtime`);
      await assert.rejects(bookAppointment(tx,scope,{...booking,operationId:randomUUID()}),status(403));
      await tx.execute(sql`reset role`);
      await tx.insert(membershipGrants).values(['expense.read','expense.write'].map(permission=>({clinicId:clinic.id,membershipId:member.id,permission})));
      await tx.execute(sql`set local role clinic_runtime`);
      const expenseInput={operationId:randomUUID(),paidOn:'2026-01-01',description:'Synthetic supplies',category:'Supplies',method:'Cash',amount:'12.30'};
      const expense=await recordExpense(tx,scope,expenseInput);
      assert.equal(expense.amountMinor,1230);
      assert.equal((await recordExpense(tx,scope,expenseInput)).id,expense.id);
      await assert.rejects(recordExpense(tx,scope,{...expenseInput,amount:'13.00'}),status(409));
      const ledger=await listExpenses(tx,scope,{paidOn:expenseInput.paidOn});
      assert.equal(ledger.count,1);assert.equal(ledger.totalMinor,'1230');assert.equal(ledger.cashMinor,'1230');
      assert.equal((await listAuditEvents(tx,scope)).filter(e=>e.entityType==='expense').length,1);
      assert.equal((await listExpenses(tx,scope,{paidOn:'2026-01-02'})).count,0);
      await assert.rejects(listExpenses(tx,otherScope,{paidOn:expenseInput.paidOn}),status(403));
      await tx.execute(sql`reset role`);
      const [secondBranch]=await tx.insert(branches).values({clinicId:clinic.id,name:'Second synthetic branch'}).returning();
      await tx.insert(membershipBranches).values({clinicId:clinic.id,membershipId:member.id,branchId:secondBranch.id});
      await tx.insert(membershipGrants).values({clinicId:otherClinic.id,membershipId:otherMember.id,permission:'expense.read'});
      await tx.execute(sql`set local role clinic_runtime`);
      assert.equal((await listExpenses(tx,{...scope,branchId:secondBranch.id},{paidOn:expenseInput.paidOn})).count,0);
      assert.equal((await listExpenses(tx,otherScope,{paidOn:expenseInput.paidOn})).count,0);
      await tx.execute(sql`reset role`);
      await tx.execute(sql`revoke insert on clinic_app.audit_events from clinic_runtime`);
      await tx.execute(sql`set local role clinic_runtime`);
      await assert.rejects(recordExpense(tx,scope,{...expenseInput,operationId:randomUUID()}));
      assert.equal((await listExpenses(tx,scope,{paidOn:expenseInput.paidOn})).count,1);
      await assert.rejects(tx.transaction(async nested=>{await nested.execute(sql`delete from clinic_app.expenses where id=${expense.id}`);}));
      await tx.execute(sql`reset role`);
      await tx.execute(sql`grant insert on clinic_app.audit_events to clinic_runtime`);
      await assert.rejects(tx.transaction(async nested=>{await nested.execute(sql`update clinic_app.expenses set amount_minor=1 where id=${expense.id}`);}));
      await assert.rejects(tx.transaction(async nested=>{await nested.execute(sql`truncate clinic_app.expenses`);}));
      await tx.execute(sql`delete from clinic_app.membership_grants where membership_id=${member.id} and permission='expense.write'`);
      await tx.execute(sql`set local role clinic_runtime`);
      await assert.rejects(recordExpense(tx,scope,expenseInput),status(403));
      await tx.execute(sql`reset role`);
      await tx.execute(sql`update clinic_app.memberships set active = false where id = ${member.id}`);
      await tx.execute(sql`set local role clinic_runtime`);
      await assert.rejects(listPatients(tx, scope), status(403));
      await assert.rejects(clinicOverview(tx,scope,day),status(403));
      throw rollback;
    });
  } catch (error) { if (error !== rollback) throw error; }
  console.log('Patient integration checks passed: create, search, version conflicts, scope isolation, revoked permissions, disabled membership atomic audit, appointment overlap/replay/status/permission rules; expense exact amounts, replay, branch isolation, atomic audit and immutability. Fixtures rolled back.');
} catch (error) {
  console.error('Patient integration checks failed.', error instanceof AppError ? error.code : error instanceof assert.AssertionError ? error.message : 'Database operation failed.');
  process.exitCode = 1;
} finally { await client.end(); }
