import './load-env.ts';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import postgres from 'postgres';
import { drizzle } from 'drizzle-orm/postgres-js';
import { eq,sql } from 'drizzle-orm';
import { migrationEnvironment,requireLocalDatabase,connectionOptions } from '../src/lib/config/environment.ts';
import { clinics,branches,appUsers,memberships,membershipBranches } from '../src/server/db/schema/organization.ts';
import { membershipGrants } from '../src/server/db/schema/security.ts';
import { patients } from '../src/server/db/schema/patients.ts';
import { visitRevisions } from '../src/server/db/schema/visits.ts';
import { createVisit,readVisit,listVisits,saveVisitDraft,signVisit } from '../src/server/visits/service.ts';
import { emptyClinicalBody } from '../src/lib/visits/contracts.ts';
import { AppError } from '../src/server/http/errors.ts';
const {MIGRATION_DATABASE_URL:url}=migrationEnvironment(process.env);requireLocalDatabase(url);const client=postgres(url,{...connectionOptions(url),max:1});const rollback=new Error('ROLLBACK_FIXTURES');const status=(n:number)=>(e:unknown)=>e instanceof AppError&&e.status===n;
try{try{await drizzle(client).transaction(async tx=>{
 await tx.execute(sql`select pg_advisory_xact_lock(73492009)`);
 const [clinic]=await tx.insert(clinics).values({name:'Synthetic clinical checks',currency:'PKR',timezone:'Asia/Karachi'}).returning();const [branch]=await tx.insert(branches).values({clinicId:clinic.id,name:'Synthetic branch'}).returning();const [secondBranch]=await tx.insert(branches).values({clinicId:clinic.id,name:'Second branch'}).returning();const authUserId=randomUUID();const [user]=await tx.insert(appUsers).values({authUserId,displayName:'Synthetic clinician'}).returning();const [member]=await tx.insert(memberships).values({clinicId:clinic.id,userId:user.id}).returning();await tx.insert(membershipBranches).values([branch,secondBranch].map(b=>({clinicId:clinic.id,membershipId:member.id,branchId:b.id})));await tx.insert(membershipGrants).values(['patient.demographics.read','patient.clinical.read','visit.draft.write','visit.finalize'].map(permission=>({clinicId:clinic.id,membershipId:member.id,permission})));
 const [patient]=await tx.insert(patients).values({clinicId:clinic.id,creationKey:randomUUID(),creationHash:'synthetic',displayId:'SYNTHETIC',name:'Synthetic patient',phone:'+92 300 0000000',phoneNormalized:'923000000000'}).returning();const scope={authUserId,clinicId:clinic.id,branchId:branch.id};
 const otherAuth=randomUUID();const [otherUser]=await tx.insert(appUsers).values({authUserId:otherAuth,displayName:'Other synthetic clinician'}).returning();const [otherMember]=await tx.insert(memberships).values({clinicId:clinic.id,userId:otherUser.id}).returning();await tx.insert(membershipBranches).values({clinicId:clinic.id,membershipId:otherMember.id,branchId:branch.id});await tx.insert(membershipGrants).values(['patient.demographics.read','patient.clinical.read','visit.draft.write','visit.finalize'].map(permission=>({clinicId:clinic.id,membershipId:otherMember.id,permission})));const otherScope={...scope,authUserId:otherAuth};
 await tx.execute(sql`set local role clinic_runtime`);const input={patientId:patient.id,operationId:randomUUID()};const visit=await createVisit(tx,scope,input);assert.equal((await createVisit(tx,scope,input)).id,visit.id);assert.equal((await listVisits(tx,scope,{})).length,1);assert.equal((await listVisits(tx,{...scope,branchId:secondBranch.id},{})).length,0);await assert.rejects(readVisit(tx,{...scope,branchId:secondBranch.id},visit.id),status(404));await assert.rejects(readVisit(tx,{...scope,clinicId:randomUUID()},visit.id),status(403));
 await assert.rejects(signVisit(tx,scope,visit.id,{expectedVersion:1,operationId:randomUUID()}),status(400));const body={...emptyClinicalBody,complaint:'Synthetic complaint',assessment:'Synthetic assessment only',treatment:'Synthetic treatment entry'};const saved=await saveVisitDraft(tx,scope,visit.id,{expectedVersion:1,body});assert.equal(saved.version,2);await assert.rejects(saveVisitDraft(tx,scope,visit.id,{expectedVersion:1,body}),status(409));await assert.rejects(saveVisitDraft(tx,otherScope,visit.id,{expectedVersion:2,body}),status(409));await assert.rejects(signVisit(tx,otherScope,visit.id,{expectedVersion:2,operationId:randomUUID()}),status(403));
 await tx.execute(sql`reset role`);await tx.execute(sql`revoke insert on clinic_app.audit_events from clinic_runtime`);await tx.execute(sql`set local role clinic_runtime`);await assert.rejects(signVisit(tx,scope,visit.id,{expectedVersion:2,operationId:randomUUID()}));assert.equal((await readVisit(tx,scope,visit.id)).visit.status,'draft');assert.equal((await readVisit(tx,scope,visit.id)).revisions.length,0);await tx.execute(sql`reset role`);await tx.execute(sql`grant insert on clinic_app.audit_events to clinic_runtime`);await tx.execute(sql`set local role clinic_runtime`);
 const signing={expectedVersion:2,operationId:randomUUID()};const signed=await signVisit(tx,scope,visit.id,signing);assert.equal((await signVisit(tx,scope,visit.id,signing)).id,signed.id);await assert.rejects(saveVisitDraft(tx,scope,visit.id,{expectedVersion:3,body}),status(409));const amendment={expectedVersion:3,operationId:randomUUID(),reason:'Synthetic correction reason',body:{...body,advice:'Synthetic advice amended'}};const amended=await signVisit(tx,scope,visit.id,amendment,true);assert.equal(amended.revision,2);assert.equal((await signVisit(tx,scope,visit.id,amendment,true)).id,amended.id);const detail=await readVisit(tx,scope,visit.id);assert.equal(detail.revisions.length,2);assert.equal(detail.revisions[1].body.advice,'');assert.equal(detail.revisions[0].body.advice,'Synthetic advice amended');assert.equal(detail.visit.version,4);
 await tx.execute(sql`reset role`);await assert.rejects(tx.transaction(async nested=>{await nested.execute(sql`update clinic_app.visits set body='{}'::jsonb where id=${visit.id}`);}));await assert.rejects(tx.transaction(async nested=>{await nested.update(visitRevisions).set({reason:'tampered'}).where(eq(visitRevisions.id,signed.id));}));await assert.rejects(tx.transaction(async nested=>{await nested.execute(sql`truncate clinic_app.visit_revisions`);}));await tx.execute(sql`delete from clinic_app.membership_grants where membership_id=${member.id} and permission='patient.clinical.read'`);await tx.execute(sql`set local role clinic_runtime`);await assert.rejects(readVisit(tx,scope,visit.id),status(403));await assert.rejects(listVisits(tx,scope,{}),status(403));throw rollback;
});}catch(e){if(e!==rollback)throw e;}console.log('Clinical integration passed: draft/version/author rules, scope denial, immutable final revisions, append-only amendments, signing replay, audit rollback and revoked clinical access. Fixtures rolled back.');}catch(e){console.error('Clinical integration failed.',e instanceof assert.AssertionError?e.message:e instanceof AppError?e.code:'Database operation failed.');process.exitCode=1;}finally{await client.end();}
