import './load-env.ts';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import postgres from 'postgres';
import { drizzle } from 'drizzle-orm/postgres-js';
import { sql } from 'drizzle-orm';
import { migrationEnvironment,requireLocalDatabase,connectionOptions } from '../src/lib/config/environment.ts';
import { businessDate } from '../src/lib/finance/contracts.ts';
import { emptyClinicalBody } from '../src/lib/visits/contracts.ts';
import { clinics,branches,appUsers,memberships,membershipBranches } from '../src/server/db/schema/organization.ts';
import { membershipGrants } from '../src/server/db/schema/security.ts';
import { patients } from '../src/server/db/schema/patients.ts';
import { readPatientClinical,savePatientHistory,readHistoryVersion,createPatientAlert,updatePatientAlert,readPatientAlert,listPatientAlerts } from '../src/server/patient-clinical/service.ts';
import { listPatients } from '../src/server/patients/service.ts';
import { patientTimeline } from '../src/server/timeline/service.ts';
import { createVisit,saveVisitDraft,signVisit,readVisit } from '../src/server/visits/service.ts';
import { AppError } from '../src/server/http/errors.ts';
const {MIGRATION_DATABASE_URL:url}=migrationEnvironment(process.env);requireLocalDatabase(url);const client=postgres(url,{...connectionOptions(url),max:1});const rollback=new Error('ROLLBACK_FIXTURES');const status=(n:number)=>(e:unknown)=>e instanceof AppError&&e.status===n;
try{try{await drizzle(client).transaction(async tx=>{
 await tx.execute(sql`select pg_advisory_xact_lock(73492009)`);
 const [clinic]=await tx.insert(clinics).values({name:'Synthetic follow-ups',currency:'PKR',timezone:'Asia/Karachi'}).returning();const [branch]=await tx.insert(branches).values({clinicId:clinic.id,name:'Follow-up branch'}).returning();const [second]=await tx.insert(branches).values({clinicId:clinic.id,name:'Second branch'}).returning();
 const authUserId=randomUUID();const [user]=await tx.insert(appUsers).values({authUserId,displayName:'Synthetic clinician'}).returning();const [member]=await tx.insert(memberships).values({clinicId:clinic.id,userId:user.id}).returning();await tx.insert(membershipBranches).values([branch,second].map(b=>({clinicId:clinic.id,membershipId:member.id,branchId:b.id})));await tx.insert(membershipGrants).values(['patient.demographics.read','patient.clinical.read','patient.clinical.write','visit.draft.write','visit.finalize'].map(permission=>({clinicId:clinic.id,membershipId:member.id,permission})));
 const [unavailableUser]=await tx.insert(appUsers).values({authUserId:randomUUID(),displayName:'No follow-up access'}).returning();const [unavailable]=await tx.insert(memberships).values({clinicId:clinic.id,userId:unavailableUser.id}).returning();await tx.insert(membershipBranches).values({clinicId:clinic.id,branchId:branch.id,membershipId:unavailable.id});
 const [otherClinic]=await tx.insert(clinics).values({name:'Other clinic',currency:'PKR',timezone:'Asia/Karachi'}).returning();
 const patientValues={creationHash:'synthetic',name:'Synthetic patient',phone:'+92 300 0000000',phoneNormalized:'923000000000'};
 const [patient]=await tx.insert(patients).values({...patientValues,creationKey:randomUUID(),clinicId:clinic.id,displayId:'SYNTHETIC'}).returning();const [different]=await tx.insert(patients).values({...patientValues,creationKey:randomUUID(),clinicId:clinic.id,displayId:'DIFFERENT'}).returning();const [otherPatient]=await tx.insert(patients).values({...patientValues,creationKey:randomUUID(),clinicId:otherClinic.id,displayId:'OTHER'}).returning();

 const scope={authUserId,clinicId:clinic.id,branchId:branch.id};const secondScope={...scope,branchId:second.id};const today=businessDate(clinic.timezone);await tx.execute(sql`set local role clinic_runtime`);
 const history={operationId:randomUUID(),expectedVersion:0,reason:'Synthetic initial review',body:{medicalHistory:'SENSITIVE_HISTORY',dentalHistory:'Synthetic history',medications:'',allergies:'Reported alert',tobaccoHistory:'',source:'Synthetic fixture',reviewedOn:today}};
 assert.equal((await readPatientClinical(tx,scope,patient.id)).history,null);assert.equal((await savePatientHistory(tx,scope,patient.id,history)).version,1);assert.equal((await savePatientHistory(tx,scope,patient.id,history)).version,1);await assert.rejects(savePatientHistory(tx,scope,patient.id,{...history,reason:'Changed review'}),status(409));await assert.rejects(savePatientHistory(tx,scope,patient.id,{...history,operationId:randomUUID()}),status(409));await assert.rejects(savePatientHistory(tx,scope,otherPatient.id,{...history,operationId:randomUUID()}),status(404));
 const visit=await createVisit(tx,scope,{patientId:patient.id,operationId:randomUUID()});const note={...emptyClinicalBody,complaint:'Synthetic complaint',assessment:'Synthetic assessment',treatment:'Synthetic care'};await saveVisitDraft(tx,scope,visit.id,{expectedVersion:1,body:note});await signVisit(tx,scope,visit.id,{expectedVersion:2,operationId:randomUUID()});
 const alertInput={operationId:randomUUID(),reason:'Synthetic reported flag',body:{type:'other',severity:'critical',text:'SENSITIVE_ALERT',active:true}};const alert=await createPatientAlert(tx,scope,patient.id,alertInput);assert.equal((await createPatientAlert(tx,scope,patient.id,alertInput)).id,alert.id);assert.equal((await readPatientClinical(tx,scope,patient.id)).activeAlertCount,1);assert.equal((await readVisit(tx,scope,visit.id)).clinical.alerts[0].body.text,'SENSITIVE_ALERT');
 const update={operationId:randomUUID(),expectedVersion:1,reason:'Synthetic resolved flag',body:{...alertInput.body,active:false}};await updatePatientAlert(tx,scope,patient.id,alert.id,update);assert.equal((await updatePatientAlert(tx,scope,patient.id,alert.id,update)).version,2);assert.equal((await readPatientClinical(tx,scope,patient.id)).activeAlertCount,0);assert.equal((await listPatientAlerts(tx,scope,patient.id,{active:'false'})).alerts.length,1);assert.equal((await readPatientAlert(tx,scope,patient.id,alert.id)).revisions[1].body.text,'SENSITIVE_ALERT');await assert.rejects(updatePatientAlert(tx,scope,patient.id,alert.id,{...update,operationId:randomUUID()}),status(409));await assert.rejects(readPatientAlert(tx,scope,different.id,alert.id),status(404));await assert.rejects(readPatientAlert(tx,secondScope,patient.id,alert.id),status(404));assert.equal((await readPatientClinical(tx,secondScope,patient.id)).history,null);
 const revised={...history,operationId:randomUUID(),expectedVersion:1,reason:'Synthetic new review',body:{...history.body,medicalHistory:'SENSITIVE_UPDATED_HISTORY'}};await savePatientHistory(tx,scope,patient.id,revised);assert.equal((await readHistoryVersion(tx,scope,patient.id,1)).body.medicalHistory,'SENSITIVE_HISTORY');assert.equal((await readVisit(tx,scope,visit.id)).clinical.history?.body.medicalHistory,'SENSITIVE_UPDATED_HISTORY');assert.deepEqual((await readVisit(tx,scope,visit.id)).revisions[0].body,note);await assert.rejects(savePatientHistory(tx,scope,patient.id,{...revised,operationId:randomUUID(),expectedVersion:2,body:{...revised.body,reviewedOn:'2999-01-01'}}),status(400));
 await tx.execute(sql`reset role`);await tx.execute(sql`revoke insert on clinic_app.audit_events from clinic_runtime`);await tx.execute(sql`set local role clinic_runtime`);await assert.rejects(savePatientHistory(tx,scope,patient.id,{...revised,operationId:randomUUID(),expectedVersion:2}));await assert.rejects(updatePatientAlert(tx,scope,patient.id,alert.id,{...update,operationId:randomUUID(),expectedVersion:2,body:{...alertInput.body,active:true}}));assert.equal((await readPatientClinical(tx,scope,patient.id)).history?.version,2);assert.equal((await readPatientAlert(tx,scope,patient.id,alert.id)).alert.version,2);await tx.execute(sql`reset role`);await tx.execute(sql`grant insert on clinic_app.audit_events to clinic_runtime`);await tx.execute(sql`set local role clinic_runtime`);
 const timeline=await patientTimeline(tx,scope,patient.id);assert.equal(timeline.events.some(event=>event.summary==='Patient history reviewed'),true);assert.equal(timeline.events.some(event=>event.summary==='Patient alert resolved'),true);assert.equal(JSON.stringify(timeline).includes('SENSITIVE_'),false);assert.equal(JSON.stringify(await listPatients(tx,scope)).includes('SENSITIVE_'),false);
 await tx.execute(sql`reset role`);for(const query of [sql`update clinic_app.patient_history_versions set body='{}'::jsonb where patient_id=${patient.id}`,sql`update clinic_app.patient_alert_versions set reason='changed' where alert_id=${alert.id}`,sql`update clinic_app.patient_alerts set body='{}'::jsonb,version=3 where id=${alert.id}`,sql`truncate clinic_app.patient_alerts cascade`])await assert.rejects(tx.transaction(async nested=>{await nested.execute(query);}));await tx.execute(sql`delete from clinic_app.membership_grants where membership_id=${member.id} and permission='patient.clinical.write'`);await tx.execute(sql`set local role clinic_runtime`);await assert.rejects(savePatientHistory(tx,scope,patient.id,history),status(403));assert.equal((await readPatientClinical(tx,scope,patient.id)).canWrite,false);await tx.execute(sql`reset role`);await tx.execute(sql`delete from clinic_app.membership_grants where membership_id=${member.id} and permission='patient.clinical.read'`);await tx.execute(sql`set local role clinic_runtime`);await assert.rejects(readPatientClinical(tx,scope,patient.id),status(403));assert.deepEqual((await patientTimeline(tx,scope,patient.id)).categories,['demographics']);throw rollback;
 });}catch(e){if(e!==rollback)throw e;}console.log('Patient clinical integration passed: history/alert revisions, active/resolved records, signed note preservation, scope/permission isolation, retry/conflict protection and audit rollback. Fixtures rolled back.');}catch(e){console.error('Patient clinical integration failed.',e instanceof assert.AssertionError?e.message:e instanceof AppError?e.code:'Database operation failed.');process.exitCode=1;}finally{await client.end();}
