import './load-env.ts';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import postgres from 'postgres';
import { drizzle } from 'drizzle-orm/postgres-js';
import { sql } from 'drizzle-orm';
import { migrationEnvironment,requireLocalDatabase,connectionOptions } from '../src/lib/config/environment.ts';
import { clinics,branches,appUsers,memberships,membershipBranches } from '../src/server/db/schema/organization.ts';
import { membershipGrants } from '../src/server/db/schema/security.ts';
import { patients } from '../src/server/db/schema/patients.ts';
import { savePatientProfile } from '../src/server/patient-profile/service.ts';
import { blankDemographicBody } from '../src/lib/patient-profile/contracts.ts';
import { duplicateCandidates,createPatient,listPatients } from '../src/server/patients/service.ts';
import { AppError } from '../src/server/http/errors.ts';
const {MIGRATION_DATABASE_URL:url}=migrationEnvironment(process.env);requireLocalDatabase(url);const client=postgres(url,{...connectionOptions(url),max:1});const rollback=new Error('ROLLBACK_FIXTURES');const status=(n:number)=>(e:unknown)=>e instanceof AppError&&e.status===n;
try{try{await drizzle(client).transaction(async tx=>{
 await tx.execute(sql`select pg_advisory_xact_lock(73492009)`);
 const [clinic]=await tx.insert(clinics).values({name:'Synthetic follow-ups',currency:'PKR',timezone:'Asia/Karachi'}).returning();const [branch]=await tx.insert(branches).values({clinicId:clinic.id,name:'Follow-up branch'}).returning();const [second]=await tx.insert(branches).values({clinicId:clinic.id,name:'Second branch'}).returning();
 const authUserId=randomUUID();const [user]=await tx.insert(appUsers).values({authUserId,displayName:'Synthetic clinician'}).returning();const [member]=await tx.insert(memberships).values({clinicId:clinic.id,userId:user.id}).returning();await tx.insert(membershipBranches).values([branch,second].map(b=>({clinicId:clinic.id,membershipId:member.id,branchId:b.id})));await tx.insert(membershipGrants).values(['patient.demographics.read','patient.demographics.write'].map(permission=>({clinicId:clinic.id,membershipId:member.id,permission})));
 const [unavailableUser]=await tx.insert(appUsers).values({authUserId:randomUUID(),displayName:'No follow-up access'}).returning();const [unavailable]=await tx.insert(memberships).values({clinicId:clinic.id,userId:unavailableUser.id}).returning();await tx.insert(membershipBranches).values({clinicId:clinic.id,branchId:branch.id,membershipId:unavailable.id});
 const [otherClinic]=await tx.insert(clinics).values({name:'Other clinic',currency:'PKR',timezone:'Asia/Karachi'}).returning();
 const patientValues={creationHash:'synthetic',name:'Synthetic patient',phone:'+92 300 0000000',phoneNormalized:'923000000000'};
 const [patient]=await tx.insert(patients).values({...patientValues,creationKey:randomUUID(),clinicId:clinic.id,displayId:'SYNTHETIC'}).returning();const [different]=await tx.insert(patients).values({...patientValues,creationKey:randomUUID(),clinicId:clinic.id,displayId:'DIFFERENT'}).returning();const [otherPatient]=await tx.insert(patients).values({...patientValues,creationKey:randomUUID(),clinicId:otherClinic.id,displayId:'OTHER'}).returning();



 const scope={authUserId,clinicId:clinic.id,branchId:branch.id};await tx.execute(sql`set local role clinic_runtime`);
 const search={name:'Synthetic patient',phone:'+92 (300) 0000000'};const candidates=await duplicateCandidates(tx,scope,search);assert.equal(candidates.candidates.length,2);assert.equal(candidates.canOverride,false);assert.equal(candidates.candidates.some(c=>c.id===otherPatient.id),false);
 const input={name:'Family member',phone:'+92 (300) 0000000',email:'',operationId:randomUUID()};await assert.rejects(createPatient(tx,scope,input),status(409));const approved={...input,duplicateOverride:{reason:'Synthetic family shares this phone'}};await assert.rejects(createPatient(tx,scope,approved),status(403));await tx.execute(sql`reset role`);await tx.insert(membershipGrants).values({clinicId:clinic.id,membershipId:member.id,permission:'patient.duplicate.override'});await tx.execute(sql`set local role clinic_runtime`);
 const family=await createPatient(tx,scope,approved);assert.equal((await createPatient(tx,scope,approved)).id,family.id);assert.notEqual(family.id,patient.id);assert.equal((await listPatients(tx,scope,{search:'923000000000'})).length,3);await assert.rejects(createPatient(tx,scope,{...approved,duplicateOverride:{reason:'Changed review reason'}}),status(409));const reviews=await tx.execute<{candidate_patient_ids:string[];reason:string}>(sql`select candidate_patient_ids,reason from clinic_app.patient_duplicate_reviews where patient_id=${family.id}`);assert.equal(reviews.length,1);assert.equal(reviews[0].candidate_patient_ids.includes(patient.id),true);assert.equal(reviews[0].reason,approved.duplicateOverride.reason);
 await savePatientProfile(tx,scope,different.id,{operationId:randomUUID(),expectedVersion:0,reason:'Synthetic alternate contact',body:{...blankDemographicBody,alternatePhone:'+92 333 1112233'}});assert.equal((await duplicateCandidates(tx,scope,{name:'Unmatched name',phone:'923331112233'})).candidates[0].id,different.id);assert.equal((await duplicateCandidates(tx,scope,{name:' SYNTHETIC PATIENT ',phone:'+92 399 8880000'})).candidates.length,2);
 await tx.execute(sql`reset role`);await tx.execute(sql`revoke insert on clinic_app.audit_events from clinic_runtime`);await tx.execute(sql`set local role clinic_runtime`);await assert.rejects(createPatient(tx,scope,{...approved,operationId:randomUUID(),name:'Another family member'}));assert.equal((await listPatients(tx,scope)).length,3);const count=await tx.execute<{count:string}>(sql`select count(*)::text as count from clinic_app.patient_duplicate_reviews where clinic_id=${clinic.id}`);assert.equal(count[0].count,'1');await tx.execute(sql`reset role`);await tx.execute(sql`grant insert on clinic_app.audit_events to clinic_runtime`);
 for(const query of [sql`update clinic_app.patient_duplicate_reviews set reason='tampered' where patient_id=${family.id}`,sql`truncate clinic_app.patient_duplicate_reviews`])await assert.rejects(tx.transaction(async nested=>{await nested.execute(query);}));await tx.execute(sql`delete from clinic_app.membership_grants where membership_id=${member.id} and permission='patient.duplicate.override'`);await tx.execute(sql`set local role clinic_runtime`);await assert.rejects(createPatient(tx,scope,approved),status(403));assert.equal((await duplicateCandidates(tx,scope,search)).canOverride,false);await tx.execute(sql`reset role`);await tx.execute(sql`delete from clinic_app.membership_grants where membership_id=${member.id} and permission='patient.demographics.read'`);await tx.execute(sql`set local role clinic_runtime`);await assert.rejects(duplicateCandidates(tx,scope,search),status(403));throw rollback;
 });}catch(e){if(e!==rollback)throw e;}console.log('Duplicate review integration passed: normalized exact name/phone candidates, clinic isolation, explicit override, family shared-phone retention, stable retries, immutable evidence, fresh grants and audit rollback. Fixtures rolled back.');}catch(e){console.error('Duplicate review integration failed.',e instanceof assert.AssertionError?e.message:e instanceof AppError?e.code:'Database operation failed.');process.exitCode=1;}finally{await client.end();}
