'use client';
import Link from 'next/link';
import { useEffect,useRef,useState,type FormEvent } from 'react';
import { businessDate,moneyMinor,paymentMethods } from '@/lib/finance/contracts';
import { api,scopeHeaders,useClinic } from './session';
type Patient={id:string;name:string;displayId:string};
type Refund={id:string;amountMinor:number;method:string;paidOn:string;reason:string};
type Account={refunds:Refund[];patient:Patient;chargedMinor:string;paidMinor:string;balanceMinor:string;charges:{id:string;description:string;amountMinor:number;createdAt:string}[];payments:{id:string;amountMinor:number;method:string;paidOn:string;receiptId:string;receiptNumber:string}[]};
export function BillingDirectory(){
 const {scope,can}=useClinic();const [search,setSearch]=useState('');const [patients,setPatients]=useState<Patient[]|null>(null);const [error,setError]=useState('');const allowed=can('billing.read')&&can('patient.demographics.read');
 useEffect(()=>{if(!allowed)return;const controller=new AbortController();api(`/api/v1/patients?search=${encodeURIComponent(search)}`,{headers:scopeHeaders(scope),signal:controller.signal}).then(data=>{if(!controller.signal.aborted)setPatients(data.patients);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[scope,search,allowed]);
 if(!allowed)return <section className="staff-workspace live-inner"><h1>Billing</h1><p>Your account needs billing read and patient demographic access.</p></section>;
 return <div className="staff-workspace live-inner"><h1>Patient billing</h1><p>Open a saved patient account to post reviewed charges, record received payments and view receipts.</p><section><label>Find patient<input value={search} onChange={e=>{setSearch(e.target.value);setPatients(null);setError('');}} placeholder="Search name, ID or phone"/></label>{error&&<p role="alert" className="staff-error">{error}</p>}{patients?<ul>{patients.map(p=><li key={p.id}><div><strong>{p.name}</strong><p>{p.displayId}</p></div><Link href={`/accounts/${p.id}`}>Open account</Link></li>)}</ul>:!error&&<p role="status">Loading patients…</p>}{patients?.length===0&&<p>No matching patients.</p>}<p>Showing up to 50 matches. Use search to find the account.</p></section></div>;
}
export function PatientAccount({patientId}:{patientId:string}){
 const {scope,can}=useClinic();const [account,setAccount]=useState<Account|null>(null);const [error,setError]=useState('');const [revision,setRevision]=useState(0);const allowed=can('billing.read')&&can('patient.demographics.read');
 useEffect(()=>{if(!allowed)return;const controller=new AbortController();api(`/api/v1/patients/${patientId}/account`,{headers:scopeHeaders(scope),signal:controller.signal}).then(data=>{if(!controller.signal.aborted)setAccount(data);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[scope,patientId,revision,allowed]);
 const refresh=()=>{setAccount(null);setError('');setRevision(n=>n+1);};
 if(!allowed)return <section className="staff-workspace live-inner"><h1>Patient account</h1><p>Your account needs billing read and patient demographic access.</p></section>;
 return <div className="staff-workspace live-inner"><Link href="/billing">Back to billing</Link>{error&&<p role="alert" className="staff-error">{error}</p>}{account?<><div className="staff-toolbar"><div><h1>{account.patient.name}</h1><p>{account.patient.displayId} · {scope.branchName}</p></div><button onClick={refresh}>Refresh account</button></div><section><p>Charges {moneyMinor(account.chargedMinor)} · Payments {moneyMinor(account.paidMinor)} · Outstanding {moneyMinor(account.balanceMinor)}</p></section><div className="staff-grid finance-forms">{can('charge.post')&&scope.currency==='PKR'&&<section><h2>Post reviewed charge</h2><p>Enter the agreed service description and price. Posted entries remain on the ledger.</p><FinanceForm kind="charge" patientId={patientId} onSaved={refresh}/></section>}{can('payment.post')&&scope.currency==='PKR'&&<section><h2>Record received payment</h2><p>Record money already received. Overpayments and deposits are not enabled.</p><FinanceForm kind="payment" patientId={patientId} onSaved={refresh}/></section>}</div>{can('refund.post')&&account.payments.length>0&&<section><h2>Record returned payment</h2><RefundForm payments={account.payments} onSaved={refresh}/></section>}<section><h2>Latest charges</h2><div className="table-scroll"><table><thead><tr><th>Description</th><th>Amount</th><th>Posted</th></tr></thead><tbody>{account.charges.map(c=><tr key={c.id}><td>{c.description}</td><td>{moneyMinor(c.amountMinor)}</td><td>{new Date(c.createdAt).toLocaleString()}</td></tr>)}</tbody></table></div>{!account.charges.length&&<p>No posted charges.</p>}</section><section><h2>Latest payments and receipts</h2><div className="table-scroll"><table><thead><tr><th>Paid on</th><th>Method</th><th>Amount</th><th>Receipt</th></tr></thead><tbody>{account.payments.map(p=><tr key={p.id}><td>{p.paidOn}</td><td>{p.method}</td><td>{moneyMinor(p.amountMinor)}</td><td><Link href={`/receipts/${p.receiptId}`}>{p.receiptNumber}</Link></td></tr>)}</tbody></table></div>{!account.payments.length&&<p>No recorded payments.</p>}<h2>Refunds</h2><ul>{account.refunds.map(r=><li key={r.id}><div><strong>{moneyMinor(r.amountMinor)} · {r.method}</strong><p>{r.paidOn} · {r.reason}</p></div><Link href={`/refunds/${r.id}`}>Refund confirmation</Link></li>)}</ul><p>Each list shows the latest 100 records; account totals include every posted entry. Charge credits, deposits and treatment-item links remain pending.</p></section></>:!error&&<p role="status">Loading account…</p>}</div>;
}
function FinanceForm({kind,patientId,onSaved}:{kind:'charge'|'payment';patientId:string;onSaved:()=>void}){
 const {scope}=useClinic();const [busy,setBusy]=useState(false);const [error,setError]=useState('');const operation=useRef<{id:string;payload:string}|null>(null);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const values={...Object.fromEntries(new FormData(e.currentTarget)),patientId};const payload=JSON.stringify(values);if(operation.current&&operation.current.payload!==payload){setError('Resolve the previous request with the same details before posting a different entry.');return;}operation.current??={id:crypto.randomUUID(),payload};setBusy(true);setError('');try{await api(kind==='charge'?'/api/v1/charges':'/api/v1/payments',{method:'POST',headers:scopeHeaders(scope),body:JSON.stringify({...values,operationId:operation.current.id})});operation.current=null;onSaved();}catch(e){if(e instanceof Error&&'status' in e&&Number(e.status)>=400&&Number(e.status)<500&&(!('code' in e)||e.code!=='OPERATION_CONFLICT'))operation.current=null;setError(e instanceof Error?e.message:'Financial entry could not be saved.');}finally{setBusy(false);}}
 return <form onSubmit={submit}>{error&&<p role="alert" className="staff-error">{error}</p>}{kind==='charge'?<label>Service description<input name="description" required minLength={2} maxLength={240} disabled={busy}/></label>:<><label>Payment date<input name="paidOn" type="date" defaultValue={businessDate(scope.timezone)} required disabled={busy}/></label><label>Method<select name="method" disabled={busy}>{paymentMethods.map(v=><option key={v}>{v}</option>)}</select></label></>}<label>Amount (PKR)<input name="amount" required inputMode="decimal" pattern="(?:0|[1-9][0-9]{0,5})(?:\.[0-9]{1,2})?" disabled={busy} placeholder="1500.00"/></label><button disabled={busy}>{busy?'Saving…':kind==='charge'?'Post charge':'Record payment'}</button></form>;
}
type Receipt={reason?:string;id:string;number:string;createdAt:string;snapshot:{clinicName:string;branchName:string;patientName:string;patientDisplayId:string;method:string;paidOn:string;amountMinor:number;chargedMinor:string;paidMinor:string;balanceMinor:string;allocations:{chargeId:string;description:string;amountMinor:number}[]}};
export function SavedReceipt({receiptId,kind='payment'}:{receiptId:string;kind?:'payment'|'refund'}){
 const {scope,can}=useClinic();const [receipt,setReceipt]=useState<Receipt|null>(null);const [error,setError]=useState('');const allowed=can('billing.read')&&can('patient.demographics.read');
 useEffect(()=>{if(!allowed)return;const controller=new AbortController();api(`/api/v1/${kind==='refund'?'refunds':'receipts'}/${receiptId}`,{headers:scopeHeaders(scope),signal:controller.signal}).then(data=>{if(!controller.signal.aborted)setReceipt(data.receipt);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[scope,receiptId,allowed,kind]);
 if(!allowed)return <section className="staff-workspace live-inner"><h1>Receipt</h1><p>Billing read access is required.</p></section>;
 return <div className="staff-workspace live-inner">{error&&<p role="alert" className="staff-error">{error}</p>}{receipt?<><button className="print-control" onClick={()=>window.print()}>Print receipt</button><section className="saved-receipt"><h1>{receipt.snapshot.clinicName}</h1><p>{receipt.snapshot.branchName}</p><h2>{kind==='refund'?'Refund confirmation':'Payment receipt'}</h2><p className="receipt-number">{receipt.number}</p><p>{receipt.snapshot.patientName} · {receipt.snapshot.patientDisplayId}</p><p>Paid on {receipt.snapshot.paidOn} by {receipt.snapshot.method}</p>{receipt.reason&&<p>Reason: {receipt.reason}</p>}<h2>{kind==='refund'?'Returned':'Received'} {moneyMinor(receipt.snapshot.amountMinor)}</h2><table><thead><tr><th>{kind==='refund'?'Reversed allocation':'Allocation'}</th><th>Amount</th></tr></thead><tbody>{receipt.snapshot.allocations.map(a=><tr key={a.chargeId}><td>{a.description}</td><td>{moneyMinor(a.amountMinor)}</td></tr>)}</tbody></table><p>Charges at payment: {moneyMinor(receipt.snapshot.chargedMinor)}</p><p>Payments at payment: {moneyMinor(receipt.snapshot.paidMinor)}</p><p>Balance after payment: {moneyMinor(receipt.snapshot.balanceMinor)}</p><p>This document preserves the account snapshot when this entry was recorded.</p></section></>:!error&&<p role="status">Loading receipt…</p>}</div>;
}

function RefundForm({payments,onSaved}:{payments:Account['payments'];onSaved:()=>void}){
 const {scope}=useClinic();const [busy,setBusy]=useState(false);const [error,setError]=useState('');const operation=useRef<{id:string;payload:string}|null>(null);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const values=Object.fromEntries(new FormData(e.currentTarget));const {paymentId,...details}=values;const payload=JSON.stringify(values);if(operation.current&&operation.current.payload!==payload){setError('Resolve the original refund request before changing its details.');return;}operation.current??={id:crypto.randomUUID(),payload};setBusy(true);setError('');try{await api(`/api/v1/payments/${paymentId}/refunds`,{method:'POST',headers:scopeHeaders(scope),body:JSON.stringify({...details,operationId:operation.current.id})});operation.current=null;onSaved();}catch(e){if(e instanceof Error&&'status' in e&&Number(e.status)>=400&&Number(e.status)<500&&(!('code' in e)||e.code!=='OPERATION_CONFLICT'))operation.current=null;setError(e instanceof Error?e.message:'Refund could not be saved.');}finally{setBusy(false);}}
 return <form onSubmit={submit}><p>Record money already returned using the original payment method. A refund restores the unpaid balance on the charge.</p>{error&&<p role="alert" className="staff-error">{error}</p>}<label>Original payment<select name="paymentId" disabled={busy}>{payments.map(p=><option key={p.id} value={p.id}>{p.paidOn} · {moneyMinor(p.amountMinor)} · {p.method}</option>)}</select></label><label>Return date<input name="paidOn" type="date" defaultValue={businessDate(scope.timezone)} required disabled={busy}/></label><label>Amount returned (PKR)<input name="amount" inputMode="decimal" required disabled={busy}/></label><label>Reason<input name="reason" minLength={3} maxLength={500} required disabled={busy}/></label><button disabled={busy}>{busy?'Saving…':'Record refund'}</button></form>;
}
