'use client';
import { useEffect,useState,type FormEvent } from 'react';
import { businessDate,moneyMinor } from '@/lib/finance/contracts';
import { api,scopeHeaders,useClinic } from './session';
type Snapshot={openingMinor:string;countedMinor:string;cashReceiptsMinor:string;cashRefundsMinor:string;cashExpensesMinor:string;expectedMinor:string;varianceMinor:string;note:string};
type Summary={businessDate:string;draft:{version:number;openingMinor:number;countedMinor:number;note:string}|null;approval:{snapshot:Snapshot;approvedAt:string}|null;cashReceiptsMinor:string;cashRefundsMinor:string;cashExpensesMinor:string;expectedMinor:string;varianceMinor:string};
const decimal=(n:number)=>`${Math.floor(n/100)}.${String(n%100).padStart(2,'0')}`;
export function DailyClosing(){
 const {scope,can}=useClinic();const [day,setDay]=useState(()=>businessDate(scope.timezone));const [summary,setSummary]=useState<Summary|null>(null);const [revision,setRevision]=useState(0);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const allowed=can('closing.read');
 useEffect(()=>{if(!allowed)return;const controller=new AbortController();api(`/api/v1/closings?businessDate=${day}`,{headers:scopeHeaders(scope),signal:controller.signal}).then(data=>{if(!controller.signal.aborted)setSummary(data);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[scope,day,revision,allowed]);
 const refresh=()=>{setSummary(null);setError('');setRevision(n=>n+1);};
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy||!summary)return;const values=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);setError('');setNotice('');try{await api('/api/v1/closings',{method:'POST',headers:scopeHeaders(scope),body:JSON.stringify({...values,businessDate:day,expectedVersion:summary.draft?.version??0})});setNotice('Cash count saved. A different authorized staff member must approve it.');refresh();}catch(e){setError(e instanceof Error?e.message:'Unable to save closing draft.');}finally{setBusy(false);}}
 async function approve(){if(busy||!summary?.draft)return;setBusy(true);setError('');setNotice('');try{await api('/api/v1/closings',{method:'PATCH',headers:scopeHeaders(scope),body:JSON.stringify({businessDate:day,expectedVersion:summary.draft.version,expectedCashMinor:summary.expectedMinor})});setNotice('Closing approved. This business day is locked.');refresh();}catch(e){setError(e instanceof Error?e.message:'Unable to approve closing.');}finally{setBusy(false);}}
 if(!allowed)return <section className="staff-workspace live-inner"><h1>Daily closing</h1><p>Your account needs closing read access.</p></section>;
 const values=summary?.approval?.snapshot??summary;
 return <div className="staff-workspace live-inner"><h1>Daily cash closing</h1><p>Reconcile recorded cash payments and paid cash expenses for {scope.branchName}.</p>{error&&<p role="alert" className="staff-error">{error}</p>}{notice&&<p role="status">{notice}</p>}<section><label>Business date<input type="date" value={day} disabled={busy} required onChange={e=>{setDay(e.target.value);setSummary(null);setError('');setNotice('');}}/></label><button disabled={busy} onClick={refresh}>Refresh totals</button></section>{summary&&values?<><section><h2>{summary.approval?'Approved closing':'Current cash totals'}</h2><p>Cash receipts: {moneyMinor(values.cashReceiptsMinor)}</p><p>Cash refunds: {moneyMinor(values.cashRefundsMinor)}</p><p>Paid cash expenses: {moneyMinor(values.cashExpensesMinor)}</p><p>Opening float: {moneyMinor(summary.approval?.snapshot.openingMinor??summary.draft?.openingMinor??0)}</p><p>Expected cash: {moneyMinor(values.expectedMinor)}</p><p>Counted cash: {moneyMinor(summary.approval?.snapshot.countedMinor??summary.draft?.countedMinor??0)}</p><p>Variance: {moneyMinor(values.varianceMinor)}</p>{summary.approval&&<><p>Approved {new Date(summary.approval.approvedAt).toLocaleString()}</p><p>{summary.approval.snapshot.note}</p><p>Payments and paid expenses cannot be added to this branch business day.</p></>}</section>{!summary.approval&&can('closing.write')&&scope.currency==='PKR'&&<section><h2>Prepare cash count</h2><form onSubmit={save} key={`${day}:${summary.draft?.version??0}`}><label>Opening float (PKR)<input name="opening" inputMode="decimal" defaultValue={decimal(summary.draft?.openingMinor??0)} required/></label><label>Counted cash (PKR)<input name="counted" inputMode="decimal" defaultValue={decimal(summary.draft?.countedMinor??0)} required/></label><label>Reconciliation note<textarea name="note" defaultValue={summary.draft?.note??''} maxLength={500}/></label><button disabled={busy}>Save cash count</button></form></section>}{!summary.approval&&summary.draft&&can('closing.approve')&&<section><h2>Review and approve</h2><p>Approval requires a different staff member from the latest draft author. Explain every cash difference before approving.</p><button disabled={busy} onClick={approve}>Approve and lock business day</button></section>}</>:!error&&<p role="status">Loading daily totals…</p>}</div>;
}
