'use client';
import { useEffect, useRef, useState, type FormEvent } from 'react';
import { categories, methods } from '@/lib/expenses/input';
import { api, scopeHeaders, useClinic } from './session';
type Expense={id:string;paidOn:string;description:string;category:string;method:string;amountMinor:number;currency:string};
type Result={expenses:Expense[];count:number;totalMinor:string;cashMinor:string};
function money(value:string|number){const minor=BigInt(value);return `PKR ${minor/BigInt(100)}.${(minor%BigInt(100)).toString().padStart(2,'0')}`;}
function today(timezone:string){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());return ['year','month','day'].map(k=>parts.find(p=>p.type===k)?.value).join('-');}
export function ExpenseLedger(){
 const {scope,can}=useClinic();const [day,setDay]=useState(()=>today(scope.timezone));const [offset,setOffset]=useState(0);const [result,setResult]=useState<Result|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [revision,setRevision]=useState(0);const [saved,setSaved]=useState('');const operation=useRef<{key:string;payload:string}|null>(null);
 const allowed=can('expense.read');
 useEffect(()=>{if(!allowed)return;const controller=new AbortController();api(`/api/v1/expenses?paidOn=${day}&offset=${offset}`,{headers:scopeHeaders(scope),signal:controller.signal}).then(data=>{if(!controller.signal.aborted)setResult(data);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[scope,day,offset,revision,allowed]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const form=e.currentTarget;const values=Object.fromEntries(new FormData(form));const payload=JSON.stringify(values);if(operation.current&&operation.current.payload!==payload){setError('Retry the original details before changing an expense with an uncertain result. Reload and check the ledger first.');return;}operation.current??={key:crypto.randomUUID(),payload};setBusy(true);setError('');setSaved('');try{await api('/api/v1/expenses',{method:'POST',headers:scopeHeaders(scope),body:JSON.stringify({...values,operationId:operation.current.key})});operation.current=null;form.reset();setDay(String(values.paidOn));setOffset(0);setResult(null);setRevision(n=>n+1);setSaved('Expense saved.');}catch(e){if(e instanceof Error && 'status' in e && Number(e.status)>=400 && Number(e.status)<500 && Number(e.status)!==409)operation.current=null;setError(e instanceof Error?e.message:'Unable to save expense.');}finally{setBusy(false);}}
 if(!allowed)return <section className="staff-workspace live-inner"><h1>Expenses</h1><p>Your account needs expense read access for this branch.</p></section>;
 return <div className="staff-workspace live-inner"><h1>Expenses</h1><p>Recorded payments for {scope.branchName}. Entries are saved with an audit trail.</p>{error&&<p className="staff-error" role="alert">{error}</p>}{saved&&<p role="status">{saved}</p>}<section><label>Ledger date<input type="date" value={day} required onChange={e=>{setDay(e.target.value);setOffset(0);setResult(null);setError('');}}/></label>{result?<><p>{result.count} expenses · Total {money(result.totalMinor)} · Cash {money(result.cashMinor)}</p><div className="table-scroll"><table><thead><tr><th>Description</th><th>Category</th><th>Paid by</th><th>Amount</th></tr></thead><tbody>{result.expenses.map(row=><tr key={row.id}><td>{row.description}</td><td>{row.category}</td><td>{row.method}</td><td>{money(row.amountMinor)}</td></tr>)}</tbody></table></div>{!result.count&&<p>No expenses recorded for this date.</p>}<div className="live-pagination"><button disabled={offset===0} onClick={()=>{setResult(null);setError('');setOffset(n=>n-50);}}>Previous</button><span>{result.count?offset+1:0}–{Math.min(offset+50,result.count)} of {result.count}</span><button disabled={offset+50>=result.count} onClick={()=>{setResult(null);setError('');setOffset(n=>n+50);}}>Next</button></div></>:!error&&<p role="status">Loading expenses…</p>}</section>{can('expense.write')&&scope.currency==='PKR'&&<section><h2>Record paid expense</h2><p>Use this for an expense already paid. Confirm the details before saving; corrections will require a future reversal workflow.</p><form onSubmit={submit}><label>Payment date<input name="paidOn" type="date" defaultValue={day} required/></label><label>Description<input name="description" maxLength={240} required/></label><label>Category<select name="category">{categories.map(v=><option key={v}>{v}</option>)}</select></label><label>Payment method<select name="method">{methods.map(v=><option key={v}>{v}</option>)}</select></label><label>Amount (PKR)<input name="amount" inputMode="decimal" pattern="(?:0|[1-9][0-9]{0,5})(?:\.[0-9]{1,2})?" required placeholder="1250.00"/></label><button disabled={busy}>{busy?'Saving…':'Record expense'}</button></form></section>}</div>;
}
