'use client';
import Link from 'next/link';
import { useEffect,useRef,useState,type FormEvent } from 'react';
import { businessDate } from '@/lib/finance/contracts';
import { dueBucket,followUpStatuses,followUpTypes,statusLabels,type FollowUpStatus } from '@/lib/follow-ups/contracts';
import { api,scopeHeaders,useClinic } from './session';
type Staff={id:string;name:string};
type Item={id:string;patientName:string;type:string;customType:string;dueOn:string;status:FollowUpStatus;assigneeId:string|null};
type Detail={followUp:{id:string;patientId:string;visitId:string|null;type:string;customType:string;dueOn:string;status:FollowUpStatus;assigneeId:string|null;version:number;appointmentId:string|null};patientName:string;canWrite:boolean;canBook:boolean;appointment:{id:string;status:string;startsAt:string}|null;events:{id:string;kind:string;version:number;createdAt:string;actorName:string;detail:{note:string;status?:FollowUpStatus;channel?:string;outcome?:string;dueOn?:string}}[]};
function useCommand(){
 const {scope}=useClinic();const [busy,setBusy]=useState(false);const [error,setError]=useState('');const operation=useRef<{id:string;payload:string}|null>(null);
 async function send(url:string,method:string,values:Record<string,unknown>,saved:(data:{id:string})=>void){if(busy)return;const payload=JSON.stringify({url,method,...values});if(operation.current&&operation.current.payload!==payload){setError('Retry the previous request before changing its details.');return;}operation.current??={id:crypto.randomUUID(),payload};setBusy(true);setError('');try{const data=await api(url,{method,headers:scopeHeaders(scope),body:JSON.stringify({...values,operationId:operation.current.id})});operation.current=null;saved(data);}catch(e){if(e instanceof Error&&'status' in e&&Number(e.status)>=400&&Number(e.status)<500&&(!('code' in e)||e.code!=='OPERATION_CONFLICT'))operation.current=null;setError(e instanceof Error?e.message:'Follow-up could not be saved.');}finally{setBusy(false);}}
 return {busy,error,send};
}
export function FollowUps({initialVisitId='',initialFollowUpId=''}:{initialVisitId?:string;initialFollowUpId?:string}){
 const {scope,can}=useClinic();const [items,setItems]=useState<Item[]|null>(null);const [staff,setStaff]=useState<Staff[]>([]);const [selected,setSelected]=useState(initialFollowUpId);const [bucket,setBucket]=useState('all');const [status,setStatus]=useState('open');const [assignee,setAssignee]=useState('');const [offset,setOffset]=useState(0);const [more,setMore]=useState(false);const [revision,setRevision]=useState(0);const [error,setError]=useState('');const allowed=can('followup.read')&&can('patient.demographics.read')&&can('patient.clinical.read');
 useEffect(()=>{if(!allowed)return;const c=new AbortController();api('/api/v1/follow-ups/staff',{headers:scopeHeaders(scope),signal:c.signal}).then(data=>{if(!c.signal.aborted)setStaff(data.staff);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[scope,allowed]);
 useEffect(()=>{if(!allowed)return;const c=new AbortController();const query=new URLSearchParams({bucket,status,offset:String(offset),...(assignee?{assigneeId:assignee}:{})});api(`/api/v1/follow-ups?${query}`,{headers:scopeHeaders(scope),signal:c.signal}).then(data=>{if(!c.signal.aborted){setItems(data.items);setMore(data.hasMore);setError('');}}).catch(e=>{if(!c.signal.aborted){setItems(null);setError(e.message);}});return()=>c.abort();},[scope,allowed,bucket,status,assignee,offset,revision]);
 if(!allowed)return <section className="staff-workspace live-inner"><h1>Follow-ups and recalls</h1><p>Your account needs follow-up, clinical and demographic read access.</p></section>;
 const refresh=()=>{setItems(null);setRevision(n=>n+1);};const filter=(set:(value:string)=>void,value:string)=>{set(value);setItems(null);setOffset(0);};
 return <div className="staff-workspace live-inner"><h1>Follow-ups and recalls</h1><p>Track planned reviews and preventive recalls for {scope.branchName}. Contact logs record staff actions; they do not send messages.</p>{error&&<p role="alert" className="staff-error">{error}</p>}<section><label>Due dates<select value={bucket} onChange={e=>filter(setBucket,e.target.value)}>{['all','today','overdue','upcoming'].map(value=><option key={value} value={value}>{value}</option>)}</select></label><label>Status<select value={status} onChange={e=>filter(setStatus,e.target.value)}><option value="open">Open follow-ups</option><option value="all">All statuses</option>{followUpStatuses.map(value=><option key={value} value={value}>{statusLabels[value]}</option>)}</select></label><label>Assigned staff<select value={assignee} onChange={e=>filter(setAssignee,e.target.value)}><option value="">All staff / unassigned</option>{staff.map(person=><option key={person.id} value={person.id}>{person.name}</option>)}</select></label><button onClick={refresh}>Refresh</button>{can('followup.write')&&<button onClick={()=>setSelected('')}>New follow-up</button>}{items?<><ul>{items.map(item=><li key={item.id}><button onClick={()=>setSelected(item.id)}>{item.patientName} · {item.customType||item.type} · {item.dueOn} ({dueBucket(item.dueOn,businessDate(scope.timezone))}) · {statusLabels[item.status]}</button></li>)}</ul>{!items.length&&<p>No matching follow-ups.</p>}<div className="live-pagination"><button disabled={offset===0} onClick={()=>{setItems(null);setOffset(n=>n-50);}}>Previous</button><span>Page {offset/50+1}</span><button disabled={!more} onClick={()=>{setItems(null);setOffset(n=>n+50);}}>Next</button></div></>:!error&&<p role="status">Loading follow-ups…</p>}</section>{selected?<FollowUpDetail key={selected} id={selected} staff={staff} onChanged={refresh}/>:can('followup.write')?<CreateFollowUp key={initialVisitId} staff={staff} visitId={initialVisitId} saved={id=>{setSelected(id);refresh();}}/>:<p>Select a follow-up to view its history.</p>}</div>;
}
function Assignee({staff,defaultValue='',disabled=false}:{staff:Staff[];defaultValue?:string;disabled?:boolean}){return <label>Assigned staff<select name="assigneeId" defaultValue={defaultValue} disabled={disabled}><option value="">Unassigned</option>{defaultValue&&!staff.some(person=>person.id===defaultValue)&&<option value={defaultValue}>Previously assigned staff</option>}{staff.map(person=><option key={person.id} value={person.id}>{person.name}</option>)}</select></label>;}
function CreateFollowUp({staff,visitId,saved}:{staff:Staff[];visitId:string;saved:(id:string)=>void}){
 const {scope}=useClinic();const {busy,error,send}=useCommand();const [patients,setPatients]=useState<{id:string;name:string}[]>([]);const [search,setSearch]=useState('');const [type,setType]=useState<string>('Periodic check-up');const [linked,setLinked]=useState<{patientId:string;name:string}|null>(null);const [loadError,setLoadError]=useState('');
 useEffect(()=>{const c=new AbortController();if(visitId){api(`/api/v1/visits/${encodeURIComponent(visitId)}`,{headers:scopeHeaders(scope),signal:c.signal}).then(data=>{if(!c.signal.aborted)setLinked({patientId:data.visit.patientId,name:data.patientName});}).catch(e=>{if(!c.signal.aborted)setLoadError(e.message);});}else{api(`/api/v1/patients?search=${encodeURIComponent(search)}`,{headers:scopeHeaders(scope),signal:c.signal}).then(data=>{if(!c.signal.aborted)setPatients(data.patients);}).catch(e=>{if(!c.signal.aborted)setLoadError(e.message);});}return()=>c.abort();},[scope,search,visitId]);
 function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));void send('/api/v1/follow-ups','POST',{...values,patientId:linked?.patientId??values.patientId,visitId:visitId||null,assigneeId:values.assigneeId||null,customType:type==='Custom'?values.customType:''},data=>saved(data.id));}
 return <section><h2>New follow-up / recall</h2>{visitId&&<Link href="/follow-ups">Create without a visit link</Link>}{error&&<p role="alert" className="staff-error">{error}</p>}{loadError&&<p role="alert">{loadError}</p>}{!visitId&&<label>Find patient<input value={search} onChange={e=>setSearch(e.target.value)} maxLength={100} disabled={busy}/></label>}<form onSubmit={create}>{visitId?<p>{linked?`Linked to the clinical visit for ${linked.name}`:'Loading linked visit…'}</p>:<label>Patient<select name="patientId" required disabled={busy}><option value="">Select patient</option>{patients.map(patient=><option key={patient.id} value={patient.id}>{patient.name}</option>)}</select></label>}<label>Type<select name="type" value={type} onChange={e=>setType(e.target.value)} disabled={busy}>{followUpTypes.map(value=><option key={value}>{value}</option>)}</select></label>{type==='Custom'&&<label>Custom type<input name="customType" required minLength={2} maxLength={80} disabled={busy}/></label>}<label>Due date<input name="dueOn" type="date" defaultValue={businessDate(scope.timezone)} required disabled={busy}/></label><Assignee staff={staff} disabled={busy}/><label>Reason / instructions<textarea name="note" required minLength={3} maxLength={1000} disabled={busy}/></label><button disabled={busy||Boolean(visitId&&!linked)}>Save follow-up</button></form></section>;
}
function FollowUpDetail({id,staff,onChanged}:{id:string;staff:Staff[];onChanged:()=>void}){
 const {scope}=useClinic();const [detail,setDetail]=useState<Detail|null>(null);const [revision,setRevision]=useState(0);const [error,setError]=useState('');
 useEffect(()=>{const c=new AbortController();api(`/api/v1/follow-ups/${id}`,{headers:scopeHeaders(scope),signal:c.signal}).then(data=>{if(!c.signal.aborted){setDetail(data);setError('');}}).catch(e=>{if(!c.signal.aborted){setDetail(null);setError(e.message);}});return()=>c.abort();},[scope,id,revision]);
 const reload=()=>{setDetail(null);setRevision(n=>n+1);onChanged();};
 return <section><button onClick={reload}>Reload follow-up</button>{error&&<p role="alert" className="staff-error">{error}</p>}{detail?<><h2>{detail.patientName} · {detail.followUp.customType||detail.followUp.type}</h2><p>{statusLabels[detail.followUp.status]} · Due {detail.followUp.dueOn}</p>{detail.followUp.visitId&&<Link href={`/visits/${detail.followUp.visitId}`}>Open linked clinical visit</Link>}{detail.appointment&&<p>Linked appointment: {new Date(detail.appointment.startsAt).toLocaleString('en-PK',{timeZone:scope.timezone})} · {detail.appointment.status}{detail.appointment.status==='cancelled'&&' — review this follow-up and return it to Due if another booking is needed.'}</p>}{detail.canWrite&&<FollowUpActions key={detail.followUp.version} detail={detail} staff={staff} saved={reload}/>}<h3>Latest 100 history entries</h3>{detail.events.map(event=><article key={event.id}><strong>{event.kind} · {event.actorName} · {new Date(event.createdAt).toLocaleString('en-PK',{timeZone:scope.timezone})}</strong><p>{event.detail.note}</p>{event.detail.channel&&<p>{event.detail.channel} · {event.detail.outcome}</p>}{event.detail.status&&<p>Status: {statusLabels[event.detail.status]}</p>}{event.detail.dueOn&&<p>Due date: {event.detail.dueOn}</p>}</article>)}</>:!error&&<p role="status">Loading follow-up…</p>}</section>;
}
function FollowUpActions({detail,staff,saved}:{detail:Detail;staff:Staff[];saved:()=>void}){
 const {busy,error,send}=useCommand();const [status,setStatus]=useState<FollowUpStatus>(detail.followUp.status==='contacted'?'due':'contacted');const row=detail.followUp;const finished=row.status==='completed'||row.status==='closed';
 function mutate(event:FormEvent<HTMLFormElement>,action:string){event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));const input=action==='edit'?{...values,assigneeId:values.assigneeId||null}:action==='transition'?{...values,appointmentId:status==='booked'?row.appointmentId:null}:values;void send(`/api/v1/follow-ups/${row.id}`,'PATCH',{...input,action,expectedVersion:row.version},saved);}
 function book(event:FormEvent<HTMLFormElement>){event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));const startsAt=new Date(String(values.startsAt));const endsAt=new Date(String(values.endsAt));if(!Number.isFinite(+startsAt)||!Number.isFinite(+endsAt))return;void send(`/api/v1/follow-ups/${row.id}/book`,'POST',{note:values.note,startsAt:startsAt.toISOString(),endsAt:endsAt.toISOString(),expectedVersion:row.version},saved);}
 if(finished)return <p>This follow-up is finished. Create a new record for further care.</p>;
 return <>{error&&<p role="alert" className="staff-error">{error}</p>}<details><summary>Change due date or assignment</summary><form onSubmit={event=>mutate(event,'edit')}><label>Due date<input name="dueOn" type="date" defaultValue={row.dueOn} required disabled={busy}/></label><Assignee staff={staff} defaultValue={row.assigneeId??''} disabled={busy}/><label>Reason<textarea name="note" required minLength={3} maxLength={1000} disabled={busy}/></label><button disabled={busy}>Save changes</button></form></details><details><summary>Record contact attempt</summary><p>This logs contact already made; it does not send a message or change status automatically.</p><form onSubmit={event=>mutate(event,'contact')}><label>Channel<select name="channel" disabled={busy}>{['Phone','In person','WhatsApp','SMS','Email','Other'].map(value=><option key={value}>{value}</option>)}</select></label><label>Outcome<select name="outcome" disabled={busy}>{['Reached','No answer','Left message','Declined','Other'].map(value=><option key={value}>{value}</option>)}</select></label><label>Contact note<textarea name="note" required minLength={3} maxLength={1000} disabled={busy}/></label><button disabled={busy}>Record contact</button></form></details><details><summary>Change follow-up status</summary><form onSubmit={event=>mutate(event,'transition')}><label>Status<select name="status" value={status} onChange={e=>setStatus(e.target.value as FollowUpStatus)} disabled={busy}>{followUpStatuses.filter(value=>value!==row.status&&(value!=='booked'||Boolean(row.appointmentId))).map(value=><option key={value} value={value}>{statusLabels[value]}</option>)}</select></label><label>Reason / care outcome<textarea name="note" required minLength={3} maxLength={1000} disabled={busy}/></label><p>Completed and Closed finish this record. Booking alone does not mean care is completed.</p><button disabled={busy}>Save status</button></form></details>{detail.canBook&&row.status!=='booked'&&<details><summary>Book the follow-up appointment</summary><p>Enter times in your device timezone. They will be saved as exact instants.</p><form onSubmit={book}><label>Starts<input name="startsAt" type="datetime-local" required disabled={busy}/></label><label>Ends<input name="endsAt" type="datetime-local" required disabled={busy}/></label><label>Booking note<textarea name="note" required minLength={3} maxLength={1000} disabled={busy}/></label><button disabled={busy}>Book and link appointment</button></form></details>}</>;
}
