'use client';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { CalendarDays,Users,Check } from 'lucide-react';
import { api,scopeHeaders,useClinic } from './session';
type Overview={patients:number;appointments:{booked:number;arrived:number;cancelled:number}|null};
export function Overview(){const {scope,can}=useClinic();const [data,setData]=useState<Overview|null>(null);const [error,setError]=useState('');const [revision,setRevision]=useState(0);
 useEffect(()=>{if(!can('patient.demographics.read'))return;const c=new AbortController();const start=new Date();start.setHours(0,0,0,0);const end=new Date(start);end.setDate(end.getDate()+1);api(`/api/v1/overview?${new URLSearchParams({startsAt:start.toISOString(),endsAt:end.toISOString()})}`,{headers:scopeHeaders(scope),signal:c.signal}).then(result=>{if(!c.signal.aborted)setData(result);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[scope,can,revision]);
 return <><div className="page-heading"><div><p className="eyebrow">Your clinic</p><h1>Overview</h1></div><button className="text-button" onClick={()=>{setData(null);setError('');setRevision(v=>v+1);}}>Refresh overview</button></div><div className="welcome-card"><div><p className="welcome-tag">CLINIC WORKSPACE</p><h2>{scope.clinicName}</h2><p>{scope.branchName} · Saved patient records and branch appointments</p></div></div>{error&&<p role="alert" className="form-error">{error}</p>}{!can('patient.demographics.read')?<section className="panel empty-state"><h3>Patient access required</h3><p>Your account needs patient demographic read permission to see this overview.</p></section>:!data&&!error?<p role="status">Loading saved clinic records…</p>:data&&<div className="stats-grid"><div className="stat-card"><span className="stat-label">Registered patients<Users size={18}/></span><strong>{data.patients}</strong><p>All patients in this clinic</p></div><div className="stat-card"><span className="stat-label">Booked today<CalendarDays size={18}/></span><strong>{data.appointments?.booked??'—'}</strong><p>{data.appointments?'Selected branch · device-local day':'Appointment permission required'}</p></div><div className="stat-card"><span className="stat-label">Arrived today<Check size={18}/></span><strong>{data.appointments?.arrived??'—'}</strong><p>{data.appointments?'Selected branch · device-local day':'Appointment permission required'}</p></div></div>}<section className="panel live-actions"><h2>Continue your work</h2><p>Register a patient or open the branch calendar.</p><div><Link href="/patients" className="text-button">Open patients →</Link><Link href="/appointments" className="text-button">Open appointments →</Link></div></section></>;
}
