'use client';
import Link from 'next/link';
import { useEffect,useRef,useState,type FormEvent } from 'react';
import { businessDate } from '@/lib/finance/contracts';
import type { DemographicBody } from '@/lib/patient-profile/contracts';
import { PatientClinicalProfile } from './patient-clinical';
import { api,scopeHeaders,useClinic } from './session';
type Profile={patient:{id:string;name:string;displayId:string;phone:string;email:string|null};profile:{version:number;body:DemographicBody};revisions:{version:number;body:DemographicBody;reason:string;createdAt:string;actorName:string}[];canWrite:boolean;canArchive:boolean};
function DemographicDetails({body}:{body:DemographicBody}){return <dl><dt>Status</dt><dd>{body.status}</dd><dt>Date of birth</dt><dd>{body.dob??'Unknown / not recorded'}</dd><dt>Reported age</dt><dd>{body.reportedAge===null?'Not recorded':`${body.reportedAge} years, as reported on ${body.ageAsOf}`}</dd><dt>Gender (as reported)</dt><dd>{body.gender||'Not recorded'}</dd><dt>Address</dt><dd className="clinical-note-text">{body.address||'Not recorded'}</dd><dt>Alternate phone</dt><dd>{body.alternatePhone||'Not recorded'}</dd><dt>Emergency contact</dt><dd>{[body.emergencyName,body.emergencyPhone,body.emergencyRelationship].filter(Boolean).join(' · ')||'Not recorded'}</dd></dl>;}
export function PatientProfile({patientId}:{patientId:string}){
 const {scope,can}=useClinic();const [data,setData]=useState<Profile|null>(null);const [revision,setRevision]=useState(0);const [error,setError]=useState('');const allowed=can('patient.demographics.read');
 useEffect(()=>{if(!allowed)return;const c=new AbortController();api(`/api/v1/patients/${patientId}/profile`,{headers:scopeHeaders(scope),signal:c.signal}).then(result=>{if(!c.signal.aborted){setData(result);setError('');}}).catch(e=>{if(!c.signal.aborted){setData(null);setError(e.message);}});return()=>c.abort();},[scope,patientId,allowed,revision]);
 const reload=()=>{setData(null);setRevision(n=>n+1);};if(!allowed)return <section><h1>Patient profile</h1><p>Patient demographic read access is required.</p></section>;
 return <div className="staff-workspace live-inner"><Link href="/patients">Back to patients</Link><h1>{data?.patient.name??'Patient profile'}</h1>{error&&<p role="alert" className="staff-error">{error}</p>}{data?<><p>{data.patient.displayId} · {data.patient.phone} {data.patient.email&&`· ${data.patient.email}`}</p><Link href={`/patients/${patientId}/timeline`}>Open timeline</Link><button onClick={reload}>Refresh profile</button><section><h2>Patient demographics</h2><p>These fields belong to the clinic patient master. Medical records below remain branch-scoped.</p><DemographicDetails body={data.profile.body}/>{data.canWrite&&<ProfileForm key={data.profile.version} patientId={patientId} data={data} saved={reload}/>}<h3>Latest 20 demographic versions</h3>{data.revisions.map(item=><details key={item.version}><summary>Version {item.version} · {item.actorName} · {new Date(item.createdAt).toLocaleString('en-PK',{timeZone:scope.timezone})}</summary><p>{item.reason}</p><DemographicDetails body={item.body}/></details>)}</section><PatientClinicalProfile patientId={patientId}/></>:!error&&<p role="status">Loading patient profile…</p>}</div>;
}
function ProfileForm({patientId,data,saved}:{patientId:string;data:Profile;saved:()=>void}){
 const {scope}=useClinic();const body=data.profile.body;const [mode,setMode]=useState(body.dob?'dob':body.reportedAge!==null?'age':'unknown');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const operation=useRef<{id:string;payload:string}|null>(null);
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;const f=new FormData(event.currentTarget);const next={dob:mode==='dob'?String(f.get('dob')):null,reportedAge:mode==='age'?Number(f.get('reportedAge')):null,ageAsOf:mode==='age'?String(f.get('ageAsOf')):null,gender:f.get('gender'),address:f.get('address'),alternatePhone:f.get('alternatePhone'),emergencyName:f.get('emergencyName'),emergencyPhone:f.get('emergencyPhone'),emergencyRelationship:f.get('emergencyRelationship'),status:f.get('status')};const values={body:next,expectedVersion:data.profile.version,reason:f.get('reason')};const payload=JSON.stringify(values);if(operation.current&&operation.current.payload!==payload){setError('Retry the previous profile request before changing its details.');return;}operation.current??={id:crypto.randomUUID(),payload};setBusy(true);setError('');try{await api(`/api/v1/patients/${patientId}/profile`,{method:'POST',headers:scopeHeaders(scope),body:JSON.stringify({...values,operationId:operation.current.id})});operation.current=null;saved();}catch(e){if(e instanceof Error&&'status' in e&&Number(e.status)>=400&&Number(e.status)<500&&(!('code' in e)||e.code!=='OPERATION_CONFLICT'))operation.current=null;setError(e instanceof Error?e.message:'Profile could not be saved.');}finally{setBusy(false);}}
 return <details><summary>Edit patient demographics</summary>{error&&<p role="alert" className="staff-error">{error}</p>}<form onSubmit={save}><label>Age information<select value={mode} onChange={e=>setMode(e.target.value)} disabled={busy}><option value="unknown">Unknown / not recorded</option><option value="dob">Known date of birth</option><option value="age">Reported age (DOB unknown)</option></select></label>{mode==='dob'&&<label>Date of birth<input name="dob" type="date" defaultValue={body.dob??''} max={businessDate(scope.timezone)} required disabled={busy}/></label>}{mode==='age'&&<><label>Reported age in years<input name="reportedAge" type="number" min={0} max={130} step={1} defaultValue={body.reportedAge??''} required disabled={busy}/></label><label>Age reported on<input name="ageAsOf" type="date" defaultValue={body.ageAsOf??businessDate(scope.timezone)} max={businessDate(scope.timezone)} required disabled={busy}/></label><p>Reported age is retained with its date; no birth date is invented.</p></>}<label>Gender (as reported, optional)<input name="gender" defaultValue={body.gender} maxLength={80} disabled={busy}/></label><label>Address<textarea name="address" defaultValue={body.address} maxLength={500} disabled={busy}/></label><label>Alternate phone<input name="alternatePhone" type="tel" defaultValue={body.alternatePhone} maxLength={30} disabled={busy}/></label><label>Emergency contact name<input name="emergencyName" defaultValue={body.emergencyName} maxLength={160} disabled={busy}/></label><label>Emergency phone<input name="emergencyPhone" type="tel" defaultValue={body.emergencyPhone} maxLength={30} disabled={busy}/></label><label>Emergency relationship<input name="emergencyRelationship" defaultValue={body.emergencyRelationship} maxLength={80} disabled={busy}/></label><label>Patient status<select name="status" defaultValue={body.status} disabled={busy}><option value="active" disabled={body.status==='archived'&&!data.canArchive}>Active</option><option value="inactive" disabled={body.status==='archived'&&!data.canArchive}>Inactive</option><option value="archived" disabled={!data.canArchive&&body.status!=='archived'}>Archived</option></select></label><label>Reason for these changes<input name="reason" minLength={3} maxLength={500} required disabled={busy}/></label><button disabled={busy}>Save demographic version</button></form></details>;
}
