'use client';
import { useEffect,useRef,useState,type FormEvent } from 'react';
import { api,scopeHeaders,useClinic } from './session';
type Patient={id:string;displayId:string;name:string;phone:string;email:string|null;version:number};
export function PatientDirectory(){
 const {scope,can}=useClinic();const [patients,setPatients]=useState<Patient[]>([]);const [search,setSearch]=useState('');const [offset,setOffset]=useState(0);const [revision,setRevision]=useState(0);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [editing,setEditing]=useState<Patient|null>(null);const registration=useRef<{payload:string;operationId:string}|null>(null);
 useEffect(()=>{if(!can('patient.demographics.read'))return;const controller=new AbortController();api(`/api/v1/patients?${new URLSearchParams({search,offset:String(offset)})}`,{headers:scopeHeaders(scope),signal:controller.signal}).then(data=>{if(!controller.signal.aborted){setPatients(data.patients);setLoading(false);}}).catch(e=>{if(!controller.signal.aborted){setError(e.message);setLoading(false);}});return()=>controller.abort();},[scope,search,offset,revision,can]);
 function refresh(){setLoading(true);setPatients([]);setError('');setRevision(v=>v+1);}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const form=e.currentTarget;const data=new FormData(form);const patient={name:data.get('name'),phone:data.get('phone'),email:data.get('email')};const payload=JSON.stringify({clinicId:scope.clinicId,patient});if(!registration.current||registration.current.payload!==payload)registration.current={payload,operationId:crypto.randomUUID()};setBusy(true);setError('');setNotice('');try{await api(editing?`/api/v1/patients/${editing.id}`:'/api/v1/patients',{method:editing?'PATCH':'POST',headers:scopeHeaders(scope),body:JSON.stringify(editing?{patient,expectedVersion:editing.version}:{...patient,operationId:registration.current.operationId})});registration.current=null;setEditing(null);form.reset();setNotice(editing?'Patient changes saved.':'Patient registered.');refresh();}catch(e){setError(e instanceof Error?e.message:'Save failed.');}finally{setBusy(false);}}
 if(!can('patient.demographics.read'))return <section className="panel empty-state"><h1>Patient access required</h1><p>Your membership does not include patient demographic access.</p></section>;
 return <div className="staff-workspace live-inner"><div className="page-heading"><div><p className="eyebrow">Patient records</p><h1>Patient directory</h1></div><button disabled={busy} onClick={refresh}>Refresh records</button></div>{error&&<p role="alert" className="staff-error">{error}</p>}{notice&&<p role="status">{notice}</p>}<div className="staff-grid"><section><h2>Saved patients</h2><label>Search patients<input value={search} onChange={e=>{setSearch(e.target.value);setOffset(0);setLoading(true);setPatients([]);setError('');}} placeholder="Name, phone or patient ID"/></label>{loading?<p role="status">Loading patients…</p>:error?null:patients.length===0?<p>No patients match your search.</p>:<ul>{patients.map(p=><li key={p.id}><div><strong>{p.name}</strong><p>{p.phone}</p>{p.email&&<p>{p.email}</p>}</div>{can('patient.demographics.write')&&<button disabled={busy} onClick={()=>{setEditing(p);setError('');setNotice('');}}>Edit</button>}</li>)}</ul>}<div className="live-pagination"><button disabled={busy||loading||offset===0} onClick={()=>{setOffset(v=>Math.max(0,v-50));setLoading(true);setPatients([]);}}>Previous</button><span>Page {offset/50+1}</span><button disabled={busy||loading||patients.length<50} onClick={()=>{setOffset(v=>v+50);setLoading(true);setPatients([]);}}>Next</button></div></section>{can('patient.demographics.write')?<section><h2>{editing?'Edit patient':'Register patient'}</h2><form key={editing?`${editing.id}:${editing.version}`:'new'} onSubmit={save}><label>Full name<input name="name" defaultValue={editing?.name} minLength={2} maxLength={160} disabled={busy} required/></label><label>Phone<input name="phone" type="tel" defaultValue={editing?.phone} minLength={7} maxLength={30} disabled={busy} required/></label><label>Email (optional)<input name="email" type="email" defaultValue={editing?.email||''} maxLength={254} disabled={busy}/></label><button disabled={busy}>{busy?'Saving…':editing?'Save changes':'Register patient'}</button>{editing&&<button disabled={busy} type="button" onClick={()=>setEditing(null)}>Cancel edit</button>}</form><p>Records are saved to this clinic’s database.</p></section>:<section><h2>View access</h2><p>Your membership allows viewing patients. Registration and editing require patient-management permission.</p></section>}</div></div>;
}
