'use client';
import Link from 'next/link';
import { useEffect,useRef,useState,type FormEvent } from 'react';
import { businessDate } from '@/lib/finance/contracts';
import { alertTypes,alertSeverities,type HistoryBody,type AlertBody } from '@/lib/patient-clinical/contracts';
import { api,scopeHeaders,useClinic } from './session';
type Alert={id:string;version:number;body:AlertBody};
type Clinical={patient:{id:string;name:string;displayId:string};history:{version:number;body:HistoryBody;reason:string;createdAt:string;actorName:string}|null;revisions:{version:number;reason:string;createdAt:string;actorName:string}[];alerts:Alert[];activeAlertCount:number;canWrite:boolean};
const labels={medicalHistory:'Medical history',dentalHistory:'Dental history',medications:'Current medications',allergies:'Allergies',tobaccoHistory:'Tobacco history'} as const;
function HistoryFields({body}:{body:HistoryBody}){return <dl>{Object.entries(labels).map(([key,label])=><div key={key}><dt><strong>{label}</strong></dt><dd className="clinical-note-text">{body[key as keyof typeof labels]||'Not recorded'}</dd></div>)}<dt>Information source</dt><dd>{body.source}</dd><dt>Reviewed on</dt><dd>{body.reviewedOn}</dd></dl>;}
function Alerts({alerts}:{alerts:Alert[]}){return <ul>{alerts.map(alert=><li key={alert.id} className={`patient-alert patient-alert-${alert.body.severity}`}><div><strong>{alert.body.severity} · {alert.body.type}</strong><p className="clinical-note-text">{alert.body.text}</p></div></li>)}</ul>;}
export function CurrentClinicalContext({patientId,initial}:{patientId:string;initial:Clinical}){
 const {scope}=useClinic();const [data,setData]=useState<Clinical|null>(initial);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function reload(){setBusy(true);setError('');try{setData(await api(`/api/v1/patients/${patientId}/clinical`,{headers:scopeHeaders(scope)}));}catch(e){setData(null);setError(e instanceof Error?e.message:'Current patient history could not be loaded.');}finally{setBusy(false);}}
 if(!data)return <section className="clinical-context"><h2>Current patient history unavailable</h2><p role="alert" className="staff-error">{error}</p><button disabled={busy} onClick={reload}>Retry current patient history</button></section>;
 return <section className="clinical-context"><h2>Current patient history and alerts · {scope.branchName}</h2><p>This is the latest loaded branch record, separate from the signed visit’s historical content.</p>{error&&<p role="alert" className="staff-error">{error}</p>}<button disabled={busy} onClick={reload}>Reload current patient history</button><Link href={`/patients/${patientId}/profile#clinical`}>Open patient history and alerts</Link><Alerts alerts={data.alerts}/>{!data.activeAlertCount&&<p>No active alerts recorded in this branch. This does not confirm an absence of allergies or medical conditions.</p>}{data.activeAlertCount>data.alerts.length&&<p>Showing {data.alerts.length} of {data.activeAlertCount} active alerts. Open the profile to review additional alerts.</p>}{data.history&&<div><strong>Allergies (latest recorded review)</strong><p className="clinical-note-text">{data.history.body.allergies||'Not recorded'}</p><strong>Medications (latest recorded review)</strong><p className="clinical-note-text">{data.history.body.medications||'Not recorded'}</p></div>}<details><summary>Reviewed history {data.history?`· ${data.history.body.reviewedOn}`:'· not yet recorded'}</summary>{data.history?<HistoryFields body={data.history.body}/>:<p>Medical history has not been recorded in this branch.</p>}</details></section>;
}
function useClinicalSave(){const {scope}=useClinic();const [busy,setBusy]=useState(false);const [error,setError]=useState('');const operation=useRef<{id:string;payload:string}|null>(null);async function send(url:string,method:string,values:Record<string,unknown>,saved:()=>void){if(busy)return;const payload=JSON.stringify({url,method,...values});if(operation.current&&operation.current.payload!==payload){setError('Retry the previous request before changing its details.');return;}operation.current??={id:crypto.randomUUID(),payload};setBusy(true);setError('');try{await api(url,{method,headers:scopeHeaders(scope),body:JSON.stringify({...values,operationId:operation.current.id})});operation.current=null;saved();}catch(e){if(e instanceof Error&&'status' in e&&Number(e.status)>=400&&Number(e.status)<500&&(!('code' in e)||e.code!=='OPERATION_CONFLICT'))operation.current=null;setError(e instanceof Error?e.message:'Clinical record could not be saved.');}finally{setBusy(false);}}return {busy,error,send};}
export function PatientClinicalProfile({patientId}:{patientId:string}){
 const {scope,can}=useClinic();const [data,setData]=useState<Clinical|null>(null);const [revision,setRevision]=useState(0);const [error,setError]=useState('');const [older,setOlder]=useState<{version:number;body:HistoryBody}|null>(null);const allowed=can('patient.clinical.read')&&can('patient.demographics.read');
 useEffect(()=>{if(!allowed)return;const c=new AbortController();api(`/api/v1/patients/${patientId}/clinical`,{headers:scopeHeaders(scope),signal:c.signal}).then(result=>{if(!c.signal.aborted){setData(result);setError('');}}).catch(e=>{if(!c.signal.aborted){setData(null);setError(e.message);}});return()=>c.abort();},[scope,patientId,allowed,revision]);
 async function show(version:number){setOlder(null);setError('');try{const result=await api(`/api/v1/patients/${patientId}/clinical/history/${version}`,{headers:scopeHeaders(scope)});setOlder(result);}catch(e){setError(e instanceof Error?e.message:'History version unavailable.');}}
 const reload=()=>{setData(null);setOlder(null);setRevision(n=>n+1);};
 if(!allowed)return <section id="clinical"><h2>Medical history and alerts</h2><p>Clinical read access is required for this part of the patient profile.</p></section>;
 return <section id="clinical"><h2>Medical history and alerts · {scope.branchName}</h2>{error&&<p role="alert" className="staff-error">{error}</p>}{data?<><p>{data.patient.name} · {data.patient.displayId}</p><button onClick={reload}>Refresh clinical records</button><CurrentClinicalContext key={data.history?.version??0} patientId={patientId} initial={data}/>{data.canWrite&&<HistoryForm key={data.history?.version??0} patientId={patientId} data={data} saved={reload}/>}<h3>Latest 50 history reviews</h3>{data.revisions.map(version=><p key={version.version}><button onClick={()=>void show(version.version)}>View version {version.version}</button> · {version.actorName} · {new Date(version.createdAt).toLocaleString('en-PK',{timeZone:scope.timezone})} · {version.reason}</p>)}{older&&<details open><summary>Historical history version {older.version}</summary><HistoryFields body={older.body}/></details>}<PatientAlertManager key={revision} patientId={patientId} canWrite={data.canWrite} saved={reload}/></>:!error&&<p role="status">Loading history and alerts…</p>}</section>;
}
function HistoryForm({patientId,data,saved}:{patientId:string;data:Clinical;saved:()=>void}){
 const {scope}=useClinic();const {busy,error,send}=useClinicalSave();function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));const {reason,...body}=values;void send(`/api/v1/patients/${patientId}/clinical`,'POST',{expectedVersion:data.history?.version??0,reason,body},saved);}
 return <details><summary>Record a new history review</summary>{error&&<p role="alert" className="staff-error">{error}</p>}<form onSubmit={save}>{Object.entries(labels).map(([key,label])=><label key={key}>{label}<textarea name={key} defaultValue={data.history?.body[key as keyof typeof labels]??''} maxLength={6000} disabled={busy}/></label>)}<label>Information source / reviewed with<input name="source" defaultValue={data.history?.body.source??''} required minLength={2} maxLength={160} disabled={busy}/></label><label>Review date<input name="reviewedOn" type="date" defaultValue={businessDate(scope.timezone)} max={businessDate(scope.timezone)} required disabled={busy}/></label><label>Reason for this review<input name="reason" required minLength={3} maxLength={500} disabled={busy}/></label><button disabled={busy}>Save history review</button></form></details>;
}
function PatientAlertManager({patientId,canWrite,saved}:{patientId:string;canWrite:boolean;saved:()=>void}){
 const {scope}=useClinic();const [alerts,setAlerts]=useState<Alert[]>([]);const [offset,setOffset]=useState(0);const [active,setActive]=useState('true');const [more,setMore]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [selected,setSelected]=useState<{alert:Alert;revisions:{version:number;body:AlertBody;reason:string;actorName:string;createdAt:string}[]}|null>(null);
 useEffect(()=>{const c=new AbortController();api(`/api/v1/patients/${patientId}/clinical/alerts?${new URLSearchParams({active,offset:String(offset)})}`,{headers:scopeHeaders(scope),signal:c.signal}).then(data=>{if(!c.signal.aborted){setAlerts(data.alerts);setMore(data.hasMore);setLoading(false);setError('');}}).catch(e=>{if(!c.signal.aborted){setError(e.message);setLoading(false);}});return()=>c.abort();},[scope,patientId,offset,active]);
 async function open(id:string){setSelected(null);try{setSelected(await api(`/api/v1/patients/${patientId}/clinical/alerts/${id}`,{headers:scopeHeaders(scope)}));}catch(e){setError(e instanceof Error?e.message:'Alert unavailable.');}}
 return <section><h3>Patient alert records</h3>{error&&<p role="alert" className="staff-error">{error}</p>}<label>Alert status<select value={active} onChange={e=>{setActive(e.target.value);setOffset(0);setLoading(true);setSelected(null);}}><option value="true">Active alerts</option><option value="false">Resolved alerts</option><option value="all">All alerts</option></select></label>{loading?<p role="status">Loading alerts…</p>:<><ul>{alerts.map(alert=><li key={alert.id}><div><strong>{alert.body.severity} · {alert.body.type} · {alert.body.active?'Active':'Resolved'}</strong><p>{alert.body.text}</p></div><button onClick={()=>void open(alert.id)}>Open alert history</button></li>)}</ul>{!alerts.length&&<p>No matching alert records.</p>}<div className="live-pagination"><button disabled={!offset} onClick={()=>{setLoading(true);setOffset(n=>n-50);}}>Previous alerts</button><span>Page {offset/50+1}</span><button disabled={!more} onClick={()=>{setLoading(true);setOffset(n=>n+50);}}>Older alerts</button></div></>}{selected&&<><h4>Latest 50 alert revisions</h4>{selected.revisions.map(version=><details key={version.version}><summary>Version {version.version} · {version.actorName} · {new Date(version.createdAt).toLocaleString('en-PK',{timeZone:scope.timezone})} · {version.body.active?'Active':'Resolved'}</summary><p>{version.body.text}</p><p>{version.body.type} · {version.body.severity} · {version.reason}</p></details>)}</>}{canWrite&&<><button onClick={()=>setSelected(null)}>New alert</button><AlertForm key={selected?`${selected.alert.id}:${selected.alert.version}`:'new'} patientId={patientId} alert={selected?.alert} saved={saved}/></>}</section>;
}
function AlertForm({patientId,alert,saved}:{patientId:string;alert?:Alert;saved:()=>void}){
 const {busy,error,send}=useClinicalSave();function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const body={type:form.get('type'),severity:form.get('severity'),text:form.get('text'),active:alert?form.get('active')==='on':true};void send(`/api/v1/patients/${patientId}/clinical/alerts${alert?`/${alert.id}`:''}`,alert?'PATCH':'POST',{body,reason:form.get('reason'),...(alert?{expectedVersion:alert.version}:{})},saved);}
 return <form onSubmit={save}><h4>{alert?'Review / update alert':'New alert'}</h4>{error&&<p role="alert" className="staff-error">{error}</p>}<label>Type<select name="type" defaultValue={alert?.body.type??'other'} disabled={busy}>{alertTypes.map(value=><option key={value}>{value}</option>)}</select></label><label>Severity<select name="severity" defaultValue={alert?.body.severity??'important'} disabled={busy}>{alertSeverities.map(value=><option key={value}>{value}</option>)}</select></label><label>Alert text<textarea name="text" defaultValue={alert?.body.text??''} required minLength={3} maxLength={1000} disabled={busy}/></label>{alert&&<label><input name="active" type="checkbox" defaultChecked={alert.body.active} disabled={busy}/>Active alert (clear to resolve)</label>}<label>Reason for recording / changing<input name="reason" required minLength={3} maxLength={500} disabled={busy}/></label><button disabled={busy}>Save alert revision</button></form>;
}
