'use client';
import { useEffect,useRef,useState,type FormEvent } from 'react';
import { moneyMinor } from '@/lib/finance/contracts';
import type { PlanSnapshot } from '@/lib/plans/contracts';
import { api,scopeHeaders,useClinic } from './session';
type PlanRow={id:string;title:string;patientName:string;status:string;version:number;totalMinor:string};
type Detail={plan:{id:string;status:string;version:number};patientName:string;versions:{id:string;version:number;snapshot:PlanSnapshot;createdAt:string}[];acceptance:{version:number;acceptedBy:string;evidence:string;acceptedAt:string}|null;canWrite:boolean;canAccept:boolean};
type Patient={id:string;name:string;displayId:string};
export function TreatmentPlans(){
 const {scope,can}=useClinic();const [plans,setPlans]=useState<PlanRow[]|null>(null);const [selected,setSelected]=useState('');const [revision,setRevision]=useState(0);const [error,setError]=useState('');
 const allowed=can('plan.read')&&can('patient.clinical.read')&&can('patient.demographics.read');
 useEffect(()=>{if(!allowed)return;const c=new AbortController();api('/api/v1/plans',{headers:scopeHeaders(scope),signal:c.signal}).then(data=>{if(!c.signal.aborted){setPlans(data.plans);setError('');}}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[scope,allowed,revision]);
 if(!allowed)return <section className="staff-workspace live-inner"><h1>Treatment plans</h1><p>Your account needs treatment-plan, clinical and demographic read access.</p></section>;
 const changed=()=>setRevision(n=>n+1);
 return <div className="staff-workspace live-inner"><h1>Treatment plans</h1><p>Save estimates and record the exact version agreed with the patient. Accepting an estimate does not charge the patient or record clinical consent.</p>{error&&<p role="alert" className="staff-error">{error}</p>}<section><h2>Latest 50 plans</h2><button onClick={changed}>Refresh plans</button>{can('plan.write')&&<button onClick={()=>setSelected('')}>New estimate</button>}{plans?.length?<ul>{plans.map(plan=><li key={plan.id}><button onClick={()=>setSelected(plan.id)}>{plan.patientName} · {plan.title} · {moneyMinor(plan.totalMinor)} · {plan.status} · v{plan.version}</button></li>)}</ul>:<p>{plans?'No saved plans.':'Loading plans…'}</p>}</section>{selected?<PlanDetail key={selected} id={selected} onChanged={changed}/>:can('plan.write')?<NewPlan onCreated={id=>{setSelected(id);changed();}}/>:<p>Select a plan to review its estimate.</p>}</div>;
}
function NewPlan({onCreated}:{onCreated:(id:string)=>void}){
 const {scope}=useClinic();const [patients,setPatients]=useState<Patient[]>([]);const [search,setSearch]=useState('');const [error,setError]=useState('');
 useEffect(()=>{const c=new AbortController();api(`/api/v1/patients?search=${encodeURIComponent(search)}`,{headers:scopeHeaders(scope),signal:c.signal}).then(data=>{if(!c.signal.aborted)setPatients(data.patients);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[scope,search]);
 return <section><h2>New estimate</h2>{error&&<p role="alert">{error}</p>}<label>Find patient<input value={search} onChange={e=>setSearch(e.target.value)} maxLength={100}/></label><EstimateForm patients={patients} onSaved={onCreated}/></section>;
}
function PlanDetail({id,onChanged}:{id:string;onChanged:()=>void}){
 const {scope}=useClinic();const [detail,setDetail]=useState<Detail|null>(null);const [revision,setRevision]=useState(0);const [error,setError]=useState('');
 useEffect(()=>{const c=new AbortController();api(`/api/v1/plans/${id}`,{headers:scopeHeaders(scope),signal:c.signal}).then(data=>{if(!c.signal.aborted){setDetail(data);setError('');}}).catch(e=>{if(!c.signal.aborted){setDetail(null);setError(e.message);}});return()=>c.abort();},[scope,id,revision]);
 const reload=()=>{setDetail(null);setRevision(n=>n+1);onChanged();};
 return <section><button onClick={reload}>Reload estimate</button>{error&&<p role="alert" className="staff-error">{error}</p>}{detail?<><h2>{detail.patientName} · {detail.plan.status}</h2>{detail.plan.status==='draft'?<EstimateForm key={detail.plan.version} detail={detail} onSaved={reload}/>:<><Snapshot snapshot={detail.versions[0].snapshot}/><p>Accepted version {detail.acceptance?.version} by {detail.acceptance?.acceptedBy} · {detail.acceptance&&new Date(detail.acceptance.acceptedAt).toLocaleString()}</p><p>Evidence: {detail.acceptance?.evidence}</p><p>The accepted estimate is locked. Create a separate plan for further proposed work.</p></>}<h3>Latest 100 estimate versions</h3>{detail.versions.map(version=><details key={version.id}><summary>Version {version.version} · {new Date(version.createdAt).toLocaleString()}</summary><Snapshot snapshot={version.snapshot}/></details>)}</>:!error&&<p role="status">Loading estimate…</p>}</section>;
}
function Snapshot({snapshot}:{snapshot:PlanSnapshot}){return <><h3>{snapshot.title}</h3><p>{snapshot.note}</p><ul>{snapshot.items.map(item=><li key={item.id}>{item.description}{item.tooth&&` · Tooth/site: ${item.tooth}`} · {item.quantity} × {moneyMinor(item.unitPriceMinor)} = {moneyMinor(item.totalMinor)}</li>)}</ul><p><strong>Total: {moneyMinor(snapshot.totalMinor)}</strong></p></>;}
const price=(n:number)=>`${Math.floor(n/100)}.${String(n%100).padStart(2,'0')}`;
const newItem=()=>({id:crypto.randomUUID(),description:'',tooth:'',quantity:1,unitPrice:''});
function EstimateForm({detail,patients,onSaved}:{detail?:Detail;patients?:Patient[];onSaved:(id:string)=>void}){
 const {scope}=useClinic();const snapshot=detail?.versions[0]?.snapshot;
 const [title,setTitle]=useState(snapshot?.title??'Treatment estimate');const [note,setNote]=useState(snapshot?.note??'');const [patientId,setPatientId]=useState('');
 const [items,setItems]=useState(()=>snapshot?snapshot.items.map(item=>({...item,unitPrice:price(item.unitPriceMinor)})):[newItem()]);
 const [acceptedBy,setAcceptedBy]=useState('');const [evidence,setEvidence]=useState('');const [dirty,setDirty]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const operation=useRef<{id:string;payload:string}|null>(null);const editable=!detail||detail.canWrite;
 function updateItem(id:string,key:'description'|'tooth'|'quantity'|'unitPrice',value:string|number){setDirty(true);setItems(rows=>rows.map(item=>item.id===id?{...item,[key]:value}:item));}
 async function submit(event:FormEvent,accept=false){event.preventDefault();if(busy)return;const body={title,note,items:items.map(({id,description,tooth,quantity,unitPrice})=>({id,description,tooth,quantity,unitPrice}))};const values=accept?{expectedVersion:detail!.plan.version,acceptedBy,evidence}:detail?{expectedVersion:detail.plan.version,body}:{patientId,body};const payload=JSON.stringify({accept,...values});if(operation.current&&operation.current.payload!==payload){setError('Resolve the previous request before changing its details.');return;}operation.current??={id:crypto.randomUUID(),payload};setBusy(true);setError('');try{const result=await api(detail?`/api/v1/plans/${detail.plan.id}${accept?'/accept':''}`:'/api/v1/plans',{method:detail&&!accept?'PATCH':'POST',headers:scopeHeaders(scope),body:JSON.stringify({...values,operationId:operation.current.id})});operation.current=null;onSaved(detail?.plan.id??result.id);}catch(e){if(e instanceof Error&&'status' in e&&Number(e.status)>=400&&Number(e.status)<500&&(!('code' in e)||e.code!=='OPERATION_CONFLICT'))operation.current=null;setError(e instanceof Error?e.message:'Estimate could not be saved.');}finally{setBusy(false);}}
 return <>{error&&<p role="alert" className="staff-error">{error}</p>}{editable?<form onSubmit={event=>void submit(event)}>{!detail&&<label>Patient<select value={patientId} onChange={e=>setPatientId(e.target.value)} required disabled={busy}><option value="">Select a patient</option>{patients?.map(patient=><option key={patient.id} value={patient.id}>{patient.displayId} · {patient.name}</option>)}</select></label>}<label>Estimate title<input value={title} onChange={e=>{setTitle(e.target.value);setDirty(true);}} minLength={2} maxLength={120} required disabled={busy}/></label>{items.map((item,index)=><fieldset key={item.id} disabled={busy}><legend>Item {index+1}</legend><label>Treatment<input value={item.description} onChange={e=>updateItem(item.id,'description',e.target.value)} required minLength={2} maxLength={240}/></label><label>Tooth/site (optional)<input value={item.tooth} onChange={e=>updateItem(item.id,'tooth',e.target.value)} maxLength={40}/></label><label>Quantity<input type="number" min={1} max={100} step={1} value={item.quantity} onChange={e=>updateItem(item.id,'quantity',Number(e.target.value))} required/></label><label>Unit price (PKR)<input inputMode="decimal" value={item.unitPrice} onChange={e=>updateItem(item.id,'unitPrice',e.target.value)} required/></label><button type="button" disabled={items.length===1} onClick={()=>{setDirty(true);setItems(rows=>rows.filter(row=>row.id!==item.id));}}>Remove item</button></fieldset>)}<button type="button" disabled={busy||items.length>=100} onClick={()=>{setDirty(true);setItems(rows=>[...rows,newItem()]);}}>Add treatment item</button><label>Estimate notes<textarea value={note} onChange={e=>{setNote(e.target.value);setDirty(true);}} maxLength={1000} disabled={busy}/></label><button disabled={busy}>{busy?'Saving…':detail?'Save new estimate version':'Create estimate'}</button></form>:snapshot&&<Snapshot snapshot={snapshot}/>}{detail?.canAccept&&<form onSubmit={event=>void submit(event,true)}><h3>Record patient acceptance</h3><p>Confirm agreement to saved version {detail.plan.version} totaling {moneyMinor(snapshot!.totalMinor)}. Record who agreed and how that agreement was confirmed.</p>{dirty&&<p>Save or reload your changes before accepting the estimate.</p>}<label>Patient or representative name<input value={acceptedBy} onChange={e=>setAcceptedBy(e.target.value)} required minLength={2} maxLength={160} disabled={busy}/></label><label>Acceptance evidence<textarea value={evidence} onChange={e=>setEvidence(e.target.value)} required minLength={3} maxLength={500} disabled={busy}/></label><button disabled={busy||dirty}>Record acceptance and lock prices</button></form>}</>;
}
