'use client';
import { createContext,useContext,useEffect,useState,type FormEvent,type ReactNode } from 'react';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { CalendarDays,LayoutDashboard,Users,Wallet,Receipt,LockKeyhole,Stethoscope,ShieldCheck,MessageCircle,BarChart3 } from 'lucide-react';
export type ClinicScope={clinicId:string;clinicName:string;branchId:string;branchName:string;currency:string;timezone:string;permissions:string[]};
type Session={scope:ClinicScope;can:(permission:string)=>boolean};
const SessionContext=createContext<Session|null>(null);
export function useClinic(){const value=useContext(SessionContext);if(!value)throw new Error('Clinic session is required.');return value;}
export async function api(url:string,init?:RequestInit){const r=await fetch(url,{cache:'no-store',...init});const data=await r.json();if(!r.ok)throw Object.assign(new Error(data.error?.message||'The request could not be completed.'),{status:r.status,code:data.error?.code});return data;}
export function scopeHeaders(scope:ClinicScope){return {'x-clinic-id':scope.clinicId,'x-branch-id':scope.branchId,'Content-Type':'application/json'};}
const nav=[{href:'/plans',name:'Treatment plans',icon:Stethoscope},{href:'/reports',name:'Reports',icon:BarChart3},{href:'/clinical',name:'Clinical visits',icon:Stethoscope},{href:'/communications',name:'Communications',icon:MessageCircle},{href:'/',name:'Overview',icon:LayoutDashboard},{href:'/patients',name:'Patients',icon:Users},{href:'/appointments',name:'Appointments',icon:CalendarDays},{href:'/billing',name:'Billing',icon:Wallet},{href:'/expenses',name:'Expenses',icon:Receipt},{href:'/closing',name:'Daily closing',icon:LockKeyhole}];
export function ClinicSession({children}:{children:ReactNode}){
 const path=usePathname();const [scopes,setScopes]=useState<ClinicScope[]|null>(null);const [selected,setSelected]=useState('');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{const controller=new AbortController();fetch('/api/v1/session',{cache:'no-store',signal:controller.signal}).then(async r=>{const data=await r.json();if(controller.signal.aborted)return;if(r.ok){setScopes(data.scopes);const saved=sessionStorage.getItem('clinic-branch');setSelected(data.scopes.some((s:ClinicScope)=>s.branchId===saved)?saved:data.scopes[0]?.branchId||'');}else if(r.status!==401)setError(data.error?.message||'Unable to load your clinic access.');setLoading(false);}).catch(()=>{if(!controller.signal.aborted){setError('Unable to connect. Reload to try again.');setLoading(false);}});return()=>controller.abort();},[]);
 async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setError('');const form=new FormData(e.currentTarget);try{await api('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:form.get('email'),password:form.get('password')})});const data=await api('/api/v1/session');setScopes(data.scopes);setSelected(data.scopes[0]?.branchId||'');}catch(e){setError(e instanceof Error?e.message:'Sign-in failed.');}finally{setBusy(false);}}
 async function logout(){setBusy(true);setError('');try{await api('/api/auth/logout',{method:'POST'});setScopes(null);setSelected('');sessionStorage.removeItem('clinic-branch');}catch(e){setError(e instanceof Error?e.message:'Sign-out failed.');}finally{setBusy(false);}}
 if(loading)return <main className="staff-workspace"><section role="status"><h1>Opening your clinic…</h1><p>Checking your staff session.</p></section></main>;
 if(scopes===null)return <main className="staff-workspace live-login"><div className="brand"><span className="brand-icon"><Stethoscope size={24}/></span><span>Dental<span className="brand-light">space</span></span></div><section><h1>Staff sign-in</h1><p>Access your clinic’s saved patient records and appointments.</p>{error&&<p role="alert" className="staff-error">{error}</p>}<form onSubmit={login}><label>Email<input name="email" type="email" autoComplete="username" required maxLength={254}/></label><label>Password<input name="password" type="password" autoComplete="current-password" required maxLength={256}/></label><button disabled={busy}>{busy?'Signing in…':'Sign in'}</button></form></section></main>;
 const scope=scopes.find(s=>s.branchId===selected);
 if(!scope)return <main className="staff-workspace"><section><h1>No active clinic access</h1><p>Your signed-in account needs an active branch membership.</p>{error&&<p role="alert">{error}</p>}<button disabled={busy} onClick={logout}>Sign out</button></section></main>;
 return <SessionContext.Provider value={{scope,can:p=>scope.permissions.includes(p)}}><div className="workspace live-workspace"><aside className="sidebar"><Link href="/" className="brand"><span className="brand-icon"><Stethoscope size={23}/></span><span>Dental<span className="brand-light">space</span><small>CLINIC WORKSPACE</small></span></Link><div className="clinic-label"><span className="clinic-avatar">{scope.clinicName[0]}</span><div>{scope.clinicName}<small>{scope.branchName}</small></div></div><p className="nav-label">WORKSPACE</p><nav aria-label="Main navigation">{nav.map(({href,name,icon:Icon})=><Link href={href} key={href} className={`nav-link ${path===href?'active':''}`} aria-current={path===href?'page':undefined}><Icon size={19}/>{name}</Link>)}</nav><div className="sidebar-note"><ShieldCheck size={22}/><strong>Saved clinic records</strong><p>Your access follows your clinic and branch permissions.</p></div></aside><div className="workspace-main"><header className="topbar"><span>Workspace <span className="breadcrumb">/</span><strong>{nav.find(n=>n.href===path)?.name||'Records'}</strong></span><div className="live-session-actions"><label className="sr-only" htmlFor="branch-select">Clinic and branch</label><select id="branch-select" disabled={busy} value={selected} onChange={e=>{setSelected(e.target.value);sessionStorage.setItem('clinic-branch',e.target.value);}}>{scopes.map(s=><option key={s.branchId} value={s.branchId}>{s.clinicName} · {s.branchName}</option>)}</select><button disabled={busy} onClick={logout}>Sign out</button></div></header><main className="page-content live-content" key={scope.branchId}>{error&&<p role="alert" className="form-error">{error}</p>}{children}</main></div></div></SessionContext.Provider>;
}
