'use client';
import { useRecordPatientView } from './header-tools';
import Link from 'next/link';
import { useEffect,useState,type FormEvent } from 'react';
import { categoryLabels,type TimelineResult } from '@/lib/timeline/contracts';
import { moneyMinor } from '@/lib/finance/contracts';
import { api,scopeHeaders,useClinic } from './session';
export function PatientTimeline({patientId}:{patientId:string}){useRecordPatientView(patientId);
 const {scope,can}=useClinic();const [result,setResult]=useState<TimelineResult|null>(null);const [categories,setCategories]=useState<TimelineResult['categories']>([]);const [category,setCategory]=useState('all');const [from,setFrom]=useState('');const [to,setTo]=useState('');const [filters,setFilters]=useState({category:'all',from:'',to:'',revision:0});const [cursors,setCursors]=useState<(string|null)[]>([null]);const [error,setError]=useState('');const cursor=cursors.at(-1);const allowed=can('patient.demographics.read');
 useEffect(()=>{if(!allowed)return;const c=new AbortController();const query=new URLSearchParams({category:filters.category,...(filters.from?{from:filters.from}:{}),...(filters.to?{to:filters.to}:{}),...(cursor?{cursor}:{})});api(`/api/v1/patients/${patientId}/timeline?${query}`,{headers:scopeHeaders(scope),signal:c.signal}).then(data=>{if(!c.signal.aborted){setResult(data);setCategories(data.categories);setError('');}}).catch(e=>{if(!c.signal.aborted){setResult(null);setError(e.message);}});return()=>c.abort();},[scope,patientId,filters,cursor,allowed]);
 function apply(event:FormEvent){event.preventDefault();if(from&&to&&from>to){setError('Choose an ordered date range.');return;}setResult(null);setError('');setCursors([null]);setFilters(f=>({category,from,to,revision:f.revision+1}));}
 const instant=(value:string)=>new Date(value).toLocaleString('en-PK',{timeZone:scope.timezone,dateStyle:'medium',timeStyle:'short'});
 if(!allowed)return <section className="staff-workspace live-inner"><h1>Patient timeline</h1><p>Patient demographic read access is required.</p></section>;
 return <div className="staff-workspace live-inner"><Link href="/patients">Back to patients</Link><h1>{result?`${result.patient.name} — timeline`:'Patient timeline'}</h1>{result&&<p>{result.patient.displayId} · {scope.branchName} · {scope.timezone}</p>}<p>Newest activity first. Clinical, finance and communication records appear according to your access. Patient registration is clinic-wide; other activity is for the selected branch.</p>{error&&<p className="staff-error" role="alert">{error}</p>}<section><form onSubmit={apply}><label>Activity type<select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All permitted activity</option>{categories.map(value=><option key={value} value={value}>{categoryLabels[value]}</option>)}</select></label><label>From activity date<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To activity date<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button>Apply / refresh</button></form></section>{result?<section aria-label="Patient history">{result.events.length?<ol>{result.events.map(event=><li key={event.key} className="timeline-entry"><p><time dateTime={event.occurredAt}>{instant(event.occurredAt)}</time> · {categoryLabels[event.category]}</p><h2>{event.summary}</h2><p>{event.actorName}</p>{event.amountMinor!==null&&<p>{moneyMinor(event.amountMinor)}</p>}{event.scheduledAt&&<p>Appointment time: {instant(event.scheduledAt)}</p>}{event.eventDate&&<p>{event.category==='billing'?'Billing business date':event.category==='plans'?'Performed date':event.category==='clinical'?'History review date':'Due date'}: {event.eventDate}</p>}<Link href={event.href}>Open record</Link></li>)}</ol>:<p>No permitted activity matches these filters.</p>}<div className="live-pagination"><button disabled={cursors.length===1} onClick={()=>{setResult(null);setError('');setCursors(stack=>stack.slice(0,-1));}}>Newer events</button><span>Page {cursors.length}</span><button disabled={!result.nextCursor} onClick={()=>{setResult(null);setError('');setCursors(stack=>[...stack,result.nextCursor]);}}>Older events</button></div></section>:!error&&<p role="status">Loading patient history…</p>}</div>;
}
