'use client';
import Link from 'next/link';
import { CurrentClinicalContext } from './patient-clinical';
import type { ComponentProps } from 'react';
import { useRouter } from 'next/navigation';
import { useEffect,useRef,useState,type FormEvent } from 'react';
import { type ClinicalBody } from '@/lib/visits/contracts';
import { api,scopeHeaders,useClinic } from './session';
const labels:Record<keyof ClinicalBody,string>={complaint:'Chief complaint',history:'Relevant history',examination:'Examination',assessment:'Assessment',treatment:'Treatment provided',advice:'Advice and follow-up plan',followUpOn:'Follow-up date'};
type VisitListItem={id:string;patientName:string;status:string;authorName:string;createdAt:string};
export function ClinicalVisits(){
 const {scope,can}=useClinic();const router=useRouter();const [patients,setPatients]=useState<{id:string;name:string;displayId:string}[]>([]);const [search,setSearch]=useState('');const [visits,setVisits]=useState<VisitListItem[]|null>(null);const [offset,setOffset]=useState(0);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const operation=useRef<{id:string;patientId:string}|null>(null);const allowed=can('patient.clinical.read')&&can('patient.demographics.read');
 useEffect(()=>{if(!allowed)return;const c=new AbortController();api(`/api/v1/visits?offset=${offset}`,{headers:scopeHeaders(scope),signal:c.signal}).then(data=>{if(!c.signal.aborted)setVisits(data.visits);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[scope,offset,allowed]);
 useEffect(()=>{if(!allowed||!can('visit.draft.write'))return;const c=new AbortController();api(`/api/v1/patients?search=${encodeURIComponent(search)}`,{headers:scopeHeaders(scope),signal:c.signal}).then(data=>{if(!c.signal.aborted)setPatients(data.patients);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[scope,search,allowed,can]);
 async function start(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const patientId=String(new FormData(e.currentTarget).get('patientId'));if(operation.current&&operation.current.patientId!==patientId){setError('Resolve the original visit request before selecting another patient.');return;}operation.current??={id:crypto.randomUUID(),patientId};setBusy(true);setError('');try{const data=await api('/api/v1/visits',{method:'POST',headers:scopeHeaders(scope),body:JSON.stringify({patientId,operationId:operation.current.id})});operation.current=null;router.push(`/visits/${data.visit.id}`);}catch(e){if(e instanceof Error&&'status' in e&&Number(e.status)>=400&&Number(e.status)<500)operation.current=null;setError(e instanceof Error?e.message:'Unable to start visit.');}finally{setBusy(false);}}
 if(!allowed)return <section className="staff-workspace live-inner"><h1>Clinical visits</h1><p>Your account needs clinical and patient demographic read access.</p></section>;
 return <div className="staff-workspace live-inner"><h1>Clinical visits</h1><p>Saved notes for {scope.branchName}. Clinical access is separate from patient management.</p>{error&&<p role="alert" className="staff-error">{error}</p>}{can('visit.draft.write')&&<section><h2>Start a walk-in visit</h2><label>Find patient<input value={search} disabled={busy} onChange={e=>setSearch(e.target.value)} placeholder="Search name or phone"/></label><form onSubmit={start}><label>Patient<select name="patientId" required disabled={busy}><option value="">Select patient</option>{patients.map(p=><option key={p.id} value={p.id}>{p.name} · {p.displayId}</option>)}</select></label><button disabled={busy}>{busy?'Starting…':'Start visit draft'}</button></form></section>}<section><h2>Recent visits</h2>{visits?<><ul>{visits.map(v=><li key={v.id}><div><strong>{v.patientName}</strong><p>{v.status} · {v.authorName} · {new Date(v.createdAt).toLocaleString()}</p></div><Link href={`/visits/${v.id}`}>Open visit</Link></li>)}</ul>{!visits.length&&<p>No visits recorded.</p>}<div className="live-pagination"><button disabled={offset===0||busy} onClick={()=>{setVisits(null);setOffset(n=>n-50);}}>Previous</button><span>Page {offset/50+1}</span><button disabled={visits.length<50||busy} onClick={()=>{setVisits(null);setOffset(n=>n+50);}}>Next</button></div></>:!error&&<p role="status">Loading visits…</p>}</section></div>;
}
type Detail={clinical:ComponentProps<typeof CurrentClinicalContext>['initial'];visit:{id:string;patientId:string;status:string;version:number;body:ClinicalBody};patientName:string;patientDisplayId:string;authorName:string;canEdit:boolean;canFinalize:boolean;revisions:{id:string;revision:number;kind:string;reason:string;body:ClinicalBody;authorName:string;signedAt:string}[]};
export function ClinicalVisit({visitId}:{visitId:string}){
 const {scope,can}=useClinic();const [data,setData]=useState<Detail|null>(null);const [error,setError]=useState('');const [revision,setRevision]=useState(0);const [notice,setNotice]=useState('');const allowed=can('patient.clinical.read')&&can('patient.demographics.read');
 useEffect(()=>{if(!allowed)return;const c=new AbortController();api(`/api/v1/visits/${visitId}`,{headers:scopeHeaders(scope),signal:c.signal}).then(result=>{if(!c.signal.aborted)setData(result);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[scope,visitId,revision,allowed]);
 const saved=(message:string)=>{setNotice(message);setError('');setData(null);setRevision(n=>n+1);};
 if(!allowed)return <section className="staff-workspace live-inner"><h1>Clinical visit</h1><p>Clinical read access is required.</p></section>;
 return <div className="staff-workspace live-inner"><Link href="/clinical">Back to visits</Link>{error&&<p role="alert" className="staff-error">{error}</p>}{notice&&<p role="status">{notice}</p>}{data?<><h1>{data.patientName}</h1><p>{data.patientDisplayId} · {data.visit.status} · Author: {data.authorName}</p>{can('followup.read')&&can('followup.write')&&<Link href={`/follow-ups?visitId=${data.visit.id}`}>Create linked follow-up</Link>}<CurrentClinicalContext patientId={data.visit.patientId} initial={data.clinical}/><VisitNoteForm key={data.visit.version} detail={data} onSaved={saved}/><section><h2>Signed revision history</h2>{!data.revisions.length&&<p>No signed revisions. This note is a draft.</p>}{data.revisions.map(r=><details key={r.id}><summary>Revision {r.revision} · {r.kind} · {r.authorName} · {new Date(r.signedAt).toLocaleString()}</summary>{r.reason&&<p>Reason: {r.reason}</p>}<NoteBody body={r.body}/></details>)}</section></>:!error&&<p role="status">Loading clinical note…</p>}</div>;
}
function NoteBody({body}:{body:ClinicalBody}){return <dl>{(Object.keys(labels) as (keyof ClinicalBody)[]).map(key=><div key={key}><dt><strong>{labels[key]}</strong></dt><dd className="clinical-note-text">{body[key]||'—'}</dd></div>)}</dl>;}
function VisitNoteForm({detail,onSaved}:{detail:Detail;onSaved:(message:string)=>void}){
 const {scope}=useClinic();const [body,setBody]=useState(detail.visit.body);const [reason,setReason]=useState('');const [amending,setAmending]=useState(false);const [busy,setBusy]=useState(false);const [dirty,setDirty]=useState(false);const [error,setError]=useState('');const operation=useRef<{id:string;payload:string}|null>(null);const draft=detail.visit.status==='draft';const editable=draft?detail.canEdit:amending&&detail.canFinalize;
 async function action(kind:'save'|'sign'|'amend'){if(busy)return;const values=kind==='save'?{expectedVersion:detail.visit.version,body}:kind==='amend'?{expectedVersion:detail.visit.version,body,reason}:{expectedVersion:detail.visit.version};const payload=JSON.stringify({kind,...values});if(kind!=='save'){if(operation.current&&operation.current.payload!==payload){setError('Resolve the previous signing request before changing its details.');return;}operation.current??={id:crypto.randomUUID(),payload};}setBusy(true);setError('');try{await api(`/api/v1/visits/${detail.visit.id}${kind==='sign'?'/finalize':kind==='amend'?'/amendments':''}`,{method:kind==='save'?'PATCH':'POST',headers:scopeHeaders(scope),body:JSON.stringify(kind==='save'?values:{...values,operationId:operation.current!.id})});operation.current=null;onSaved(kind==='save'?'Draft saved.':kind==='sign'?'Clinical note signed.':'Amendment signed; the earlier revision is preserved.');}catch(e){if(e instanceof Error&&'status' in e&&Number(e.status)>=400&&Number(e.status)<500&&(!('code' in e)||e.code!=='OPERATION_CONFLICT'))operation.current=null;setError(e instanceof Error?e.message:'Clinical note could not be saved.');}finally{setBusy(false);}}
 return <section><h2>{draft?'Visit note draft':amending?'Create signed amendment':'Signed clinical note'}</h2>{error&&<p role="alert" className="staff-error">{error}</p>}{editable?<form onSubmit={e=>{e.preventDefault();void action(amending?'amend':'save');}}>{(Object.keys(labels) as (keyof ClinicalBody)[]).map(key=><label key={key}>{labels[key]}{key==='followUpOn'?<input type="date" value={body[key]} disabled={busy} onChange={e=>{setBody(b=>({...b,[key]:e.target.value}));setDirty(true);}}/>:<textarea maxLength={12000} value={body[key]} disabled={busy} onChange={e=>{setBody(b=>({...b,[key]:e.target.value}));setDirty(true);}}/>}</label>)}{amending&&<label>Reason for amendment<input value={reason} required minLength={3} maxLength={500} disabled={busy} onChange={e=>setReason(e.target.value)}/></label>}<button disabled={busy}>{busy?'Saving…':amending?'Sign amendment':'Save draft'}</button></form>:<NoteBody body={body}/>} {draft&&detail.canFinalize&&<><p>Review the saved note before signing. Signed revisions cannot be overwritten.</p><button disabled={busy||dirty} onClick={()=>void action('sign')}>Sign saved clinical note</button>{dirty&&<p>Save the draft before signing.</p>}</>}{!draft&&detail.canFinalize&&!amending&&<button disabled={busy} onClick={()=>setAmending(true)}>Create amendment</button>}</section>;
}
